// GENERATED by scripts/build-alphabet-figure.mjs — do not edit by hand.
//
// The 44 vertex letters of the regular palette, each with the site symmetry it carries. Recovered
// from the shipped table (tools/ctrnact-oracle/reference/eu_solver.orig.cpp) by finding, for every
// entry, the unique subgroup of the configuration word's symmetry group whose dart orbits the
// entry's label array transverses. Re-run the script to check: it verifies |H| against the fold
// size, |N(H)/H| against ferkval, and that the entries land one per conjugacy class — which is the
// statement the number 44 rests on (appendix lemma A2(iii)).
//
// `rot` is the order of the rotation about the vertex; `axes` are the mirror lines through it, in
// degrees, in the frame where stub 0 points along +x and the word runs counterclockwise — the frame
// figureFromWord() builds. `onStub` marks an axis running along a half-edge, as against one
// bisecting a corner.

export interface AlphabetLetter {
	/** the table's own code, "3a" through "6j", ordered by vertex degree */
	code: string;
	/** "(3,6,3,6)A2" — configuration and site-symmetry variant */
	symbol: string;
	word: number[];
	/** the variant suffix alone: "S4", "R2", "A1", "F", or "" where the configuration has one letter */
	variant: string;
	rot: number;
	axes: { deg: number; onStub: boolean }[];
}

export const ALPHABET_44: AlphabetLetter[] = [
	{ code: "3a", symbol: "(3,12,12)A", word: [12, 12, 3], variant: "A", rot: 1, axes: [{ deg: 150, onStub: true }] },
	{ code: "3b", symbol: "(3,12,12)F", word: [12, 12, 3], variant: "F", rot: 1, axes: [] },
	{ code: "3c", symbol: "(4,6,12)", word: [12, 6, 4], variant: "", rot: 1, axes: [] },
	{ code: "3d", symbol: "(6,6,6)S", word: [6, 6, 6], variant: "S", rot: 3, axes: [{ deg: 0, onStub: true }, { deg: 60, onStub: true }, { deg: 120, onStub: true }] },
	{ code: "3e", symbol: "(6,6,6)R", word: [6, 6, 6], variant: "R", rot: 3, axes: [] },
	{ code: "3f", symbol: "(6,6,6)A", word: [6, 6, 6], variant: "A", rot: 1, axes: [{ deg: 0, onStub: true }] },
	{ code: "3g", symbol: "(6,6,6)F", word: [6, 6, 6], variant: "F", rot: 1, axes: [] },
	{ code: "4a", symbol: "(3,3,4,12)", word: [12, 4, 3, 3], variant: "", rot: 1, axes: [] },
	{ code: "4b", symbol: "(3,4,3,12)A", word: [12, 3, 4, 3], variant: "A", rot: 1, axes: [{ deg: 75, onStub: false }] },
	{ code: "4c", symbol: "(3,4,3,12)F", word: [12, 3, 4, 3], variant: "F", rot: 1, axes: [] },
	{ code: "4d", symbol: "(3,3,6,6)A", word: [6, 6, 3, 3], variant: "A", rot: 1, axes: [{ deg: 120, onStub: true }] },
	{ code: "4e", symbol: "(3,3,6,6)F", word: [6, 6, 3, 3], variant: "F", rot: 1, axes: [] },
	{ code: "4f", symbol: "(3,6,3,6)S", word: [6, 3, 6, 3], variant: "S", rot: 2, axes: [{ deg: 60, onStub: false }, { deg: 150, onStub: false }] },
	{ code: "4g", symbol: "(3,6,3,6)R", word: [6, 3, 6, 3], variant: "R", rot: 2, axes: [] },
	{ code: "4h", symbol: "(3,6,3,6)A1", word: [6, 3, 6, 3], variant: "A1", rot: 1, axes: [{ deg: 150, onStub: false }] },
	{ code: "4i", symbol: "(3,6,3,6)A2", word: [6, 3, 6, 3], variant: "A2", rot: 1, axes: [{ deg: 60, onStub: false }] },
	{ code: "4j", symbol: "(3,6,3,6)F", word: [6, 3, 6, 3], variant: "F", rot: 1, axes: [] },
	{ code: "4k", symbol: "(3,4,4,6)", word: [6, 4, 4, 3], variant: "", rot: 1, axes: [] },
	{ code: "4l", symbol: "(3,4,6,4)A", word: [6, 4, 3, 4], variant: "A", rot: 1, axes: [{ deg: 60, onStub: false }] },
	{ code: "4m", symbol: "(3,4,6,4)F", word: [6, 4, 3, 4], variant: "F", rot: 1, axes: [] },
	{ code: "4n", symbol: "(4,4,4,4)S4", word: [4, 4, 4, 4], variant: "S4", rot: 4, axes: [{ deg: 0, onStub: true }, { deg: 45, onStub: false }, { deg: 90, onStub: true }, { deg: 135, onStub: false }] },
	{ code: "4o", symbol: "(4,4,4,4)R4", word: [4, 4, 4, 4], variant: "R4", rot: 4, axes: [] },
	{ code: "4p", symbol: "(4,4,4,4)S2a", word: [4, 4, 4, 4], variant: "S2a", rot: 2, axes: [{ deg: 0, onStub: true }, { deg: 90, onStub: true }] },
	{ code: "4q", symbol: "(4,4,4,4)S2b", word: [4, 4, 4, 4], variant: "S2b", rot: 2, axes: [{ deg: 45, onStub: false }, { deg: 135, onStub: false }] },
	{ code: "4r", symbol: "(4,4,4,4)R2", word: [4, 4, 4, 4], variant: "R2", rot: 2, axes: [] },
	{ code: "4s", symbol: "(4,4,4,4)A1", word: [4, 4, 4, 4], variant: "A1", rot: 1, axes: [{ deg: 0, onStub: true }] },
	{ code: "4t", symbol: "(4,4,4,4)A2", word: [4, 4, 4, 4], variant: "A2", rot: 1, axes: [{ deg: 45, onStub: false }] },
	{ code: "4u", symbol: "(4,4,4,4)F", word: [4, 4, 4, 4], variant: "F", rot: 1, axes: [] },
	{ code: "5a", symbol: "(3,3,3,3,6)A", word: [6, 3, 3, 3, 3], variant: "A", rot: 1, axes: [{ deg: 60, onStub: true }] },
	{ code: "5b", symbol: "(3,3,3,3,6)F", word: [6, 3, 3, 3, 3], variant: "F", rot: 1, axes: [] },
	{ code: "5c", symbol: "(3,3,3,4,4)A", word: [4, 4, 3, 3, 3], variant: "A", rot: 1, axes: [{ deg: 90, onStub: true }] },
	{ code: "5d", symbol: "(3,3,3,4,4)F", word: [4, 4, 3, 3, 3], variant: "F", rot: 1, axes: [] },
	{ code: "5e", symbol: "(3,3,4,3,4)A", word: [4, 3, 4, 3, 3], variant: "A", rot: 1, axes: [{ deg: 120, onStub: true }] },
	{ code: "5f", symbol: "(3,3,4,3,4)F", word: [4, 3, 4, 3, 3], variant: "F", rot: 1, axes: [] },
	{ code: "6a", symbol: "(3,3,3,3,3,3)S6", word: [3, 3, 3, 3, 3, 3], variant: "S6", rot: 6, axes: [{ deg: 0, onStub: true }, { deg: 30, onStub: false }, { deg: 60, onStub: true }, { deg: 90, onStub: false }, { deg: 120, onStub: true }, { deg: 150, onStub: false }] },
	{ code: "6b", symbol: "(3,3,3,3,3,3)R6", word: [3, 3, 3, 3, 3, 3], variant: "R6", rot: 6, axes: [] },
	{ code: "6c", symbol: "(3,3,3,3,3,3)S3a", word: [3, 3, 3, 3, 3, 3], variant: "S3a", rot: 3, axes: [{ deg: 0, onStub: true }, { deg: 60, onStub: true }, { deg: 120, onStub: true }] },
	{ code: "6d", symbol: "(3,3,3,3,3,3)S3b", word: [3, 3, 3, 3, 3, 3], variant: "S3b", rot: 3, axes: [{ deg: 30, onStub: false }, { deg: 90, onStub: false }, { deg: 150, onStub: false }] },
	{ code: "6e", symbol: "(3,3,3,3,3,3)R3", word: [3, 3, 3, 3, 3, 3], variant: "R3", rot: 3, axes: [] },
	{ code: "6f", symbol: "(3,3,3,3,3,3)S2", word: [3, 3, 3, 3, 3, 3], variant: "S2", rot: 2, axes: [{ deg: 0, onStub: true }, { deg: 90, onStub: false }] },
	{ code: "6g", symbol: "(3,3,3,3,3,3)R2", word: [3, 3, 3, 3, 3, 3], variant: "R2", rot: 2, axes: [] },
	{ code: "6h", symbol: "(3,3,3,3,3,3)A1", word: [3, 3, 3, 3, 3, 3], variant: "A1", rot: 1, axes: [{ deg: 0, onStub: true }] },
	{ code: "6i", symbol: "(3,3,3,3,3,3)A2", word: [3, 3, 3, 3, 3, 3], variant: "A2", rot: 1, axes: [{ deg: 150, onStub: false }] },
	{ code: "6j", symbol: "(3,3,3,3,3,3)F", word: [3, 3, 3, 3, 3, 3], variant: "F", rot: 1, axes: [] },
];
