// GENERATED by scripts/build-compat-graph.ts — do not edit by hand.
//
// The compatibility graph over the fifteen vertex configurations that appear in a tiling of the
// plane: an edge joins two of them when they can sit at the two ends of one edge of a tiling, which
// is `VertexConfiguration.isCompatible` — the same test the seed extractor runs. Mirror pairs are
// merged, so the names are the ones the deck has already used.

export interface CompatNode {
	/** "3.4.6.4", the canonical name. */
	word: string;
	/** How many of the other fourteen it can meet. */
	degree: number;
}

/** In the deck's own order: the fifteen as they appear on the vertex-configuration slide. */
export const COMPAT_NODES: CompatNode[] = [
	{ word: "3.3.3.3.3.3", degree: 5 },
	{ word: "3.3.3.3.6", degree: 7 },
	{ word: "3.3.3.4.4", degree: 9 },
	{ word: "3.3.4.3.4", degree: 8 },
	{ word: "3.3.4.12", degree: 10 },
	{ word: "3.3.6.6", degree: 8 },
	{ word: "3.4.3.12", degree: 6 },
	{ word: "3.4.4.6", degree: 10 },
	{ word: "3.4.6.4", degree: 6 },
	{ word: "3.6.3.6", degree: 3 },
	{ word: "3.12.12", degree: 2 },
	{ word: "4.4.4.4", degree: 2 },
	{ word: "4.6.12", degree: 3 },
	{ word: "4.8.8", degree: 0 },
	{ word: "6.6.6", degree: 1 },
];

/** Unordered, each pair once, in node order. */
export const COMPAT_EDGES: [string, string][] = [
	["3.3.3.3.3.3", "3.3.3.3.6"],
	["3.3.3.3.3.3", "3.3.3.4.4"],
	["3.3.3.3.3.3", "3.3.4.3.4"],
	["3.3.3.3.3.3", "3.3.4.12"],
	["3.3.3.3.3.3", "3.3.6.6"],
	["3.3.3.3.6", "3.3.3.4.4"],
	["3.3.3.3.6", "3.3.4.3.4"],
	["3.3.3.3.6", "3.3.4.12"],
	["3.3.3.3.6", "3.3.6.6"],
	["3.3.3.3.6", "3.4.4.6"],
	["3.3.3.3.6", "3.6.3.6"],
	["3.3.3.4.4", "3.3.4.3.4"],
	["3.3.3.4.4", "3.3.4.12"],
	["3.3.3.4.4", "3.3.6.6"],
	["3.3.3.4.4", "3.4.3.12"],
	["3.3.3.4.4", "3.4.4.6"],
	["3.3.3.4.4", "3.4.6.4"],
	["3.3.3.4.4", "4.4.4.4"],
	["3.3.4.3.4", "3.3.4.12"],
	["3.3.4.3.4", "3.3.6.6"],
	["3.3.4.3.4", "3.4.3.12"],
	["3.3.4.3.4", "3.4.4.6"],
	["3.3.4.3.4", "3.4.6.4"],
	["3.3.4.12", "3.3.6.6"],
	["3.3.4.12", "3.4.3.12"],
	["3.3.4.12", "3.4.4.6"],
	["3.3.4.12", "3.4.6.4"],
	["3.3.4.12", "3.12.12"],
	["3.3.4.12", "4.6.12"],
	["3.3.6.6", "3.4.4.6"],
	["3.3.6.6", "3.6.3.6"],
	["3.3.6.6", "6.6.6"],
	["3.4.3.12", "3.4.4.6"],
	["3.4.3.12", "3.4.6.4"],
	["3.4.3.12", "3.12.12"],
	["3.4.4.6", "3.4.6.4"],
	["3.4.4.6", "3.6.3.6"],
	["3.4.4.6", "4.4.4.4"],
	["3.4.4.6", "4.6.12"],
	["3.4.6.4", "4.6.12"],
];
