// GENERATED by scripts/build-compat-tilings.ts — do not edit by hand.
//
// The tilings the compatibility-graph slide cycles through: the vertex configurations each one uses
// and, more to the point, which of them it actually places at the two ends of an edge. Read off the
// tiling's own cell. Every entry was checked at build time to place only pairs the compatibility
// relation permits, and to be CONNECTED through those pairs — which is the claim the slide makes.

export interface CompatTiling {
	id: string;
	k: number;
	/** The configurations at its vertices, as named in COMPAT_NODES. */
	words: string[];
	/** Which of them meet along an edge OF THIS TILING. A subset of the compatibility graph's edges. */
	pairs: [string, string][];
	/** The configuration of each vertex orbit, by orbit id: the ids the orbit overlay colours by. */
	orbitWords: string[];
}

export const COMPAT_TILINGS: CompatTiling[] = [
	{ id: "t2001", k: 2, words: ["3.4.6.4", "4.6.12"], pairs: [["3.4.6.4", "4.6.12"]], orbitWords: ["4.6.12", "3.4.6.4"] },
	{ id: "t2006", k: 2, words: ["3.4.4.6", "3.6.3.6"], pairs: [["3.4.4.6", "3.6.3.6"]], orbitWords: ["3.4.4.6", "3.6.3.6"] },
	{ id: "t2011", k: 2, words: ["3.3.6.6", "3.6.3.6"], pairs: [["3.3.6.6", "3.6.3.6"]], orbitWords: ["3.3.6.6", "3.6.3.6"] },
	{ id: "t2016", k: 2, words: ["3.3.3.4.4", "3.3.4.3.4"], pairs: [["3.3.3.4.4", "3.3.4.3.4"]], orbitWords: ["3.3.3.4.4", "3.3.4.3.4"] },
	{ id: "t3001", k: 3, words: ["3.3.6.6", "3.6.3.6", "6.6.6"], pairs: [["3.3.6.6", "3.6.3.6"], ["3.3.6.6", "6.6.6"]], orbitWords: ["3.6.3.6", "3.3.6.6", "6.6.6"] },
	{ id: "t3016", k: 3, words: ["3.3.3.4.4", "4.4.4.4"], pairs: [["3.3.3.4.4", "4.4.4.4"]], orbitWords: ["3.3.3.4.4", "4.4.4.4", "4.4.4.4"] },
	{ id: "t3031", k: 3, words: ["3.3.6.6", "3.4.4.6", "3.6.3.6"], pairs: [["3.4.4.6", "3.6.3.6"], ["3.3.6.6", "3.6.3.6"]], orbitWords: ["3.3.6.6", "3.6.3.6", "3.4.4.6"] },
	{ id: "t3046", k: 3, words: ["3.3.3.3.6", "3.6.3.6"], pairs: [["3.3.3.3.6", "3.6.3.6"]], orbitWords: ["3.6.3.6", "3.3.3.3.6", "3.3.3.3.6"] },
	{ id: "t4001", k: 4, words: ["3.3.3.3.3.3", "3.3.6.6", "6.6.6"], pairs: [["3.3.3.3.3.3", "3.3.6.6"], ["3.3.6.6", "6.6.6"]], orbitWords: ["6.6.6", "6.6.6", "3.3.6.6", "3.3.3.3.3.3"] },
	{ id: "t4038", k: 4, words: ["3.3.3.4.4", "4.4.4.4"], pairs: [["3.3.3.4.4", "4.4.4.4"]], orbitWords: ["3.3.3.4.4", "4.4.4.4", "4.4.4.4", "4.4.4.4"] },
	{ id: "t4075", k: 4, words: ["3.3.3.3.3.3", "3.3.3.4.4", "4.4.4.4"], pairs: [["3.3.3.4.4", "4.4.4.4"], ["3.3.3.3.3.3", "3.3.3.4.4"]], orbitWords: ["3.3.3.3.3.3", "3.3.3.4.4", "3.3.3.3.3.3", "4.4.4.4"] },
	{ id: "t4112", k: 4, words: ["3.3.3.3.6", "3.3.6.6", "3.6.3.6"], pairs: [["3.3.3.3.6", "3.6.3.6"], ["3.3.6.6", "3.6.3.6"], ["3.3.3.3.6", "3.3.6.6"]], orbitWords: ["3.3.6.6", "3.3.6.6", "3.6.3.6", "3.3.3.3.6"] },
	{ id: "t5001", k: 5, words: ["3.3.3.4.4", "3.3.6.6", "3.4.4.6", "6.6.6"], pairs: [["3.3.6.6", "6.6.6"], ["3.3.6.6", "3.4.4.6"], ["3.3.3.4.4", "3.3.6.6"], ["3.3.3.4.4", "3.4.4.6"]], orbitWords: ["3.3.6.6", "6.6.6", "3.4.4.6", "6.6.6", "3.3.3.4.4"] },
	{ id: "t5084", k: 5, words: ["3.3.3.3.3.3", "3.3.3.4.4", "4.4.4.4"], pairs: [["3.3.3.3.3.3", "3.3.3.4.4"], ["3.3.3.4.4", "4.4.4.4"]], orbitWords: ["4.4.4.4", "3.3.3.4.4", "3.3.3.3.3.3", "3.3.3.4.4", "3.3.3.4.4"] },
	{ id: "t5167", k: 5, words: ["3.3.3.3.6", "3.3.3.4.4", "3.4.4.6", "3.6.3.6"], pairs: [["3.4.4.6", "3.6.3.6"], ["3.3.3.3.6", "3.6.3.6"], ["3.3.3.3.6", "3.3.3.4.4"]], orbitWords: ["3.3.3.4.4", "3.3.3.4.4", "3.3.3.3.6", "3.4.4.6", "3.6.3.6"] },
	{ id: "t5250", k: 5, words: ["3.3.3.3.6", "3.3.6.6", "3.6.3.6"], pairs: [["3.3.3.3.6", "3.3.6.6"], ["3.3.6.6", "3.6.3.6"], ["3.3.3.3.6", "3.6.3.6"]], orbitWords: ["3.6.3.6", "3.3.6.6", "3.3.3.3.6", "3.3.3.3.6", "3.6.3.6"] },
];
