import type { TranslationalCellData } from "@/lib/utils/renderTiling";
import type { ParametricCellData } from "@/lib/utils/paramCell";
import type { CatalogueTiling } from "@/lib/services/catalogueService";
import type { ExactCellSource } from "@/lib/services/cellCodecService";
import type { LatticeShape, WallpaperGroup } from "@/lib/classes/symmetry/types";

// The Reference (Oracle) shelf — a DISPLAY-ONLY atlas of known k-uniform tilings from the literature,
// deliberately kept OFF the certified-results catalogue (§0: the site never produces the claim; these
// are external oracles, not our search output). Generated by scripts/build-reference-atlas.ts into the
// static asset public/reference-atlas.json and lazy-fetched only when the shelf is opened.
//
//   - galebach: regular k=1..6 (Soto-Sánchez/Galebach), reconstructed geometry. No completeness proof.
//   - myers:    Myers star tilings (k=1 in-ring Fig-4 subclass today; k=2 pending the machine-readable
//               JSON). An unchecked hand enumeration — shown as reference, never as certified.
//   - ctrnact:  Marek Čtrnáct's k-uniform search, reproduced here (k=7 shown; k≤8 in figures/data/ctrnact.json).
//               An unproven exhaustive search extending Galebach beyond k=6 — reference, never certified.
//   - ctrnact-star: the Čtrnáct-engine star extension's full in-ring catalogs (feat/ctrnact-star),
//               k=1..2, star-bearing solutions only. Most reproduce Myers records; the ones flagged
//               candidate:true match NOTHING in Myers and are pending adversarial review.
export interface ReferenceTiling {
	id: string; // "t4001" (galebach) | "myers-k1-star-03" (myers) | "ctrnact-07_..." (ctrnact)
	source: "galebach" | "myers" | "ctrnact" | "ctrnact-star";
	k: number;
	family: string; // distinct polygon-type label, e.g. "3.4.6.12"; star tiles marked "n*"
	renderCell: TranslationalCellData; // float, parseBaseCell-ready
	alphaRange?: [number, number]; // degrees; present ⇒ one-parameter family with an alpha slider
	candidate?: boolean; // ctrnact-star only: not in Myers' enumeration — candidate new tiling
	preview?: boolean; // ctrnact-star only: from a PARTIAL (still-running) solve — incomplete, uncertified
	// Historical first-discoverer of this tiling (Kepler, Krötenheerdt, Chavey, Galebach, Čtrnáct,
	// Joseph Myers, Alessandro Longo). One attribute, orthogonal to certification.
	discoverer: string;
	// Rigorous completeness status of this tiling's enumeration level:
	//   proven      — this work's method has a completeness certificate (regular k≤3)
	//   reproduced  — count matches a published enumeration, not independently proven here
	//   candidate   — surfaced by this work; completeness / literature-novelty not established
	certification: "proven" | "reproduced" | "candidate";
	// Present on family entries: the proven parametric cell driving the /play alpha slider
	// (lib/utils/paramCell.ts). renderCell then holds the default-alpha evaluation (thumbnails).
	paramCell?: ParametricCellData;
	exactSource?: ExactCellSource; // exact cyclotomic cell for the symmetry overlay (added 2026-07)

	// Vertex-type classification (build-computed, 2026-07). k counts vertex ORBITS; m counts DISTINCT
	// vertex configurations among them (m ≤ k). `partition` is the multiplicities of those distinct
	// configs, descending, summing to k — e.g. m=3, partition [5,1,1] is the "511" group at k=7.
	// Absent when a source has no per-orbit config data (never guessed; the tiling is then excluded from
	// M/partition filters). m === k is the Krötenheerdt (maximal) class.
	m?: number;
	partition?: number[];
	// Exact wallpaper symmetry — REGULAR tilings only (WallpaperSymmetry needs exact convex-tile
	// intersection; star tiles are non-convex ⇒ omitted, NOTES §9.4). Absent for every star tiling.
	wallpaperGroup?: WallpaperGroup;
	latticeShape?: LatticeShape;
}

// The star folds an atlas actually uses (the n of each n* token): 3,4,6,8,9,12,18. Used to seed the
// star-fold filter without re-deriving from the whole atlas.
export const STAR_FOLDS = [3, 4, 6, 8, 9, 12, 18] as const;

// tileClass: a tiling is "star" iff its family carries a star token ("n*"); regular otherwise. This
// matches polygonClassLabel and is source-independent (myers/ctrnact-star always mark stars).
export function tileClassOf(t: Pick<ReferenceTiling, "family">): "regular" | "star" {
	return t.family.includes("*") ? "star" : "regular";
}

// The star folds present in a family (unique, ascending). "3.4*.6*" → [4,6]. Empty for regular.
export function starFoldsOf(t: Pick<ReferenceTiling, "family">): number[] {
	const folds = new Set<number>();
	for (const tok of t.family.split(".")) {
		if (tok.endsWith("*")) {
			const n = parseInt(tok, 10);
			if (Number.isFinite(n)) folds.add(n);
		}
	}
	return [...folds].sort((a, b) => a - b);
}

// A one-parameter (α-slider) family iff it carries an alphaRange. The rigid star tilings have none.
export function isParametric(t: Pick<ReferenceTiling, "alphaRange">): boolean {
	return Array.isArray(t.alphaRange);
}

// Canonical partition key for display + filtering: digits joined ("511"), switching to a "."
// separator if any part reaches 10 so "10,1" never collides with "1,0,1". Null when unclassified.
export function partitionKeyOf(t: Pick<ReferenceTiling, "partition">): string | null {
	if (!t.partition?.length) return null;
	const sep = t.partition.some((p) => p >= 10) ? "." : "";
	return t.partition.join(sep);
}

// Krötenheerdt (maximal): every orbit has a distinct vertex config, i.e. m === k. False when unclassified.
export function isMaximal(t: Pick<ReferenceTiling, "m" | "k">): boolean {
	return t.m != null && t.m === t.k;
}

export interface ReferenceFilter {
	kValue?: number; // single vertex-orbit count; unset = every k
	tileClass?: "regular" | "star"; // regular polygons only / star-bearing only
	mValue?: number; // single distinct-vertex-config count; unclassified tilings never match
	partitionKey?: string; // single partition key (e.g. "511"); unclassified tilings never match
	maximalOnly?: boolean; // Krötenheerdt: keep only m === k
	starFolds?: number[]; // keep tilings using at least one of these star folds
	parametric?: "rigid" | "family"; // rigid (no α) / one-parameter α-family
	wallpaperGroups?: WallpaperGroup[]; // exact group; unclassified (all stars) never match
	latticeShapes?: LatticeShape[]; // exact lattice shape; unclassified (all stars) never match
	discoverers?: string[]; // each entry's discoverer must be in this set
	certifications?: ReferenceTiling["certification"][]; // proven / reproduced / candidate
	polygonNames?: string[]; // each must appear in the tiling's family label
	query?: string; // free-text substring match on id or family (e.g. "4j5_5b2" or "3.6")
}

export function matchesReferenceFilters(t: ReferenceTiling, f: ReferenceFilter): boolean {
	if (f.kValue != null && t.k !== f.kValue) return false;
	if (f.tileClass && tileClassOf(t) !== f.tileClass) return false;
	// M/partition/maximal: an active filter EXCLUDES unclassified tilings rather than matching them —
	// completeness ethos, we never silently pass a tiling whose classification we don't have.
	if (f.mValue != null && t.m !== f.mValue) return false;
	if (f.partitionKey != null && partitionKeyOf(t) !== f.partitionKey) return false;
	if (f.maximalOnly && !isMaximal(t)) return false;
	if (f.starFolds?.length) {
		const folds = starFoldsOf(t);
		if (!f.starFolds.some((n) => folds.includes(n))) return false;
	}
	if (f.parametric) {
		const isFam = isParametric(t);
		if (f.parametric === "family" && !isFam) return false;
		if (f.parametric === "rigid" && isFam) return false;
	}
	if (f.wallpaperGroups?.length && (t.wallpaperGroup == null || !f.wallpaperGroups.includes(t.wallpaperGroup))) return false;
	if (f.latticeShapes?.length && (t.latticeShape == null || !f.latticeShapes.includes(t.latticeShape))) return false;
	if (f.discoverers?.length && !f.discoverers.includes(t.discoverer)) return false;
	if (f.certifications?.length && !f.certifications.includes(t.certification)) return false;
	if (f.polygonNames?.length) {
		const fam = t.family.split(".").map((s) => s.trim());
		if (!f.polygonNames.every((n) => fam.includes(n))) return false;
	}
	if (f.query?.trim()) {
		const q = f.query.trim().toLowerCase();
		if (!t.id.toLowerCase().includes(q) && !t.family.toLowerCase().includes(q)) return false;
	}
	return true;
}

// Adapt a reference tiling to the CatalogueTiling shape so the /play viewer (Canvas + Sidebar, all
// keyed on canonicalKey) renders it unchanged. `id` stands in for canonicalKey; certified is always
// false (these are oracles, not our proven results) — the /play sidebar is told mode="reference" so it
// shows an "Oracle" pill instead of the misleading "Candidate" badge.
export function referenceToCatalogue(r: ReferenceTiling): CatalogueTiling {
	return {
		canonicalKey: r.id,
		k: r.k,
		family: r.family,
		renderCell: r.renderCell,
		certified: false,
		runIds: [],
		exactSource: r.exactSource,
		paramCell: r.paramCell,
	};
}

// Lazy client-side fetch of the static atlas. Cached across mode toggles so the ~4MB payload is pulled
// at most once per session (the browser also HTTP-caches it). Never bundled into the initial page.
let cache: ReferenceTiling[] | null = null;
let inflight: Promise<ReferenceTiling[]> | null = null;

export async function loadReferenceAtlas(): Promise<ReferenceTiling[]> {
	if (cache) return cache;
	if (inflight) return inflight;
	inflight = fetch("/reference-atlas.json")
		.then((res) => {
			if (!res.ok) throw new Error(`reference-atlas.json: HTTP ${res.status}`);
			return res.json() as Promise<ReferenceTiling[]>;
		})
		.then((data) => {
			cache = data;
			inflight = null;
			return data;
		})
		.catch((err) => {
			inflight = null;
			throw err;
		});
	return inflight;
}
