import type { TranslationalCellData } from "@/lib/utils/renderTiling";
import type { ParametricCellData } from "@/lib/utils/paramCell";
import type { CatalogueTiling } from "@/lib/services/catalogueService";
import type { ExactCellSource } from "@/lib/services/cellCodecService";

// The Reference (Oracle) shelf — a DISPLAY-ONLY atlas of known k-uniform tilings from the literature,
// deliberately kept OFF the certified-results catalogue (§0: the site never produces the claim; these
// are external oracles, not our search output). Generated by scripts/build-reference-atlas.ts into the
// static asset public/reference-atlas.json and lazy-fetched only when the shelf is opened.
//
//   - galebach: regular k=1..6 (Soto-Sánchez/Galebach), reconstructed geometry. No completeness proof.
//   - myers:    Myers star tilings (k=1 in-ring Fig-4 subclass today; k=2 pending the machine-readable
//               JSON). An unchecked hand enumeration — shown as reference, never as certified.
//   - ctrnact:  Marek Čtrnáct's k-uniform search, reproduced here (k=7 shown; k≤8 in figures/data/ctrnact.json).
//               An unproven exhaustive search extending Galebach beyond k=6 — reference, never certified.
//   - ctrnact-star: the Čtrnáct-engine star extension's full in-ring catalogs (feat/ctrnact-star),
//               k=1..2, star-bearing solutions only. Most reproduce Myers records; the ones flagged
//               candidate:true match NOTHING in Myers and are pending adversarial review.
export interface ReferenceTiling {
	id: string; // "t4001" (galebach) | "myers-k1-star-03" (myers) | "ctrnact-07_..." (ctrnact)
	source: "galebach" | "myers" | "ctrnact" | "ctrnact-star";
	k: number;
	family: string; // distinct polygon-type label, e.g. "3.4.6.12"; star tiles marked "n*"
	renderCell: TranslationalCellData; // float, parseBaseCell-ready
	alphaRange?: [number, number]; // degrees; present ⇒ one-parameter family with an alpha slider
	candidate?: boolean; // ctrnact-star only: not in Myers' enumeration — candidate new tiling
	preview?: boolean; // ctrnact-star only: from a PARTIAL (still-running) solve — incomplete, uncertified
	// Historical first-discoverer of this tiling (Kepler, Krötenheerdt, Chavey, Galebach, Čtrnáct,
	// Joseph Myers, Alessandro Longo). One attribute, orthogonal to certification.
	discoverer: string;
	// Rigorous completeness status of this tiling's enumeration level:
	//   proven      — this work's method has a completeness certificate (regular k≤3)
	//   reproduced  — count matches a published enumeration, not independently proven here
	//   candidate   — surfaced by this work; completeness / literature-novelty not established
	certification: "proven" | "reproduced" | "candidate";
	// Present on family entries: the proven parametric cell driving the /play alpha slider
	// (lib/utils/paramCell.ts). renderCell then holds the default-alpha evaluation (thumbnails).
	paramCell?: ParametricCellData;
	exactSource?: ExactCellSource; // exact cyclotomic cell for the symmetry overlay (added 2026-07)
}

export interface ReferenceFilter {
	kValues?: number[];
	discoverers?: string[]; // each entry's discoverer must be in this set
	certifications?: ReferenceTiling["certification"][]; // proven / reproduced / candidate
	polygonNames?: string[]; // each must appear in the tiling's family label
	query?: string; // free-text substring match on id or family (e.g. "4j5_5b2" or "3.6")
}

export function matchesReferenceFilters(t: ReferenceTiling, f: ReferenceFilter): boolean {
	if (f.kValues?.length && !f.kValues.includes(t.k)) return false;
	if (f.discoverers?.length && !f.discoverers.includes(t.discoverer)) return false;
	if (f.certifications?.length && !f.certifications.includes(t.certification)) return false;
	if (f.polygonNames?.length) {
		const fam = t.family.split(".").map((s) => s.trim());
		if (!f.polygonNames.every((n) => fam.includes(n))) return false;
	}
	if (f.query?.trim()) {
		const q = f.query.trim().toLowerCase();
		if (!t.id.toLowerCase().includes(q) && !t.family.toLowerCase().includes(q)) return false;
	}
	return true;
}

// Adapt a reference tiling to the CatalogueTiling shape so the /play viewer (Canvas + Sidebar, all
// keyed on canonicalKey) renders it unchanged. `id` stands in for canonicalKey; certified is always
// false (these are oracles, not our proven results) — the /play sidebar is told mode="reference" so it
// shows an "Oracle" pill instead of the misleading "Candidate" badge.
export function referenceToCatalogue(r: ReferenceTiling): CatalogueTiling {
	return {
		canonicalKey: r.id,
		k: r.k,
		family: r.family,
		renderCell: r.renderCell,
		certified: false,
		runIds: [],
		exactSource: r.exactSource,
		paramCell: r.paramCell,
	};
}

// Lazy client-side fetch of the static atlas. Cached across mode toggles so the ~4MB payload is pulled
// at most once per session (the browser also HTTP-caches it). Never bundled into the initial page.
let cache: ReferenceTiling[] | null = null;
let inflight: Promise<ReferenceTiling[]> | null = null;

export async function loadReferenceAtlas(): Promise<ReferenceTiling[]> {
	if (cache) return cache;
	if (inflight) return inflight;
	inflight = fetch("/reference-atlas.json")
		.then((res) => {
			if (!res.ok) throw new Error(`reference-atlas.json: HTTP ${res.status}`);
			return res.json() as Promise<ReferenceTiling[]>;
		})
		.then((data) => {
			cache = data;
			inflight = null;
			return data;
		})
		.catch((err) => {
			inflight = null;
			throw err;
		});
	return inflight;
}

// Per-k lazy shards for the higher-k Čtrnáct atlas (k≥8, generated by scripts/build-reference-atlas.ts
// into public/reference-atlas-k{k}.json). Fetched only when that k is selected in the shelf filter, so
// a heavy shard (k=10 ≈ tens of MB) never loads unless the user opens it. Cached per-k across the session.
const shardCache = new Map<number, ReferenceTiling[]>();
const shardInflight = new Map<number, Promise<ReferenceTiling[]>>();

export async function loadReferenceAtlasShard(k: number): Promise<ReferenceTiling[]> {
	const cached = shardCache.get(k);
	if (cached) return cached;
	const existing = shardInflight.get(k);
	if (existing) return existing;
	const p = fetch(`/reference-atlas-k${k}.json`)
		.then((res) => {
			if (!res.ok) throw new Error(`reference-atlas-k${k}.json: HTTP ${res.status}`);
			return res.json() as Promise<ReferenceTiling[]>;
		})
		.then((data) => {
			shardCache.set(k, data);
			shardInflight.delete(k);
			return data;
		})
		.catch((err) => {
			shardInflight.delete(k);
			throw err;
		});
	shardInflight.set(k, p);
	return p;
}
