import type { TranslationalCellData } from "@/lib/utils/renderTiling";
import type { ParametricCellData } from "@/lib/utils/paramCell";
import type { CatalogueTiling } from "@/lib/services/catalogueService";
import type { ExactCellSource } from "@/lib/services/cellCodecService";
import type { LatticeShape, WallpaperGroup } from "@/lib/classes/symmetry/types";

// The Reference (Oracle) shelf — a DISPLAY-ONLY atlas of known k-uniform tilings from the literature,
// deliberately kept OFF the certified-results catalogue (§0: the site never produces the claim; these
// are external oracles, not our search output). Generated by scripts/build-reference-atlas.ts into the
// static asset public/reference-atlas.json and lazy-fetched only when the shelf is opened.
//
//   - galebach: regular k=1..6 (Soto-Sánchez/Galebach), reconstructed geometry. No completeness proof.
//   - myers:    Myers star tilings (k=1 in-ring Fig-4 subclass today; k=2 pending the machine-readable
//               JSON). An unchecked hand enumeration — shown as reference, never as certified.
//   - ctrnact:  Marek Čtrnáct's k-uniform search, reproduced here (k=7 shown; k≤8 in figures/data/ctrnact.json).
//               An unproven exhaustive search extending Galebach beyond k=6 — reference, never certified.
//   - ctrnact-star: the Čtrnáct-engine star extension's full in-ring catalogs (feat/ctrnact-star),
//               k=1..2, star-bearing solutions only. Most reproduce Myers records; the ones flagged
//               candidate:true match NOTHING in Myers and are pending adversarial review.
//   - composable: source tag for the convex-irregular shelf (kept as historical provenance; the
//               user-facing class is "convex", see TileClass). Tilings using convex unit-edge super-tiles
//               (e.g. cx4-2.4.2.4) alongside the regular set (scripts/build-composable-atlas.ts → the
//               separate public/reference-atlas-composable.json). Distinct-tiling counts are EXACT
//               (proof-grade ℤ[ζ₂₄] congruence dedup, NOTES §55); enumeration completeness rests on the
//               engine, as for the regular family. These carry no certification / wallpaper classification.
export type Certification = "proven" | "reproduced" | "candidate";

export interface ReferenceTiling {
	id: string; // "t4001" (galebach) | "myers-k1-star-03" (myers) | "ctrnact-07_..." (ctrnact)
	source: "galebach" | "myers" | "ctrnact" | "ctrnact-star" | "composable" | "isotoxal" | "mixed" | "scaled" | "polyomino" | "islamic" | "hyperbolic" | "spherical";
	k: number;
	family: string; // distinct polygon-type label, e.g. "3.4.6.12"; star tiles marked "n*"
	renderCell: TranslationalCellData; // float, parseBaseCell-ready (a throwaway cell for hyperbolic entries — never drawn)
	// Hyperbolic shelf only: the Schläfli symbol {p,q} of a regular hyperbolic tiling. Kept as the card
	// label for the regular entries; routing now keys on `wythoff` (present on EVERY hyperbolic entry) or
	// geometry === "hyperbolic". Absent (and geometry "euclidean"/undefined) for every Euclidean tiling.
	schlafli?: [number, number];
	// Hyperbolic shelf only: the Wythoff descriptor (triangle group {p,q} + Coxeter–Dynkin rings). Regular
	// {p,q} = rings [true,false,false]; the uniform/Archimedean forms ring more mirrors. Drives the
	// Poincaré-disk renderer (lib/render/hyperbolic.ts uniformDescriptor). Present on all hyperbolic entries.
	wythoff?: { p: number; q: number; rings: [boolean, boolean, boolean]; snub?: boolean };
	// Spherical shelf only: the Schläfli symbol {p,q} of a Platonic solid rendered as a spherical tiling
	// (the finite, 1/p + 1/q > 1/2 end of the regular {p,q} family). Its presence — like wythoff for the
	// hyperbolic disk — routes /play + the thumbnails to the three.js sphere renderer
	// (components/spherical-canvas.tsx). Absent for every Euclidean and hyperbolic tiling.
	// `solid` (required) is the stable Polyhedron id the renderer routes on — Platonic AND Archimedean
	// solids resolve by it (Archimedean have no {p,q}). p/q are the Schläfli symbol, present for the
	// Platonic solids only (display).
	spherical?: { p?: number; q?: number; solid: string };
	geometry?: "euclidean" | "hyperbolic" | "spherical";
	alphaRange?: [number, number]; // degrees; present ⇒ one-parameter family with an alpha slider
	candidate?: boolean; // ctrnact-star only: not in Myers' enumeration — candidate new tiling
	preview?: boolean; // ctrnact-star only: from a PARTIAL (still-running) solve — incomplete, uncertified
	// Historical first-discoverer of this tiling (Kepler, Krötenheerdt, Chavey, Galebach, Čtrnáct,
	// Joseph Myers, Alessandro Longo). One attribute, orthogonal to certification.
	discoverer: string;
	// Rigorous completeness status of this tiling's enumeration level:
	//   proven      — this work's method has a completeness certificate (regular k≤3)
	//   reproduced  — count matches a published enumeration, not independently proven here
	//   candidate   — surfaced by this work; completeness / literature-novelty not established
	// Absent on the convex-irregular demo shelf — those tilings make no completeness claim, so they're
	// excluded from the certification facet rather than assigned a misleading status.
	certification?: Certification;
	// Convex-irregular shelf only: true iff every composite tile it uses dissects into regular pieces (the
	// decomposable palette); false iff it uses a non-decomposable composite. Absent on every other source.
	decomposableOnly?: boolean;
	// Polyomino shelf only: which polyomino ORDER this tiling's tiles belong to — the sub-class facet
	// (Tetrominoes now; Pentominoes etc. later). Absent on every other source.
	polyominoOrder?: "tetromino";
	// Islamic shelf only: which of Bonner's design systems the underlying tessellation belongs to — the
	// sub-class facet (see docs/ISLAMIC_TILINGS.md). Absent on every other source.
	islamicSystem?: IslamicSystem;
	// Isotoxal shelf only: true iff the tiling uses a convex isotoxal tile NOT expressible on ζ₁₂ (i.e. not
	// one of the 60/120 rhombus, 90/150 hexagon, 120/150 octagon the convex-irregular enumeration already reached)
	// — the genuinely new tilings the ζ₂₄ grid unlocks. Absent on every other source.
	offGrid?: boolean;
	note?: string; // free-text provenance caveat (convex-irregular demo: counts are illustrative, not all-and-only)
	// Present on family entries: the proven parametric cell driving the /play alpha slider
	// (lib/utils/paramCell.ts). renderCell then holds the default-alpha evaluation (thumbnails).
	paramCell?: ParametricCellData;
	exactSource?: ExactCellSource; // exact cyclotomic cell for the symmetry overlay (added 2026-07)

	// Vertex-type classification (build-computed, 2026-07). k counts vertex ORBITS; m counts DISTINCT
	// vertex configurations among them (m ≤ k). `partition` is the multiplicities of those distinct
	// configs, descending, summing to k — e.g. m=3, partition [5,1,1] is the "511" group at k=7.
	// Absent when a source has no per-orbit config data (never guessed; the tiling is then excluded from
	// M/partition filters). m === k is the Krötenheerdt (maximal) class.
	m?: number;
	partition?: number[];
	// Exact wallpaper symmetry — REGULAR tilings only (WallpaperSymmetry needs exact convex-tile
	// intersection; star tiles are non-convex ⇒ omitted, NOTES §9.4). Absent for every star tiling.
	wallpaperGroup?: WallpaperGroup;
	latticeShape?: LatticeShape;
}

// The star folds an atlas actually uses (the n of each n* token): 3,4,6,8,9,12,18. Used to seed the
// star-fold filter without re-deriving from the whole atlas.
export const STAR_FOLDS = [3, 4, 6, 8, 9, 12, 18] as const;

// Higher-k demo shards shipped as separate lazy files (the eager main atlas carries only k≤2 for these
// classes — build-{composable,isotoxal}-atlas MAIN_MAX_K=2). Both the /library shelf and the /play browse
// tree read these so their "known tiers" never drift. Keep in sync with those build scripts' cells.json
// inputs (a new k lands here once its shard is built).
export const COMPOSABLE_SHARD_KS = [3];
export const ISOTOXAL_SHARD_KS = [3, 4];

// tileClass, the primary shelf axis: "convex" (convex-irregular) iff the tiling comes from the convex
// unit-edge super-tile demo (source-driven — source "composable" — since it has no "*" token); else
// "star" iff its family carries a star token ("n*"); "regular" otherwise. Matches polygonClassLabel.
export type TileClass = "regular" | "star" | "convex" | "isotoxal" | "mixed" | "scaled" | "polyomino" | "islamic" | "hyperbolic" | "spherical";
// Bonner's design systems — the sub-facet axis for the Islamic class (docs/ISLAMIC_TILINGS.md). The
// underlying tessellation's tile kit, independent of the strap-pattern family (acute/median/obtuse).
export type IslamicSystem = "regular" | "fourfold-a" | "fourfold-b" | "fivefold" | "sevenfold" | "nonsystematic" | "dual-level";
// The ONE source-driven tile classifier, shared by /library and /play. Source wins when present;
// source-less rows (the Supabase certified catalogue) fall back to family-string tokens — which
// matches the legacy polygonClassLabel, so the two pages agree with or without a source.
export function tileClassOf(t: { family: string; source?: ReferenceTiling["source"] }): TileClass {
	if (t.source === "hyperbolic") return "hyperbolic";
	if (t.source === "spherical") return "spherical";
	if (t.source === "mixed") return "mixed";
	if (t.source === "isotoxal") return "isotoxal";
	if (t.source === "composable") return "convex";
	if (t.source === "scaled") return "scaled";
	if (t.source === "polyomino") return "polyomino";
	if (t.source === "islamic") return "islamic";
	if (t.family.includes("cx")) return "convex";
	if (t.family.includes("α")) return "isotoxal";
	return t.family.includes("*") ? "star" : "regular";
}

// Single source of truth for the tile-class axis, consumed by BOTH /library (filter chips) and /play
// (catalogue groups). To add a class: one entry here + one tileClassOf branch + one bestEffort fetch in
// loadReferenceAtlas — and it appears on both pages. No per-page class list to keep in sync.
export const TILE_CLASS_ORDER: TileClass[] = ["regular", "star", "convex", "isotoxal", "mixed", "scaled", "polyomino", "islamic", "hyperbolic", "spherical"];
export const TILE_CLASS_LABEL: Record<TileClass, { short: string; long: string }> = {
	regular: { short: "Regular", long: "Regular polygons" },
	star: { short: "Star", long: "Star polygons" },
	convex: { short: "Convex irregular", long: "Convex irregular polygons" },
	isotoxal: { short: "Isotoxal", long: "Isotoxal polygons" },
	mixed: { short: "Mixed", long: "Mixed polygons" },
	scaled: { short: "Scaled", long: "Scaled polygons (sides 1–3)" },
	polyomino: { short: "Polyominoes", long: "Polyominoes (Tetris pieces)" },
	islamic: { short: "Islamic", long: "Islamic geometric systems" },
	hyperbolic: { short: "Hyperbolic", long: "Hyperbolic {p,q} tilings (Poincaré disk)" },
	spherical: { short: "Spherical", long: "Spherical {p,q} tilings (Platonic solids)" },
};

// Scaled shelf only: the max side length (scale) a tiling uses, recovered from its family subscripts
// (₂/₃). Drives the sub-class facet — "Sides 1–2" (max 2, the former Doubled class) vs "Sides 1–3" (uses
// a side-3 tile). Null for every non-scaled tiling (so the facet excludes them, matching the M/partition
// exclude-the-unclassified ethos).
export function scaledMaxScaleOf(t: { family: string; source?: ReferenceTiling["source"] }): number | null {
	if (t.source !== "scaled") return null;
	let max = 1;
	for (const tok of t.family.split(".")) {
		const m = /^\d+([₁₂₃₄₅₆₇₈₉]+)$/.exec(tok);
		if (m) max = Math.max(max, +[...m[1]].map((c) => "₀₁₂₃₄₅₆₇₈₉".indexOf(c)).join(""));
	}
	return max;
}

// Polyomino shelf only: the polyomino ORDER a tiling belongs to (its sub-class facet). Read straight from
// the build-stamped field — null for every non-polyomino tiling (so the facet excludes them, matching the
// M/partition exclude-the-unclassified ethos). Only "tetromino" exists today; pentominoes etc. extend this.
export function polyominoOrderOf(t: Pick<ReferenceTiling, "source" | "polyominoOrder">): "tetromino" | null {
	if (t.source !== "polyomino") return null;
	return t.polyominoOrder ?? null;
}

// Islamic shelf sub-facet: which Bonner design system the tiling belongs to — the build-stamped field,
// null for every non-Islamic tiling (so the facet excludes them, matching the exclude-the-unclassified ethos).
export function islamicSystemOf(t: Pick<ReferenceTiling, "source" | "islamicSystem">): IslamicSystem | null {
	if (t.source !== "islamic") return null;
	return t.islamicSystem ?? null;
}

// The star folds present in a family (unique, ascending). "3.4*.6*" → [4,6]. Empty for regular.
export function starFoldsOf(t: Pick<ReferenceTiling, "family">): number[] {
	const folds = new Set<number>();
	for (const tok of t.family.split(".")) {
		if (tok.endsWith("*")) {
			const n = parseInt(tok, 10);
			if (Number.isFinite(n)) folds.add(n);
		}
	}
	return [...folds].sort((a, b) => a - b);
}

// A one-parameter (α-slider) family iff it carries an alphaRange. The rigid star tilings have none.
export function isParametric(t: Pick<ReferenceTiling, "alphaRange">): boolean {
	return Array.isArray(t.alphaRange);
}

// Isotoxal shelf only: how many INDEPENDENT free angles the family flexes on (its paramCell slider count
// P). 1 ⇒ a single isotoxal tile flexes (α-family); 2 ⇒ two isotoxal tiles flex on their own (α, β-family).
// Null for any non-isotoxal tiling, or an isotoxal record missing its parametric cell — those never match
// the Shape facet, matching the exclude-the-unclassified ethos used by the M/partition filters.
export function isotoxalParamCount(t: Pick<ReferenceTiling, "source" | "paramCell">): 1 | 2 | null {
	if (t.source !== "isotoxal") return null;
	const n = t.paramCell?.params?.length;
	return n === 1 || n === 2 ? n : null;
}

// Canonical partition key for display + filtering: digits joined ("511"), switching to a "."
// separator if any part reaches 10 so "10,1" never collides with "1,0,1". Null when unclassified.
export function partitionKeyOf(t: Pick<ReferenceTiling, "partition">): string | null {
	if (!t.partition?.length) return null;
	const sep = t.partition.some((p) => p >= 10) ? "." : "";
	return t.partition.join(sep);
}

// Krötenheerdt (maximal): every orbit has a distinct vertex config, i.e. m === k. False when unclassified.
export function isMaximal(t: Pick<ReferenceTiling, "m" | "k">): boolean {
	return t.m != null && t.m === t.k;
}

export interface ReferenceFilter {
	kValue?: number; // single vertex-orbit count; unset = every k
	tileClass?: TileClass; // regular polygons only / star-bearing only / composite-tile demo
	// Scaled shelf sub-class: "s12" keeps only tilings within sides {1,2} (the former Doubled class);
	// "s123" keeps only tilings that use a side-3 tile. Non-scaled tilings never match while this is active.
	scaledScaleSet?: "s12" | "s123";
	// Polyomino shelf sub-class: keep only tilings whose tiles are of this polyomino order ("tetromino" today).
	// Non-polyomino tilings never match while this is active.
	polyominoOrder?: "tetromino";
	// Islamic shelf sub-class: keep only tilings in this Bonner design system. Non-Islamic tilings never
	// match while this is active.
	islamicSystem?: IslamicSystem;
	// Convex-irregular shelf facet: keep only decomposable-family or only uses-non-decomposable tilings.
	// Any tiling outside that class (decomposableOnly undefined) is EXCLUDED while this is active.
	convexDecomp?: "decomposable" | "non-decomposable";
	mValue?: number; // single distinct-vertex-config count; unclassified tilings never match
	partitionKey?: string; // single partition key (e.g. "511"); unclassified tilings never match
	maximalOnly?: boolean; // Krötenheerdt: keep only m === k
	starFolds?: number[]; // keep tilings using at least one of these star folds
	parametric?: "rigid" | "family"; // rigid (no α) / one-parameter α-family
	isotoxalShape?: "alpha" | "alpha-beta"; // isotoxal only: 1 free angle (α) vs 2 independent (α, β)
	wallpaperGroups?: WallpaperGroup[]; // exact group; unclassified (all stars) never match
	latticeShapes?: LatticeShape[]; // exact lattice shape; unclassified (all stars) never match
	discoverers?: string[]; // each entry's discoverer must be in this set
	certifications?: Certification[]; // proven / reproduced / candidate
	polygonNames?: string[]; // each must appear in the tiling's family label
	query?: string; // free-text substring match on id or family (e.g. "4j5_5b2" or "3.6")
}

export function matchesReferenceFilters(t: ReferenceTiling, f: ReferenceFilter): boolean {
	if (f.kValue != null && t.k !== f.kValue) return false;
	if (f.tileClass && tileClassOf(t) !== f.tileClass) return false;
	if (f.scaledScaleSet) {
		const ms = scaledMaxScaleOf(t);
		if (ms == null) return false; // non-scaled tilings never match the scale-set facet
		if (f.scaledScaleSet === "s12" && ms > 2) return false;
		if (f.scaledScaleSet === "s123" && ms < 3) return false;
	}
	if (f.polyominoOrder) {
		if (polyominoOrderOf(t) !== f.polyominoOrder) return false; // non-polyomino tilings never match the order facet
	}
	if (f.islamicSystem) {
		if (islamicSystemOf(t) !== f.islamicSystem) return false; // non-Islamic tilings never match the system facet
	}
	if (f.convexDecomp) {
		if (t.decomposableOnly == null) return false; // tilings outside the convex-irregular class never match this facet
		if (f.convexDecomp === "decomposable" && !t.decomposableOnly) return false;
		if (f.convexDecomp === "non-decomposable" && t.decomposableOnly) return false;
	}
	// M/partition/maximal: an active filter EXCLUDES unclassified tilings rather than matching them —
	// completeness ethos, we never silently pass a tiling whose classification we don't have.
	if (f.mValue != null && t.m !== f.mValue) return false;
	if (f.partitionKey != null && partitionKeyOf(t) !== f.partitionKey) return false;
	if (f.maximalOnly && !isMaximal(t)) return false;
	if (f.starFolds?.length) {
		const folds = starFoldsOf(t);
		if (!f.starFolds.some((n) => folds.includes(n))) return false;
	}
	if (f.parametric) {
		const isFam = isParametric(t);
		if (f.parametric === "family" && !isFam) return false;
		if (f.parametric === "rigid" && isFam) return false;
	}
	if (f.isotoxalShape) {
		const p = isotoxalParamCount(t);
		if (f.isotoxalShape === "alpha" && p !== 1) return false;
		if (f.isotoxalShape === "alpha-beta" && p !== 2) return false;
	}
	if (f.wallpaperGroups?.length && (t.wallpaperGroup == null || !f.wallpaperGroups.includes(t.wallpaperGroup))) return false;
	if (f.latticeShapes?.length && (t.latticeShape == null || !f.latticeShapes.includes(t.latticeShape))) return false;
	if (f.discoverers?.length && !f.discoverers.includes(t.discoverer)) return false;
	if (f.certifications?.length && (t.certification == null || !f.certifications.includes(t.certification))) return false;
	if (f.polygonNames?.length) {
		const fam = t.family.split(".").map((s) => s.trim());
		if (!f.polygonNames.every((n) => fam.includes(n))) return false;
	}
	if (f.query?.trim()) {
		const q = f.query.trim().toLowerCase();
		if (!t.id.toLowerCase().includes(q) && !t.family.toLowerCase().includes(q)) return false;
	}
	return true;
}

// Adapt a reference tiling to the CatalogueTiling shape so the /play viewer (Canvas + Sidebar, all
// keyed on canonicalKey) renders it unchanged. `id` stands in for canonicalKey; certified is always
// false (these are oracles, not our proven results) — the /play sidebar is told mode="reference" so it
// shows an "Oracle" pill instead of the misleading "Candidate" badge.
export function referenceToCatalogue(r: ReferenceTiling): CatalogueTiling {
	return {
		canonicalKey: r.id,
		k: r.k,
		family: r.family,
		source: r.source,
		renderCell: r.renderCell,
		certified: false,
		runIds: [],
		exactSource: r.exactSource,
		paramCell: r.paramCell,
		schlafli: r.schlafli,
		wythoff: r.wythoff,
		spherical: r.spherical,
		geometry: r.geometry,
	};
}

// Lazy client-side fetch of the static atlas. Cached across mode toggles so the ~4MB payload is pulled
// at most once per session (the browser also HTTP-caches it). Never bundled into the initial page.
let cache: ReferenceTiling[] | null = null;
let inflight: Promise<ReferenceTiling[]> | null = null;

export async function loadReferenceAtlas(): Promise<ReferenceTiling[]> {
	if (cache) return cache;
	if (inflight) return inflight;
	// The base atlas is required; the convex-irregular + isotoxal demo shelves are best-effort — a missing/broken
	// reference-atlas-{composable,isotoxal}.json degrades to an empty merge, never breaks the library.
	const bestEffort = (url: string) =>
		fetch(url)
			.then((res) => (res.ok ? (res.json() as Promise<ReferenceTiling[]>) : []))
			.catch(() => [] as ReferenceTiling[]);
	inflight = Promise.all([
		fetch("/reference-atlas.json").then((res) => {
			if (!res.ok) throw new Error(`reference-atlas.json: HTTP ${res.status}`);
			return res.json() as Promise<ReferenceTiling[]>;
		}),
		bestEffort("/reference-atlas-composable.json"),
		bestEffort("/reference-atlas-isotoxal.json"),
		bestEffort("/reference-atlas-mixed.json"),
		bestEffort("/reference-atlas-scaled.json"),
		bestEffort("/reference-atlas-polyomino.json"),
		bestEffort("/reference-atlas-islamic.json"),
		bestEffort("/reference-atlas-hyperbolic.json"),
		bestEffort("/reference-atlas-spherical.json"),
	])
		.then(([base, composable, isotoxal, mixed, scaled, polyomino, islamic, hyperbolic, spherical]) => {
			const data = [...base, ...composable, ...isotoxal, ...mixed, ...scaled, ...polyomino, ...islamic, ...hyperbolic, ...spherical];
			cache = data;
			inflight = null;
			return data;
		})
		.catch((err) => {
			inflight = null;
			throw err;
		});
	return inflight;
}

// Per-k lazy shards for the higher-k Čtrnáct atlas (k≥8, generated by scripts/build-reference-atlas.ts
// into public/reference-atlas-k{k}.json). Fetched only when that k is selected in the shelf filter, so
// a heavy shard (k=10 ≈ 73 MB) never loads unless the user opens it. Cached per-k across the session.
// NOTE: these records carry no m/partition/wallpaper classification yet (the build ctrnact path doesn't
// compute it) — they filter by k/tileClass/discoverer/certification and render, but are excluded from
// the M/partition/wallpaper facets until the build stamps those fields.
const shardCache = new Map<number, ReferenceTiling[]>();
const shardInflight = new Map<number, Promise<ReferenceTiling[]>>();

export async function loadReferenceAtlasShard(k: number): Promise<ReferenceTiling[]> {
	const cached = shardCache.get(k);
	if (cached) return cached;
	const existing = shardInflight.get(k);
	if (existing) return existing;
	const p = fetch(`/reference-atlas-k${k}.json`)
		.then((res) => {
			if (!res.ok) throw new Error(`reference-atlas-k${k}.json: HTTP ${res.status}`);
			return res.json() as Promise<ReferenceTiling[]>;
		})
		.then((data) => {
			shardCache.set(k, data);
			shardInflight.delete(k);
			return data;
		})
		.catch((err) => {
			shardInflight.delete(k);
			throw err;
		});
	shardInflight.set(k, p);
	return p;
}

// Per-k lazy shards for the convex-irregular demo shelf (k≥3, generated by scripts/build-composable-atlas.ts
// into public/reference-atlas-composable-k{k}.json). The main reference-atlas-composable.json carries
// only k≤2; the higher-k entries — heaviest today is k=3, ~940 tilings and growing with the convex
// solve — load only when the convex-irregular class or a k≥3 chip is selected. Mirrors loadReferenceAtlasShard,
// but a MISSING shard degrades to an empty merge (HTTP 404 ⇒ []) rather than throwing: the convex-irregular
// shelf is a best-effort demo, never a hard dependency of the library. Cached per-k across the session.
const composableShardCache = new Map<number, ReferenceTiling[]>();
const composableShardInflight = new Map<number, Promise<ReferenceTiling[]>>();

export async function loadComposableAtlasShard(k: number): Promise<ReferenceTiling[]> {
	const cached = composableShardCache.get(k);
	if (cached) return cached;
	const existing = composableShardInflight.get(k);
	if (existing) return existing;
	const p = fetch(`/reference-atlas-composable-k${k}.json`)
		.then((res) => {
			if (res.status === 404) return [] as ReferenceTiling[]; // shard not built for this k — empty merge
			if (!res.ok) throw new Error(`reference-atlas-composable-k${k}.json: HTTP ${res.status}`);
			return res.json() as Promise<ReferenceTiling[]>;
		})
		.then((data) => {
			composableShardCache.set(k, data);
			composableShardInflight.delete(k);
			return data;
		})
		.catch((err) => {
			composableShardInflight.delete(k);
			throw err;
		});
	composableShardInflight.set(k, p);
	return p;
}

// Per-k lazy shards for the isotoxal α-family shelf (k≥3, generated by scripts/build-isotoxal-atlas.ts into
// public/reference-atlas-isotoxal-k{k}.json). The main reference-atlas-isotoxal.json carries only k≤2; k=3
// (~858 families with parametric cells, several MB) loads only when the isotoxal class or a k≥3 chip is
// selected. Same best-effort semantics as the convex-irregular shard: a missing shard (404) → empty merge.
const isotoxalShardCache = new Map<number, ReferenceTiling[]>();
const isotoxalShardInflight = new Map<number, Promise<ReferenceTiling[]>>();

export async function loadIsotoxalAtlasShard(k: number): Promise<ReferenceTiling[]> {
	const cached = isotoxalShardCache.get(k);
	if (cached) return cached;
	const existing = isotoxalShardInflight.get(k);
	if (existing) return existing;
	const p = fetch(`/reference-atlas-isotoxal-k${k}.json`)
		.then((res) => {
			if (res.status === 404) return [] as ReferenceTiling[];
			if (!res.ok) throw new Error(`reference-atlas-isotoxal-k${k}.json: HTTP ${res.status}`);
			return res.json() as Promise<ReferenceTiling[]>;
		})
		.then((data) => {
			isotoxalShardCache.set(k, data);
			isotoxalShardInflight.delete(k);
			return data;
		})
		.catch((err) => {
			isotoxalShardInflight.delete(k);
			throw err;
		});
	isotoxalShardInflight.set(k, p);
	return p;
}
