#!/usr/bin/env python3
"""Generate a COMPLETE in-ring palette for any even D, from the closure formula.

Same derivation the star24full palette was built from (star-closure-k3-2026-07-11.log T1),
generalized off D=24. Angle unit is 360/D degrees; a tile is in-ring iff every corner angle
is an integer number of units.

  regular n-gon: interior = 180 - 360/n deg = D/2 - D/n units; integer iff n | D, n >= 3
  isotoxal star n*a: point = a units, dent = D - D/n - a units;
      both integer iff n | D; proper star (reflex dent) iff dent > D/2
      <=> a < D/2 - D/n = interior(n) units, i.e. 1 <= a <= D/2 - D/n - 1

Emits every such tile, so the palette is complete for its ring BY CONSTRUCTION. Used to test
the star orders no shipped palette reaches (n = 7, 11, 13, 14, 16, 17, 19, 21, 22, 23), whose
emptiness the taxonomy audit asserts but never checked.

Usage: gen_ring_palette.py D [--out PATH] [--max-valence 12]
"""
import argparse
import json
import sys

# two-char famchars: regulars gA.., stars sA../uA../vA../wA.. — unique, filename-safe
ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"


def famchars(prefixes, count):
    out = []
    for p in prefixes:
        for c in ALPHA:
            out.append(p + c)
            if len(out) >= count:
                return out
    raise SystemExit(f"famchar pool exhausted ({count} needed)")


def build(D, max_valence=12):
    if D % 2:
        raise SystemExit(f"D must be even (got {D}); an odd D has no integer D/2 interior")
    ns = [n for n in range(3, D + 1) if D % n == 0]
    regs, stars = [], []
    for n in ns:
        interior_u = D // 2 - D // n          # interior angle in units
        if interior_u < 1:
            continue
        regs.append(n)
        for a in range(1, interior_u):        # dent reflex <=> a < interior_u
            stars.append((n, a))

    rc = famchars(["g"], len(regs))
    sc = famchars(["s", "u", "v", "w", "x"], len(stars))
    tiles = [{"kind": "regular", "n": n, "name": str(n), "famchar": c}
             for n, c in zip(regs, rc)]
    tiles += [{"kind": "star", "n": n, "alphaU": a, "name": f"{n}*{a}", "famchar": c}
              for (n, a), c in zip(stars, sc)]

    return {
        "name": f"ring{D}",
        "D": D,
        "pinnedLegacy": False,
        "maxValence": max_valence,
        "comment": (
            f"COMPLETE in-ring palette at D={D} (unit {360/D:g} deg), generated by "
            f"gen_ring_palette.py from the closure formula: regular n-gons with n | {D} "
            f"({', '.join(map(str, regs))}) plus every isotoxal star n*a with n | {D} and "
            f"1 <= a <= {D}/2 - {D}/n - 1 (reflex dent). {len(regs)} regular + {len(stars)} "
            f"star = {len(regs)+len(stars)} tiles; complete for this ring by construction. "
            f"maxValence {max_valence} = the proven per-orbit bound. Solve+prune only "
            f"(develop is zeta24-only)."
        ),
        "tiles": tiles,
    }, regs, stars


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("D", type=int)
    ap.add_argument("--out")
    ap.add_argument("--max-valence", type=int, default=12)
    a = ap.parse_args()
    spec, regs, stars = build(a.D, a.max_valence)
    out = a.out or f"alphabets/palettes/ring{a.D}.json"
    with open(out, "w") as f:
        json.dump(spec, f, indent=2)
        f.write("\n")
    print(f"D={a.D}  regular {regs}  stars {len(stars)}  total {len(spec['tiles'])} tiles -> {out}")


if __name__ == "__main__":
    main()
