// Face analysis for freedraw patterns. Answers the question Marek raised and did not have a method
// for: "it only needs some sort of automatic detection of whether it contains infinite tiles or not".
//
// The method. Faces (tiles) are the connected components of the grid CELLS under "adjacent and the
// shared edge is not drawn". Working on the torus R^2/L makes the component count finite, but it
// destroys the distinction we care about: a finite polyomino and an infinite strip can both be one
// torus component. So the flood fill also carries each cell's LIFT into Z^2. Reaching an already
// visited coset by a second route with a different lift yields a nonzero lattice vector that maps the
// face to itself. The rank of the span of those vectors classifies the tile:
//
//   rank 0 — finite. The face is a polyomino; distinct lifts are distinct tiles.
//   rank 1 — a strip, infinite along one primitive direction.
//   rank 2 — unbounded in two directions (the whole plane for the empty pattern, or a connected
//            "sheet" riddled with periodic holes, e.g. one drawn square per 2x2 block).
//
// For rank-0 faces the Euler characteristic of the closed polyomino gives the hole count directly,
// which is the other thing Marek wanted ("polyominoes with holes would be easily accessible here").

import { type FreedrawPattern, coset, cosetCount, drawnEast, drawnNorth } from "./pattern";

export interface FaceInfo {
	/** Index into FaceAnalysis.faces; also the value stored in cellFace. */
	id: number;
	/** Dimension of the span of the face's period vectors: 0 finite, 1 strip, 2 unbounded. */
	rank: 0 | 1 | 2;
	/** Cells of the face per fundamental domain. For rank 0 this is the polyomino's area. */
	cells: number;
	/** Holes in the closed polyomino (1 - Euler characteristic). Always 0 when rank > 0. */
	holes: number;
	/** Primitive period vector for rank 1; null otherwise. The strip's direction. */
	period: [number, number] | null;
	/** One lifted cell per lattice coset of the face. With `periods`, a complete description — see below. */
	lifts: [number, number][];
	/** The lift mismatches the flood fill met. They generate the face's period subgroup P. */
	periods: [number, number][];
}

export interface FaceAnalysis {
	faces: FaceInfo[];
	/** Face id per lattice coset, so a renderer can colour any cell by one lookup. */
	cellFace: Int32Array;
}

const gcd2 = (a: number, b: number): number => {
	a = Math.abs(a);
	b = Math.abs(b);
	while (b) [a, b] = [b, a % b];
	return a;
};

/** Rank of the Q-span of a set of integer 2-vectors. Rational rank is enough to classify a face. */
function spanRank(vs: [number, number][]): 0 | 1 | 2 {
	let first: [number, number] | null = null;
	for (const w of vs) {
		if (w[0] === 0 && w[1] === 0) continue;
		if (!first) {
			first = w;
			continue;
		}
		if (first[0] * w[1] - first[1] * w[0] !== 0) return 2;
	}
	return first ? 1 : 0;
}

/** Generator of a rank-1 subgroup of Z^2 given vectors known to be pairwise parallel. */
function rank1Generator(vs: [number, number][]): [number, number] {
	const nz = vs.filter((w) => w[0] !== 0 || w[1] !== 0);
	const u = nz[0];
	const g = gcd2(u[0], u[1]);
	const prim: [number, number] = [u[0] / g, u[1] / g];
	// Every vector is an integer multiple of prim; the subgroup is generated by gcd(multiples) * prim.
	let m = 0;
	for (const w of nz) m = gcd2(m, prim[0] !== 0 ? w[0] / prim[0] : w[1] / prim[1]);
	const gen: [number, number] = [prim[0] * m, prim[1] * m];
	// Normalise the sign so the direction is deterministic across runs.
	if (gen[0] < 0 || (gen[0] === 0 && gen[1] < 0)) return [-gen[0], -gen[1]];
	return gen;
}

/** Holes in a connected polyomino given its cells' lower-left corners: 1 - (V - E + F). */
function holeCount(cells: [number, number][]): number {
	const verts = new Set<string>();
	const edges = new Set<string>();
	for (const [x, y] of cells) {
		verts.add(`${x},${y}`);
		verts.add(`${x + 1},${y}`);
		verts.add(`${x},${y + 1}`);
		verts.add(`${x + 1},${y + 1}`);
		edges.add(`h${x},${y}`);
		edges.add(`h${x},${y + 1}`);
		edges.add(`v${x},${y}`);
		edges.add(`v${x + 1},${y}`);
	}
	return 1 - (verts.size - edges.size + cells.length);
}

/**
 * Classify every face of a pattern. O(n) in the number of lattice cosets, so it is cheap enough to
 * run on load for a whole catalogue page rather than being baked into the data file.
 */
export function analyseFaces(p: FreedrawPattern): FaceAnalysis {
	const n = cosetCount(p);
	const cellFace = new Int32Array(n).fill(-1);
	const faces: FaceInfo[] = [];
	// Absolute lift of each visited coset, as a flat [x, y] pair store.
	const liftX = new Int32Array(n);
	const liftY = new Int32Array(n);

	for (let start = 0; start < n; start++) {
		if (cellFace[start] !== -1) continue;
		const id = faces.length;
		const sx = start % p.a;
		const sy = Math.floor(start / p.a);
		cellFace[start] = id;
		liftX[start] = sx;
		liftY[start] = sy;

		const periods: [number, number][] = [];
		const lifted: [number, number][] = [[sx, sy]];
		const queue: number[] = [start];
		for (let qi = 0; qi < queue.length; qi++) {
			const c = queue[qi];
			const x = liftX[c];
			const y = liftY[c];
			// Neighbour cell, and the drawn edge that would block the step.
			const steps: [number, number, boolean][] = [
				[x + 1, y, drawnNorth(p, x + 1, y)],
				[x - 1, y, drawnNorth(p, x, y)],
				[x, y + 1, drawnEast(p, x, y + 1)],
				[x, y - 1, drawnEast(p, x, y)],
			];
			for (const [nx, ny, blocked] of steps) {
				if (blocked) continue;
				const nc = coset(p, nx, ny);
				if (cellFace[nc] === -1) {
					cellFace[nc] = id;
					liftX[nc] = nx;
					liftY[nc] = ny;
					lifted.push([nx, ny]);
					queue.push(nc);
				} else {
					// Second route to a known cell. The lift mismatch is a period of this face.
					const dx = nx - liftX[nc];
					const dy = ny - liftY[nc];
					if (dx !== 0 || dy !== 0) periods.push([dx, dy]);
				}
			}
		}

		const rank = spanRank(periods);
		faces.push({
			id,
			rank,
			cells: lifted.length,
			holes: rank === 0 ? holeCount(lifted) : 0,
			period: rank === 1 ? rank1Generator(periods) : null,
			lifts: lifted,
			periods,
		});
	}

	return { faces, cellFace };
}

// ── shape classification ──────────────────────────────────────────────────────────────────────────
// Four ways to say two faces are "the same", each a refinement of the one before:
//
//   kind   rank alone — finite / strip / unbounded. 3 buckets, whatever the pattern.
//   shape  congruent: equal after a translation and one of the 8 symmetries of the grid. A 1x3 and a
//          3x1 are one shape; mirror pairs merge, matching the atlas's chirality convention.
//   pose   equal after a translation alone. 1x3 and 3x1 part company; every 3x1 in the figure stays
//          one colour no matter where it sits.
//   orbit  equal after a translation BY THE PERIOD LATTICE. This is what the fill has always drawn.
//
// The awkward part is that a strip or an unbounded sheet has no polyomino to compare. It does have a
// shape, though, and the flood fill has already computed everything needed to name it. The pattern is
// L-periodic, so L permutes the faces; if a cell c and c + l both lie in F then F and F + l share a
// cell, and two faces that share a cell are equal, so l stabilises F. Hence distinct cells of F sit in
// distinct L-cosets unless they differ by a period, which is exactly the statement
//
//     F = P + T,   P the face's period subgroup, T the fill's one-lift-per-coset transversal.
//
// So (P, T mod P) names F completely, at every rank, and comparing faces is comparing that pair up to
// the group in question. No rank-0 special case, no bounded-window approximation.

/** Extended gcd, normalised to g >= 0: returns g with a*x + b*y = g. */
function egcd(x: number, y: number): { g: number; a: number; b: number } {
	let [r0, r1] = [x, y];
	let [a0, a1] = [1, 0];
	let [b0, b1] = [0, 1];
	while (r1 !== 0) {
		const q = Math.trunc(r0 / r1);
		[r0, r1] = [r1, r0 - q * r1];
		[a0, a1] = [a1, a0 - q * a1];
		[b0, b1] = [b1, b0 - q * b1];
	}
	return r0 < 0 ? { g: -r0, a: -a0, b: -b0 } : { g: r0, a: a0, b: b0 };
}

/** Hermite normal form of a RANK-2 subgroup of Z^2: generated by (p, 0) and (q, s), p, s > 0, 0 <= q < p. */
function hnf2(vs: [number, number][]): { p: number; q: number; s: number } {
	let q = 0;
	let s = 0;
	const flat: number[] = []; // subgroup members whose second component is already 0
	for (const [x, y] of vs) {
		if (y === 0) {
			if (x !== 0) flat.push(x);
			continue;
		}
		if (s === 0) {
			[q, s] = y > 0 ? [x, y] : [-x, -y];
			continue;
		}
		// Replace the pair by one vector at the gcd of their heights, and bank the two leftovers, which
		// are combinations with height 0.
		const { g, a, b } = egcd(s, y);
		const nq = a * q + b * x;
		flat.push(q - (s / g) * nq, x - (y / g) * nq);
		q = nq;
		s = g;
	}
	let p = 0;
	for (const x of flat) p = gcd2(p, x);
	return { p, q: p > 0 ? ((q % p) + p) % p : q, s };
}

/**
 * A fold of the plane onto one representative per coset of the face's period subgroup P, plus a tag
 * naming P itself. Two faces are comparable only through the same fold, which is why everything here
 * is derived from P alone and never from the arbitrary lifts the flood fill happened to pick.
 */
function quotient(f: FaceInfo): { tag: string; fold: (x: number, y: number) => string } {
	if (f.rank === 0) return { tag: "0", fold: (x, y) => `${x}.${y}` };
	if (f.rank === 1) {
		const g = rank1Generator(f.periods);
		const m = gcd2(g[0], g[1]);
		const u: [number, number] = [g[0] / m, g[1] / m]; // primitive direction of the strip
		// Complete u to a basis (u, w) of Z^2 with determinant 1 — a deterministic function of u, so two
		// strips with the same generator get the same coordinates. In that basis P is generated by (m, 0),
		// so the first coordinate mod m and the second coordinate name the coset.
		const { a, b } = egcd(u[0], u[1]); // a*ux + b*uy = 1
		return {
			tag: `1.${g[0]},${g[1]}`,
			fold: (x, y) => `${(((x * a + y * b) % m) + m) % m}.${y * u[0] - x * u[1]}`,
		};
	}
	const { p, q, s } = hnf2(f.periods);
	return {
		tag: `2.${p},${q},${s}`,
		fold: (x, y) => {
			const j = ((y % s) + s) % s;
			return `${((((x - ((y - j) / s) * q) % p) + p) % p)}.${j}`;
		},
	};
}

/**
 * Canonical name of a face up to TRANSLATION. Minimising over "slide lift e onto the origin" is a
 * complete canonical form: any translation identifying two faces carries some cell of one onto a cell
 * of the other, so the winning candidate is always among these |T| — no need to walk all of Z^2/P,
 * which for an unbounded face is det(L) times larger than the face's own transversal.
 */
function poseKey(f: FaceInfo): string {
	const { tag, fold } = quotient(f);
	let best: string | null = null;
	for (const [ex, ey] of f.lifts) {
		const key = `${tag}|${f.lifts.map(([x, y]) => fold(x - ex, y - ey)).sort().join(" ")}`;
		if (best === null || key < best) best = key;
	}
	return best ?? tag;
}

/** The 8 symmetries of the square grid, as (x, y) -> (ax + by, cx + dy). */
const D4: [number, number, number, number][] = [
	[1, 0, 0, 1],
	[0, -1, 1, 0],
	[-1, 0, 0, -1],
	[0, 1, -1, 0],
	[1, 0, 0, -1],
	[-1, 0, 0, 1],
	[0, 1, 1, 0],
	[0, -1, -1, 0],
];

/** Canonical name of a face up to translation AND the grid symmetries: its congruence class. */
function shapeKey(f: FaceInfo): string {
	let best: string | null = null;
	for (const [a, b, c, d] of D4) {
		const move = ([x, y]: [number, number]): [number, number] => [a * x + b * y, c * x + d * y];
		const key = poseKey({ ...f, lifts: f.lifts.map(move), periods: f.periods.map(move) });
		if (best === null || key < best) best = key;
	}
	return best as string;
}

export interface FaceClasses {
	/** Class index per face id, merging faces equal up to translation. */
	pose: number[];
	/** Class index per face id, merging faces congruent under translation + the grid symmetries. */
	shape: number[];
	poseCount: number;
	shapeCount: number;
}

// Keyed on the analysis object, which every caller already memoises per pattern, so the classification
// runs once even though the renderer asks for it on every frame.
const classCache = new WeakMap<FaceAnalysis, FaceClasses>();

/**
 * Group the faces by shape and by pose. Class indices are assigned in face order, so face 0 keeps
 * colour 0 in all three of shape / pose / orbit and toggling between them reads as a split, not a
 * reshuffle. Costs a few hundred string comparisons per face; only ever called for those two fills.
 */
export function classifyFaces(a: FaceAnalysis): FaceClasses {
	const hit = classCache.get(a);
	if (hit) return hit;
	const index = (keys: string[]): number[] => {
		const seen = new Map<string, number>();
		return keys.map((k) => {
			const at = seen.get(k);
			if (at !== undefined) return at;
			seen.set(k, seen.size);
			return seen.size - 1;
		});
	};
	const pose = index(a.faces.map(poseKey));
	const shape = index(a.faces.map(shapeKey));
	const out: FaceClasses = {
		pose,
		shape,
		poseCount: new Set(pose).size,
		shapeCount: new Set(shape).size,
	};
	classCache.set(a, out);
	return out;
}

/** Human-readable tile kind for the UI and for catalogue filters. */
export const rankLabel = (rank: 0 | 1 | 2) =>
	rank === 0 ? "polyomino" : rank === 1 ? "strip" : "unbounded";

/** Summary used as a sort/filter key over the catalogue. */
export function summarise(a: FaceAnalysis) {
	let finite = 0;
	let strips = 0;
	let unbounded = 0;
	let withHoles = 0;
	for (const f of a.faces) {
		if (f.rank === 0) finite++;
		else if (f.rank === 1) strips++;
		else unbounded++;
		if (f.holes > 0) withHoles++;
	}
	return { faceOrbits: a.faces.length, finite, strips, unbounded, withHoles };
}
