// Face analysis for freedraw patterns. Answers the question Marek raised and did not have a method
// for: "it only needs some sort of automatic detection of whether it contains infinite tiles or not".
//
// The method. Faces (tiles) are the connected components of the grid CELLS under "adjacent and the
// shared edge is not drawn". Working on the torus R^2/L makes the component count finite, but it
// destroys the distinction we care about: a finite polyomino and an infinite strip can both be one
// torus component. So the flood fill also carries each cell's LIFT into Z^2. Reaching an already
// visited coset by a second route with a different lift yields a nonzero lattice vector that maps the
// face to itself. The rank of the span of those vectors classifies the tile:
//
//   rank 0 — finite. The face is a polyomino; distinct lifts are distinct tiles.
//   rank 1 — a strip, infinite along one primitive direction.
//   rank 2 — unbounded in two directions (the whole plane for the empty pattern, or a connected
//            "sheet" riddled with periodic holes, e.g. one drawn square per 2x2 block).
//
// For rank-0 faces the Euler characteristic of the closed polyomino gives the hole count directly,
// which is the other thing Marek wanted ("polyominoes with holes would be easily accessible here").

import {
	type FreedrawGrid,
	type FreedrawPatch,
	type FreedrawPattern,
	coset,
	cosetCount,
	drawnDiag,
	drawnEast,
	drawnNorth,
	gridOf,
} from "./pattern";

export interface FaceInfo {
	/** Index into FaceAnalysis.faces; also the value stored in cellFace. */
	id: number;
	/** Dimension of the span of the face's period vectors: 0 finite, 1 strip, 2 unbounded. */
	rank: 0 | 1 | 2;
	/** Cells of the face per fundamental domain. For rank 0 this is the polyomino's area. */
	cells: number;
	/** Holes in the closed polyomino/polyiamond (1 - Euler characteristic). Always 0 when rank > 0. */
	holes: number;
	/** Primitive period vector for rank 1; null otherwise. The strip's direction, in lattice coords. */
	period: [number, number] | null;
	/**
	 * One lifted cell per lattice coset of the face. With `periods`, a complete description — see below.
	 * Square: the cell's lower-left corner. Triangle: the cell's TRIPLED CENTROID — an up triangle at
	 * (x, y) is stored as (3x+1, 3y+1) and a down one as (3x+2, 3y+2). That turns the mixed cell set
	 * into plain Z² points on which the grid's point group acts LINEARLY, so the pose/shape machinery
	 * below runs identically on both grids; only the symmetry table differs.
	 */
	lifts: [number, number][];
	/** The lift mismatches the flood fill met (same encoding as lifts). They generate the period subgroup P. */
	periods: [number, number][];
}

export interface FaceAnalysis {
	grid: FreedrawGrid;
	faces: FaceInfo[];
	/**
	 * Face id per cell, for renderer lookup. Square: one entry per lattice coset. Triangle: two per
	 * coset — [2c] the up triangle, [2c+1] the down triangle.
	 */
	cellFace: Int32Array;
}

const gcd2 = (a: number, b: number): number => {
	a = Math.abs(a);
	b = Math.abs(b);
	while (b) [a, b] = [b, a % b];
	return a;
};

/** Rank of the Q-span of a set of integer 2-vectors. Rational rank is enough to classify a face. */
function spanRank(vs: [number, number][]): 0 | 1 | 2 {
	let first: [number, number] | null = null;
	for (const w of vs) {
		if (w[0] === 0 && w[1] === 0) continue;
		if (!first) {
			first = w;
			continue;
		}
		if (first[0] * w[1] - first[1] * w[0] !== 0) return 2;
	}
	return first ? 1 : 0;
}

/** Generator of a rank-1 subgroup of Z^2 given vectors known to be pairwise parallel. */
function rank1Generator(vs: [number, number][]): [number, number] {
	const nz = vs.filter((w) => w[0] !== 0 || w[1] !== 0);
	const u = nz[0];
	const g = gcd2(u[0], u[1]);
	const prim: [number, number] = [u[0] / g, u[1] / g];
	// Every vector is an integer multiple of prim; the subgroup is generated by gcd(multiples) * prim.
	let m = 0;
	for (const w of nz) m = gcd2(m, prim[0] !== 0 ? w[0] / prim[0] : w[1] / prim[1]);
	const gen: [number, number] = [prim[0] * m, prim[1] * m];
	// Normalise the sign so the direction is deterministic across runs.
	if (gen[0] < 0 || (gen[0] === 0 && gen[1] < 0)) return [-gen[0], -gen[1]];
	return gen;
}

/** Holes in a connected polyomino given its cells' lower-left corners: 1 - (V - E + F). */
function holeCount(cells: [number, number][]): number {
	const verts = new Set<string>();
	const edges = new Set<string>();
	for (const [x, y] of cells) {
		verts.add(`${x},${y}`);
		verts.add(`${x + 1},${y}`);
		verts.add(`${x},${y + 1}`);
		verts.add(`${x + 1},${y + 1}`);
		edges.add(`h${x},${y}`);
		edges.add(`h${x},${y + 1}`);
		edges.add(`v${x},${y}`);
		edges.add(`v${x + 1},${y}`);
	}
	return 1 - (verts.size - edges.size + cells.length);
}

/**
 * Classify every face of a pattern. O(n) in the number of lattice cosets, so it is cheap enough to
 * run on load for a whole catalogue page rather than being baked into the data file.
 */
export function analyseFaces(p: FreedrawPattern): FaceAnalysis {
	if (p.patch) return analysePatch(p);
	return gridOf(p) === "triangle" ? analyseTriangle(p) : analyseSquare(p);
}

/**
 * Combined-grid records carry their face classification pre-baked (the developer computed the same
 * holonomy ranks offline, since there is no fixed lattice to flood here). Synthesize the analysis
 * from it so every consumer of summarise()/rankLabel() works unchanged. lifts/periods stay empty:
 * shape/pose classification is undefined for patches and the renderer falls back to orbit colours.
 */
function analysePatch(p: FreedrawPattern): FaceAnalysis {
	const patch = p.patch!;
	const faces: FaceInfo[] = patch.compRank.map((rank, i) => ({
		id: i,
		rank,
		cells: patch.compCells[i],
		holes: patch.compHoles[i],
		period: null,
		lifts: [],
		periods: [],
	}));
	return { grid: "ts", faces, cellFace: new Int32Array(0) };
}

function analyseSquare(p: FreedrawPattern): FaceAnalysis {
	const n = cosetCount(p);
	const cellFace = new Int32Array(n).fill(-1);
	const faces: FaceInfo[] = [];
	// Absolute lift of each visited coset, as a flat [x, y] pair store.
	const liftX = new Int32Array(n);
	const liftY = new Int32Array(n);

	for (let start = 0; start < n; start++) {
		if (cellFace[start] !== -1) continue;
		const id = faces.length;
		const sx = start % p.a;
		const sy = Math.floor(start / p.a);
		cellFace[start] = id;
		liftX[start] = sx;
		liftY[start] = sy;

		const periods: [number, number][] = [];
		const lifted: [number, number][] = [[sx, sy]];
		const queue: number[] = [start];
		for (let qi = 0; qi < queue.length; qi++) {
			const c = queue[qi];
			const x = liftX[c];
			const y = liftY[c];
			// Neighbour cell, and the drawn edge that would block the step.
			const steps: [number, number, boolean][] = [
				[x + 1, y, drawnNorth(p, x + 1, y)],
				[x - 1, y, drawnNorth(p, x, y)],
				[x, y + 1, drawnEast(p, x, y + 1)],
				[x, y - 1, drawnEast(p, x, y)],
			];
			for (const [nx, ny, blocked] of steps) {
				if (blocked) continue;
				const nc = coset(p, nx, ny);
				if (cellFace[nc] === -1) {
					cellFace[nc] = id;
					liftX[nc] = nx;
					liftY[nc] = ny;
					lifted.push([nx, ny]);
					queue.push(nc);
				} else {
					// Second route to a known cell. The lift mismatch is a period of this face.
					const dx = nx - liftX[nc];
					const dy = ny - liftY[nc];
					if (dx !== 0 || dy !== 0) periods.push([dx, dy]);
				}
			}
		}

		const rank = spanRank(periods);
		faces.push({
			id,
			rank,
			cells: lifted.length,
			holes: rank === 0 ? holeCount(lifted) : 0,
			period: rank === 1 ? rank1Generator(periods) : null,
			lifts: lifted,
			periods,
		});
	}

	return { grid: "square", faces, cellFace };
}

// Triangle-cell adjacency (see pattern.ts for the U/D geometry): each neighbour step names the raw
// target cell and the drawn edge that would block it. U(x,y) meets D(x,y-1) across h(x,y),
// D(x-1,y) across v(x,y), and its rhombus partner D(x,y) across the shared diagonal w at (x,y+1);
// D(x,y) mirrors those from the other side.
function analyseTriangle(p: FreedrawPattern): FaceAnalysis {
	const n = cosetCount(p);
	const cellFace = new Int32Array(2 * n).fill(-1);
	const faces: FaceInfo[] = [];
	const liftX = new Int32Array(2 * n);
	const liftY = new Int32Array(2 * n);
	const enc = (x: number, y: number, t: number): [number, number] => [3 * x + 1 + t, 3 * y + 1 + t];

	for (let start = 0; start < 2 * n; start++) {
		if (cellFace[start] !== -1) continue;
		const id = faces.length;
		const sc = start >> 1;
		const st = start & 1;
		const sx = sc % p.a;
		const sy = Math.floor(sc / p.a);
		cellFace[start] = id;
		liftX[start] = sx;
		liftY[start] = sy;

		const periods: [number, number][] = [];
		const lifted: [number, number][] = [enc(sx, sy, st)];
		const queue: number[] = [start];
		for (let qi = 0; qi < queue.length; qi++) {
			const cell = queue[qi];
			const t = cell & 1;
			const x = liftX[cell];
			const y = liftY[cell];
			const steps: [number, number, number, boolean][] =
				t === 0
					? [
							[x, y - 1, 1, drawnEast(p, x, y)],
							[x - 1, y, 1, drawnNorth(p, x, y)],
							[x, y, 1, drawnDiag(p, x, y + 1)],
						]
					: [
							[x, y + 1, 0, drawnEast(p, x, y + 1)],
							[x + 1, y, 0, drawnNorth(p, x + 1, y)],
							[x, y, 0, drawnDiag(p, x, y + 1)],
						];
			for (const [nx, ny, nt, blocked] of steps) {
				if (blocked) continue;
				const ncell = 2 * coset(p, nx, ny) + nt;
				if (cellFace[ncell] === -1) {
					cellFace[ncell] = id;
					liftX[ncell] = nx;
					liftY[ncell] = ny;
					lifted.push(enc(nx, ny, nt));
					queue.push(ncell);
				} else {
					const dx = nx - liftX[ncell];
					const dy = ny - liftY[ncell];
					if (dx !== 0 || dy !== 0) periods.push([3 * dx, 3 * dy]);
				}
			}
		}

		const rank = spanRank(periods);
		let period: [number, number] | null = null;
		if (rank === 1) {
			// Periods are stored tripled (the lifts' encoding); report the true lattice vector.
			const g = rank1Generator(periods);
			period = [g[0] / 3, g[1] / 3];
		}
		faces.push({
			id,
			rank,
			cells: lifted.length,
			holes: rank === 0 ? holeCountTriangle(lifted) : 0,
			period,
			lifts: lifted,
			periods,
		});
	}

	return { grid: "triangle", faces, cellFace };
}

/** Holes in a connected polyiamond: 1 - (V - E + F) over its decoded triangles. */
function holeCountTriangle(encCells: [number, number][]): number {
	const verts = new Set<string>();
	const edges = new Set<string>();
	for (const [ex, ey] of encCells) {
		const t = ((ex % 3) + 3) % 3 === 1 ? 0 : 1;
		const x = (ex - 1 - t) / 3;
		const y = (ey - 1 - t) / 3;
		if (t === 0) {
			verts.add(`${x},${y}`);
			verts.add(`${x + 1},${y}`);
			verts.add(`${x},${y + 1}`);
			edges.add(`h${x},${y}`);
			edges.add(`v${x},${y}`);
			edges.add(`w${x},${y + 1}`);
		} else {
			verts.add(`${x + 1},${y}`);
			verts.add(`${x},${y + 1}`);
			verts.add(`${x + 1},${y + 1}`);
			edges.add(`v${x + 1},${y}`);
			edges.add(`h${x},${y + 1}`);
			edges.add(`w${x},${y + 1}`);
		}
	}
	return 1 - (verts.size - edges.size + encCells.length);
}

// ── shape classification ──────────────────────────────────────────────────────────────────────────
// Four ways to say two faces are "the same", each a refinement of the one before:
//
//   kind   rank alone — finite / strip / unbounded. 3 buckets, whatever the pattern.
//   shape  congruent: equal after a translation and one of the 8 symmetries of the grid. A 1x3 and a
//          3x1 are one shape; mirror pairs merge, matching the atlas's chirality convention.
//   pose   equal after a translation alone. 1x3 and 3x1 part company; every 3x1 in the figure stays
//          one colour no matter where it sits.
//   orbit  equal after a translation BY THE PERIOD LATTICE. This is what the fill has always drawn.
//
// The awkward part is that a strip or an unbounded sheet has no polyomino to compare. It does have a
// shape, though, and the flood fill has already computed everything needed to name it. The pattern is
// L-periodic, so L permutes the faces; if a cell c and c + l both lie in F then F and F + l share a
// cell, and two faces that share a cell are equal, so l stabilises F. Hence distinct cells of F sit in
// distinct L-cosets unless they differ by a period, which is exactly the statement
//
//     F = P + T,   P the face's period subgroup, T the fill's one-lift-per-coset transversal.
//
// So (P, T mod P) names F completely, at every rank, and comparing faces is comparing that pair up to
// the group in question. No rank-0 special case, no bounded-window approximation.

/** Extended gcd, normalised to g >= 0: returns g with a*x + b*y = g. */
function egcd(x: number, y: number): { g: number; a: number; b: number } {
	let [r0, r1] = [x, y];
	let [a0, a1] = [1, 0];
	let [b0, b1] = [0, 1];
	while (r1 !== 0) {
		const q = Math.trunc(r0 / r1);
		[r0, r1] = [r1, r0 - q * r1];
		[a0, a1] = [a1, a0 - q * a1];
		[b0, b1] = [b1, b0 - q * b1];
	}
	return r0 < 0 ? { g: -r0, a: -a0, b: -b0 } : { g: r0, a: a0, b: b0 };
}

/** Hermite normal form of a RANK-2 subgroup of Z^2: generated by (p, 0) and (q, s), p, s > 0, 0 <= q < p. */
function hnf2(vs: [number, number][]): { p: number; q: number; s: number } {
	let q = 0;
	let s = 0;
	const flat: number[] = []; // subgroup members whose second component is already 0
	for (const [x, y] of vs) {
		if (y === 0) {
			if (x !== 0) flat.push(x);
			continue;
		}
		if (s === 0) {
			[q, s] = y > 0 ? [x, y] : [-x, -y];
			continue;
		}
		// Replace the pair by one vector at the gcd of their heights, and bank the two leftovers, which
		// are combinations with height 0.
		const { g, a, b } = egcd(s, y);
		const nq = a * q + b * x;
		flat.push(q - (s / g) * nq, x - (y / g) * nq);
		q = nq;
		s = g;
	}
	let p = 0;
	for (const x of flat) p = gcd2(p, x);
	return { p, q: p > 0 ? ((q % p) + p) % p : q, s };
}

/**
 * A fold of the plane onto one representative per coset of the face's period subgroup P, plus a tag
 * naming P itself. Two faces are comparable only through the same fold, which is why everything here
 * is derived from P alone and never from the arbitrary lifts the flood fill happened to pick.
 */
function quotient(f: FaceInfo): { tag: string; fold: (x: number, y: number) => string } {
	if (f.rank === 0) return { tag: "0", fold: (x, y) => `${x}.${y}` };
	if (f.rank === 1) {
		const g = rank1Generator(f.periods);
		const m = gcd2(g[0], g[1]);
		const u: [number, number] = [g[0] / m, g[1] / m]; // primitive direction of the strip
		// Complete u to a basis (u, w) of Z^2 with determinant 1 — a deterministic function of u, so two
		// strips with the same generator get the same coordinates. In that basis P is generated by (m, 0),
		// so the first coordinate mod m and the second coordinate name the coset.
		const { a, b } = egcd(u[0], u[1]); // a*ux + b*uy = 1
		return {
			tag: `1.${g[0]},${g[1]}`,
			fold: (x, y) => `${(((x * a + y * b) % m) + m) % m}.${y * u[0] - x * u[1]}`,
		};
	}
	const { p, q, s } = hnf2(f.periods);
	return {
		tag: `2.${p},${q},${s}`,
		fold: (x, y) => {
			const j = ((y % s) + s) % s;
			return `${((((x - ((y - j) / s) * q) % p) + p) % p)}.${j}`;
		},
	};
}

/**
 * Canonical name of a face up to TRANSLATION. Minimising over "slide lift e onto the origin" is a
 * complete canonical form: any translation identifying two faces carries some cell of one onto a cell
 * of the other, so the winning candidate is always among these |T| — no need to walk all of Z^2/P,
 * which for an unbounded face is det(L) times larger than the face's own transversal.
 */
function poseKey(f: FaceInfo): string {
	const { tag, fold } = quotient(f);
	let best: string | null = null;
	for (const [ex, ey] of f.lifts) {
		const key = `${tag}|${f.lifts.map(([x, y]) => fold(x - ex, y - ey)).sort().join(" ")}`;
		if (best === null || key < best) best = key;
	}
	return best ?? tag;
}

/** The 8 symmetries of the square grid, as (x, y) -> (ax + by, cx + dy). */
const D4: [number, number, number, number][] = [
	[1, 0, 0, 1],
	[0, -1, 1, 0],
	[-1, 0, 0, -1],
	[0, 1, -1, 0],
	[1, 0, 0, -1],
	[-1, 0, 0, 1],
	[0, 1, 1, 0],
	[0, -1, -1, 0],
];

/**
 * The 12 symmetries of the triangular grid in its own (e1, e2) basis: powers of the 60° rotation
 * (x, y) -> (-y, x + y) times the mirror (x, y) -> (x + y, -y). Acting on tripled centroids these
 * permute the triangle cells, so the same lifts/periods machinery serves both grids.
 */
const D6: [number, number, number, number][] = (() => {
	const rot: [number, number, number, number] = [0, -1, 1, 1];
	const mir: [number, number, number, number] = [1, 1, 0, -1];
	const mul = (
		m: [number, number, number, number],
		n: [number, number, number, number],
	): [number, number, number, number] => [
		m[0] * n[0] + m[1] * n[2],
		m[0] * n[1] + m[1] * n[3],
		m[2] * n[0] + m[3] * n[2],
		m[2] * n[1] + m[3] * n[3],
	];
	const out: [number, number, number, number][] = [];
	let r: [number, number, number, number] = [1, 0, 0, 1];
	for (let i = 0; i < 6; i++) {
		out.push(r, mul(r, mir));
		r = mul(rot, r);
	}
	return out;
})();

/** Canonical name of a face up to translation AND the grid symmetries: its congruence class. */
function shapeKey(f: FaceInfo, grid: FreedrawGrid): string {
	let best: string | null = null;
	for (const [a, b, c, d] of grid === "triangle" ? D6 : D4) {
		const move = ([x, y]: [number, number]): [number, number] => [a * x + b * y, c * x + d * y];
		const key = poseKey({ ...f, lifts: f.lifts.map(move), periods: f.periods.map(move) });
		if (best === null || key < best) best = key;
	}
	return best as string;
}

export interface FaceClasses {
	/** Class index per face id, merging faces equal up to translation. */
	pose: number[];
	/** Class index per face id, merging faces congruent under translation + the grid symmetries. */
	shape: number[];
	poseCount: number;
	shapeCount: number;
}

// Keyed on the analysis object, which every caller already memoises per pattern, so the classification
// runs once even though the renderer asks for it on every frame.
const classCache = new WeakMap<FaceAnalysis, FaceClasses>();

/**
 * Group the faces by shape and by pose. Class indices are assigned in face order, so face 0 keeps
 * colour 0 in all three of shape / pose / orbit and toggling between them reads as a split, not a
 * reshuffle. Costs a few hundred string comparisons per face; only ever called for those two fills.
 */
export function classifyFaces(a: FaceAnalysis): FaceClasses {
	const hit = classCache.get(a);
	if (hit) return hit;
	const index = (keys: string[]): number[] => {
		const seen = new Map<string, number>();
		return keys.map((k) => {
			const at = seen.get(k);
			if (at !== undefined) return at;
			seen.set(k, seen.size);
			return seen.size - 1;
		});
	};
	const pose = index(a.faces.map(poseKey));
	const shape = index(a.faces.map((f) => shapeKey(f, a.grid)));
	const out: FaceClasses = {
		pose,
		shape,
		poseCount: new Set(pose).size,
		shapeCount: new Set(shape).size,
	};
	classCache.set(a, out);
	return out;
}

// ── shape/pose for combined-grid patches ────────────────────────────────────────────────────────────
// The fixed-grid poseKey/shapeKey above run off FaceInfo.lifts, which patches don't have (there is no
// lattice to lift into). So classify a patch component straight from its polygon GEOMETRY in world
// coordinates. Two components share a POSE when one is a pure translate of the other, and a SHAPE when
// they are congruent under translation + rotation + reflection. This is what makes "shape" colour every
// triangle alike and every square alike, instead of the per-component fallback that gave each of the
// (e.g.) 18 tile orbits its own hue.

// Cluster tolerance. Patch coordinates are sums of 0.5 and √3/2 ≈ 0.866, and the smallest gap between
// distinct tile vertices is ~0.5, so rounding to 1e-3 matches congruent points without merging distinct
// ones — even after a 30° rotation introduces fresh irrationals.
const patchRound = (v: number) => Math.round(v * 1000) / 1000;

// 24 congruences to try for a SHAPE key: 12 rotations in 30° steps (the tile edges lie in 30°-multiple
// directions, so a coarser step would miss real congruences and a finer one is unnecessary) times the
// x-axis reflection. Precomputed once.
const PATCH_SYM: [number, number, number, number][] = (() => {
	const out: [number, number, number, number][] = [];
	for (let k = 0; k < 12; k++) {
		const a = (k * Math.PI) / 6;
		const c = Math.cos(a);
		const s = Math.sin(a);
		out.push([c, -s, s, c]); // rotation
		out.push([c, s, s, -c]); // rotation ∘ reflection
	}
	return out;
})();

/**
 * Lay one component's cells out CONNECTED, returning a lift (period offset) per poly index.
 *
 * The catch this solves: the developer emits one cell per cell-orbit at its fundamental-domain
 * position, so the cells of a single tile can sit a full period apart with no shared corner — a
 * 2-square domino whose two squares are linked only through a period translation, or a hexagon whose
 * six triangles are scattered. Reading geometry off those raw positions gives a wrong shape and breaks
 * any boundary walk. So flood-fill the cells across shared UNDRAWN edges, assigning each a lift that
 * makes it adjacent to its neighbour.
 *
 * Only undrawn edges are crossed, and that restriction is load-bearing, not a nicety: a tile with one
 * copy per period (the honeycomb — one hexagon per period) borders PERIODIC COPIES OF ITSELF across its
 * drawn boundary, so those boundary edges also match another cell of the same component. Crossing them
 * would fold a neighbour onto this tile and scatter the layout. A drawn edge is a boundary by
 * definition; never step over it. Each half-edge is keyed by its two vertex indices and the
 * period-invariant offset between them, so the two cells across a shared edge always match.
 *
 * Shared by componentPoints (shape/pose classification) and regular.ts (regular-polygon detection).
 */
export function componentLifts(patch: FreedrawPatch, comp: number): Map<number, [number, number]> {
	const idxs: number[] = [];
	for (let pi = 0; pi < patch.polys.length; pi++) if (patch.polyComp[pi] === comp) idxs.push(pi);
	if (idxs.length === 0) return new Map();

	const drawn = new Map<string, boolean>();
	for (const [a, b, dx, dy, d] of patch.edges) {
		drawn.set(`${a},${b},${dx},${dy}`, d === 1);
		drawn.set(`${b},${a},${-dx},${-dy}`, d === 1);
	}

	// Undrawn half-edges of one poly: for each edge, the lower-indexed endpoint's offset and a key shared
	// by the same undirected edge on the neighbouring cell. Drawn edges are tile boundaries — omitted, so
	// the flood never crosses them.
	const halfEdges = (pi: number) => {
		const ring = patch.polys[pi];
		const out: { key: string; offU: [number, number] }[] = [];
		for (let i = 0; i < ring.length; i++) {
			const [va, ax, ay] = ring[i];
			const [vb, bx, by] = ring[(i + 1) % ring.length];
			if (drawn.get(`${va},${vb},${bx - ax},${by - ay}`)) continue;
			const [offU, offV] = va < vb ? [[ax, ay], [bx, by]] : [[bx, by], [ax, ay]];
			const o = offU as [number, number];
			const ov = offV as [number, number];
			out.push({ key: `${Math.min(va, vb)},${Math.max(va, vb)},${ov[0] - o[0]},${ov[1] - o[1]}`, offU: o });
		}
		return out;
	};

	const index = new Map<string, { pi: number; offU: [number, number] }[]>();
	for (const pi of idxs)
		for (const e of halfEdges(pi)) (index.get(e.key) ?? index.set(e.key, []).get(e.key)!).push({ pi, offU: e.offU });

	const lift = new Map<number, [number, number]>([[idxs[0], [0, 0]]]);
	const queue = [idxs[0]];
	for (let qi = 0; qi < queue.length; qi++) {
		const pi = queue[qi];
		const [lx, ly] = lift.get(pi)!;
		for (const e of halfEdges(pi)) {
			for (const m of index.get(e.key) ?? []) {
				if (m.pi === pi || lift.has(m.pi)) continue;
				// e's endpoint sits at e.offU + L; the neighbour's same endpoint at m.offU + Lm. Equate.
				lift.set(m.pi, [lx + e.offU[0] - m.offU[0], ly + e.offU[1] - m.offU[1]]);
				queue.push(m.pi);
			}
		}
	}
	return lift;
}

/** World-coordinate vertices of one component's tile, reassembled connected via componentLifts. */
function componentPoints(patch: FreedrawPatch, comp: number): [number, number][] {
	const [t1x, t1y] = patch.T1;
	const [t2x, t2y] = patch.T2;
	const lift = componentLifts(patch, comp);
	const pts: [number, number][] = [];
	for (let pi = 0; pi < patch.polys.length; pi++) {
		if (patch.polyComp[pi] !== comp) continue;
		const [lx, ly] = lift.get(pi) ?? [0, 0];
		for (const [vi, ox, oy] of patch.polys[pi]) {
			const x = ox + lx;
			const y = oy + ly;
			pts.push([patch.verts[vi][0] + x * t1x + y * t2x, patch.verts[vi][1] + x * t1y + y * t2y]);
		}
	}
	return pts;
}

/** Translation-invariant fingerprint of a point set: recentre on the mean, round, dedupe, sort. */
function translationKey(pts: [number, number][]): string {
	const n = pts.length || 1;
	let mx = 0;
	let my = 0;
	for (const [x, y] of pts) {
		mx += x;
		my += y;
	}
	mx /= n;
	my /= n;
	const seen = new Set<string>();
	for (const [x, y] of pts) seen.add(`${patchRound(x - mx)},${patchRound(y - my)}`);
	return [...seen].sort().join(" ");
}

/** Congruence fingerprint: the smallest translation key over all 24 rotations/reflections. */
function congruenceKey(pts: [number, number][]): string {
	let best: string | null = null;
	for (const [a, b, c, d] of PATCH_SYM) {
		const key = translationKey(pts.map(([x, y]) => [a * x + b * y, c * x + d * y]));
		if (best === null || key < best) best = key;
	}
	return best as string;
}

const patchClassCache = new WeakMap<FreedrawPatch, FaceClasses>();

/**
 * Group a patch's tile components by pose and by shape, from their real geometry. Non-finite components
 * (strips, sheets) are period-truncated, so their point set depends on the emitted representative and
 * this classifies them by that unit — an approximation, but never worse than the per-component fallback
 * it replaces, and finite tiles (the overwhelming majority, and the ones the user sees mis-coloured) are
 * exact. Memoised on the patch object.
 */
export function classifyPatchFaces(patch: FreedrawPatch): FaceClasses {
	const hit = patchClassCache.get(patch);
	if (hit) return hit;
	const index = (keys: string[]): number[] => {
		const seen = new Map<string, number>();
		return keys.map((k) => {
			const at = seen.get(k);
			if (at !== undefined) return at;
			seen.set(k, seen.size);
			return seen.size - 1;
		});
	};
	const nComp = patch.compRank.length;
	const points = Array.from({ length: nComp }, (_, c) => componentPoints(patch, c));
	const pose = index(points.map(translationKey));
	const shape = index(points.map(congruenceKey));
	const out: FaceClasses = {
		pose,
		shape,
		poseCount: new Set(pose).size,
		shapeCount: new Set(shape).size,
	};
	patchClassCache.set(patch, out);
	return out;
}

/** Human-readable tile kind for the UI and for catalogue filters. */
export const rankLabel = (rank: 0 | 1 | 2, grid: FreedrawGrid = "square") =>
	rank === 0
		? grid === "triangle"
			? "polyiamond"
			: grid === "ts"
				? "polyform"
				: "polyomino"
		: rank === 1
			? "strip"
			: "unbounded";

export interface FaceSummary {
	faceOrbits: number;
	finite: number;
	strips: number;
	unbounded: number;
	withHoles: number;
	/** Area of each finite face, ascending. Empty when the pattern has no finite tile. */
	sizes: number[];
}

/** Summary used as a sort/filter key over the catalogue. */
export function summarise(a: FaceAnalysis): FaceSummary {
	let finite = 0;
	let strips = 0;
	let unbounded = 0;
	let withHoles = 0;
	const sizes: number[] = [];
	for (const f of a.faces) {
		if (f.rank === 0) {
			finite++;
			sizes.push(f.cells);
		} else if (f.rank === 1) strips++;
		else unbounded++;
		if (f.holes > 0) withHoles++;
	}
	sizes.sort((x, y) => x - y);
	return { faceOrbits: a.faces.length, finite, strips, unbounded, withHoles, sizes };
}
