// Face analysis for freedraw patterns. Answers the question Marek raised and did not have a method
// for: "it only needs some sort of automatic detection of whether it contains infinite tiles or not".
//
// The method. Faces (tiles) are the connected components of the grid CELLS under "adjacent and the
// shared edge is not drawn". Working on the torus R^2/L makes the component count finite, but it
// destroys the distinction we care about: a finite polyomino and an infinite strip can both be one
// torus component. So the flood fill also carries each cell's LIFT into Z^2. Reaching an already
// visited coset by a second route with a different lift yields a nonzero lattice vector that maps the
// face to itself. The rank of the span of those vectors classifies the tile:
//
//   rank 0 — finite. The face is a polyomino; distinct lifts are distinct tiles.
//   rank 1 — a strip, infinite along one primitive direction.
//   rank 2 — unbounded in two directions (the whole plane for the empty pattern, or a connected
//            "sheet" riddled with periodic holes, e.g. one drawn square per 2x2 block).
//
// For rank-0 faces the Euler characteristic of the closed polyomino gives the hole count directly,
// which is the other thing Marek wanted ("polyominoes with holes would be easily accessible here").

import { type FreedrawPattern, coset, cosetCount, drawnEast, drawnNorth } from "./pattern";

export interface FaceInfo {
	/** Index into FaceAnalysis.faces; also the value stored in cellFace. */
	id: number;
	/** Dimension of the span of the face's period vectors: 0 finite, 1 strip, 2 unbounded. */
	rank: 0 | 1 | 2;
	/** Cells of the face per fundamental domain. For rank 0 this is the polyomino's area. */
	cells: number;
	/** Holes in the closed polyomino (1 - Euler characteristic). Always 0 when rank > 0. */
	holes: number;
	/** Primitive period vector for rank 1; null otherwise. The strip's direction. */
	period: [number, number] | null;
}

export interface FaceAnalysis {
	faces: FaceInfo[];
	/** Face id per lattice coset, so a renderer can colour any cell by one lookup. */
	cellFace: Int32Array;
}

const gcd2 = (a: number, b: number): number => {
	a = Math.abs(a);
	b = Math.abs(b);
	while (b) [a, b] = [b, a % b];
	return a;
};

/** Rank of the Q-span of a set of integer 2-vectors. Rational rank is enough to classify a face. */
function spanRank(vs: [number, number][]): 0 | 1 | 2 {
	let first: [number, number] | null = null;
	for (const w of vs) {
		if (w[0] === 0 && w[1] === 0) continue;
		if (!first) {
			first = w;
			continue;
		}
		if (first[0] * w[1] - first[1] * w[0] !== 0) return 2;
	}
	return first ? 1 : 0;
}

/** Generator of a rank-1 subgroup of Z^2 given vectors known to be pairwise parallel. */
function rank1Generator(vs: [number, number][]): [number, number] {
	const nz = vs.filter((w) => w[0] !== 0 || w[1] !== 0);
	const u = nz[0];
	const g = gcd2(u[0], u[1]);
	const prim: [number, number] = [u[0] / g, u[1] / g];
	// Every vector is an integer multiple of prim; the subgroup is generated by gcd(multiples) * prim.
	let m = 0;
	for (const w of nz) m = gcd2(m, prim[0] !== 0 ? w[0] / prim[0] : w[1] / prim[1]);
	const gen: [number, number] = [prim[0] * m, prim[1] * m];
	// Normalise the sign so the direction is deterministic across runs.
	if (gen[0] < 0 || (gen[0] === 0 && gen[1] < 0)) return [-gen[0], -gen[1]];
	return gen;
}

/** Holes in a connected polyomino given its cells' lower-left corners: 1 - (V - E + F). */
function holeCount(cells: [number, number][]): number {
	const verts = new Set<string>();
	const edges = new Set<string>();
	for (const [x, y] of cells) {
		verts.add(`${x},${y}`);
		verts.add(`${x + 1},${y}`);
		verts.add(`${x},${y + 1}`);
		verts.add(`${x + 1},${y + 1}`);
		edges.add(`h${x},${y}`);
		edges.add(`h${x},${y + 1}`);
		edges.add(`v${x},${y}`);
		edges.add(`v${x + 1},${y}`);
	}
	return 1 - (verts.size - edges.size + cells.length);
}

/**
 * Classify every face of a pattern. O(n) in the number of lattice cosets, so it is cheap enough to
 * run on load for a whole catalogue page rather than being baked into the data file.
 */
export function analyseFaces(p: FreedrawPattern): FaceAnalysis {
	const n = cosetCount(p);
	const cellFace = new Int32Array(n).fill(-1);
	const faces: FaceInfo[] = [];
	// Absolute lift of each visited coset, as a flat [x, y] pair store.
	const liftX = new Int32Array(n);
	const liftY = new Int32Array(n);

	for (let start = 0; start < n; start++) {
		if (cellFace[start] !== -1) continue;
		const id = faces.length;
		const sx = start % p.a;
		const sy = Math.floor(start / p.a);
		cellFace[start] = id;
		liftX[start] = sx;
		liftY[start] = sy;

		const periods: [number, number][] = [];
		const lifted: [number, number][] = [[sx, sy]];
		const queue: number[] = [start];
		for (let qi = 0; qi < queue.length; qi++) {
			const c = queue[qi];
			const x = liftX[c];
			const y = liftY[c];
			// Neighbour cell, and the drawn edge that would block the step.
			const steps: [number, number, boolean][] = [
				[x + 1, y, drawnNorth(p, x + 1, y)],
				[x - 1, y, drawnNorth(p, x, y)],
				[x, y + 1, drawnEast(p, x, y + 1)],
				[x, y - 1, drawnEast(p, x, y)],
			];
			for (const [nx, ny, blocked] of steps) {
				if (blocked) continue;
				const nc = coset(p, nx, ny);
				if (cellFace[nc] === -1) {
					cellFace[nc] = id;
					liftX[nc] = nx;
					liftY[nc] = ny;
					lifted.push([nx, ny]);
					queue.push(nc);
				} else {
					// Second route to a known cell. The lift mismatch is a period of this face.
					const dx = nx - liftX[nc];
					const dy = ny - liftY[nc];
					if (dx !== 0 || dy !== 0) periods.push([dx, dy]);
				}
			}
		}

		const rank = spanRank(periods);
		faces.push({
			id,
			rank,
			cells: lifted.length,
			holes: rank === 0 ? holeCount(lifted) : 0,
			period: rank === 1 ? rank1Generator(periods) : null,
		});
	}

	return { faces, cellFace };
}

/** Human-readable tile kind for the UI and for catalogue filters. */
export const rankLabel = (rank: 0 | 1 | 2) =>
	rank === 0 ? "polyomino" : rank === 1 ? "strip" : "unbounded";

/** Summary used as a sort/filter key over the catalogue. */
export function summarise(a: FaceAnalysis) {
	let finite = 0;
	let strips = 0;
	let unbounded = 0;
	let withHoles = 0;
	for (const f of a.faces) {
		if (f.rank === 0) finite++;
		else if (f.rank === 1) strips++;
		else unbounded++;
		if (f.holes > 0) withHoles++;
	}
	return { faceOrbits: a.faces.length, finite, strips, unbounded, withHoles };
}
