// "Freedraw" tilings (Marek Čtrnáct, 2026-07): the combinatorics lives entirely in which EDGES of an
// underlying grid are drawn, never in the tiles. A pattern is a periodic subset of the edges of Z^2
// with no vertex of degree exactly 1 (a degree-1 vertex is a dead end, which would make the figure a
// maze rather than a tiling). The tiles are whatever faces fall out, and they may be finite polyominoes,
// infinite strips, or 2-dimensionally unbounded regions — so they are NOT tiles in the Grünbaum &
// Shephard sense (closed topological disks) and none of the classical uniform-tiling theory applies.
//
// k = the number of GRID-POINT orbits under the pattern's own symmetry group. Note this counts grid
// points, including those with no drawn edge at all, so k measures how complicated the decoration of
// the grid is, not how complicated the resulting tiling is. Strips of width w give k ≈ w.
//
// The period lattice is stored in Hermite normal form: generated by (a, 0) and (b, d), index n = a*d,
// with 0 <= b < a. Bits are indexed BY GRID VERTEX, one vertex per lattice coset:
//   h[c] — the unit edge from vertex c east to c + (1,0)
//   v[c] — the unit edge from vertex c north to c + (0,1)
// Cells (the unit squares) share the same index scheme via their lower-left vertex.
//
// TRIANGULAR GRID (grid: "triangle", from Marek's triangles solver via develop_freedraw.py): the same
// HNF lattice, but its integer basis (e1, e2) sits at 60° in the plane, every vertex has SIX edges in
// three axes, and each lattice cell splits into an up triangle U and a down triangle D:
//   h[c] — the edge from vertex c along e1 to c + (1,0)
//   v[c] — the edge along e2 to c + (0,1)
//   w[c] — the "downhill diagonal" to c + (1,-1)
//   U(x,y) has corners (x,y), (x+1,y), (x,y+1);   D(x,y) has corners (x+1,y), (x,y+1), (x+1,y+1);
//   the two share the w edge based at (x, y+1).

export type FreedrawGrid = "square" | "triangle" | "ts";

/**
 * COMBINED GRID (grid: "ts"): squares and triangles mixed, so there is NO fixed lattice to index a
 * bitmask into — the underlying square-triangle tiling varies per solution. The developer
 * (tools/ctrnact-oracle/develop_freedraw.py --grid ts) emits explicit geometry instead: one period
 * of vertices, edges and polygon faces, each endpoint a (vertex index, integer T1/T2 offset) pair.
 * A record with `patch` carries 1x1 dummy lattice fields so the bitmask type stays total.
 */
export interface FreedrawPatch {
	/** Period translations, world coordinates. */
	T1: [number, number];
	T2: [number, number];
	/** Vertex positions of one fundamental domain, world coordinates. */
	verts: [number, number][];
	/** Grid-point orbit label per vertex — the patch's version of `orbit`. */
	vorbit: number[];
	/** [vi, vj, offX, offY, drawn]: segment verts[vi] -> verts[vj] + offX*T1 + offY*T2. */
	edges: [number, number, number, number, number][];
	/** Polygon rings: [vi, offX, offY] per corner, offsets relative to the ring's anchor corner. */
	polys: [number, number, number][][];
	/** Tile component (face orbit) id per polygon. */
	polyComp: number[];
	/** Per component: 0 finite, 1 strip, 2 unbounded — the same holonomy ranks as the fixed grids. */
	compRank: (0 | 1 | 2)[];
	compCells: number[];
	compHoles: number[];
	stats: { faceOrbits: number; finite: number; strips: number; unbounded: number; withHoles: number };
}

export interface FreedrawPattern {
	/** Stable catalogue id, e.g. "fd-2-017" (square), "fdt-2-0017" (triangle), "fdts-2-00017" (combined). */
	id: string;
	/** Number of grid-point orbits under the pattern's symmetry group. */
	k: number;
	/** Period lattice in HNF: generated by (a, 0) and (b, d). */
	a: number;
	b: number;
	d: number;
	/** East / e1 edge drawn, per lattice coset. Length a*d. */
	h: number[];
	/** North / e2 edge drawn, per lattice coset. Length a*d. */
	v: number[];
	/** Triangle grid only: the (1,-1) diagonal edge, per lattice coset. Length a*d. */
	w?: number[];
	/** Grid-point orbit label in [0, k), per lattice coset. Length a*d. */
	orbit: number[];
	/** Which grid the bits decorate. Absent = "square" (the original catalogue predates the field). */
	grid?: FreedrawGrid;
	/** Combined grid only: the explicit per-period geometry. Present exactly when grid === "ts". */
	patch?: FreedrawPatch;
}

export const gridOf = (p: FreedrawPattern): FreedrawGrid => p.grid ?? "square";

export const cosetCount = (p: Pick<FreedrawPattern, "a" | "d">) => p.a * p.d;

/**
 * Index of the lattice coset containing the integer point (x, y). Reduces y modulo d using the
 * (b, d) generator, then x modulo a using the (a, 0) generator. Works for negative coordinates:
 * Math.floor gives the correct rounding direction, unlike a bare `%`.
 */
export function coset(p: FreedrawPattern, x: number, y: number): number {
	const q = Math.floor(y / p.d);
	const j = y - q * p.d;
	const i = ((x - q * p.b) % p.a + p.a) % p.a;
	return j * p.a + i;
}

/** Is the unit edge from (x, y) east to (x+1, y) drawn? */
export const drawnEast = (p: FreedrawPattern, x: number, y: number) => p.h[coset(p, x, y)] === 1;

/** Is the unit edge from (x, y) north to (x, y+1) drawn? */
export const drawnNorth = (p: FreedrawPattern, x: number, y: number) => p.v[coset(p, x, y)] === 1;

/** Triangle grid only: is the diagonal edge from (x, y) to (x+1, y-1) drawn? */
export const drawnDiag = (p: FreedrawPattern, x: number, y: number) =>
	(p.w ?? [])[coset(p, x, y)] === 1;

/**
 * Number of drawn edges at grid point (x, y) — never exactly 1 by construction. On the square grid
 * this is 0..4 over the four compass edges (the Carcassonne-tile type Marek draws by hand); on the
 * triangular grid it is 0..6 over the three axes and their opposites.
 */
export function degree(p: FreedrawPattern, x: number, y: number): number {
	let n = 0;
	if (drawnEast(p, x, y)) n++;
	if (drawnNorth(p, x, y)) n++;
	if (drawnEast(p, x - 1, y)) n++;
	if (drawnNorth(p, x, y - 1)) n++;
	if (gridOf(p) === "triangle") {
		if (drawnDiag(p, x, y)) n++;
		if (drawnDiag(p, x - 1, y + 1)) n++;
	}
	return n;
}

/**
 * The four drawn directions at (x, y) as a bitmask: 1 = east, 2 = north, 4 = west, 8 = south. The 12
 * legal masks (all 16 minus the four single-bit ones) are the tile alphabet of the Carcassonne view.
 */
export function vertexMask(p: FreedrawPattern, x: number, y: number): number {
	return (
		(drawnEast(p, x, y) ? 1 : 0) |
		(drawnNorth(p, x, y) ? 2 : 0) |
		(drawnEast(p, x - 1, y) ? 4 : 0) |
		(drawnNorth(p, x, y - 1) ? 8 : 0)
	);
}
