import { describe, expect, it } from "vitest";
import { SPHERICAL_SOLIDS } from "@/lib/render/sphericalSolids";
import { NCX_EMBEDDED, NCX_SELF_INTERSECTING, ncxSelfIntersects } from "@/lib/tilings/ncx-crossing";

// lib/tilings/ncx-crossing.ts is generated by scripts/gen-ncx-crossing.mjs out of the comments the shelf
// generator writes above each solid. What can go wrong is DRIFT: the shelf is rebuilt, solids are added
// or reclassified, and nobody re-runs the script. These assert the two sides still describe one corpus,
// so a stale run fails loudly instead of filtering the library down to a wrong answer.
const ncxIds = SPHERICAL_SOLIDS.filter((s) => s.id.startsWith("ncx-")).map((s) => s.id);

describe("the non-convex shelf's crossing split", () => {
	it("partitions the shelf exactly — every solid on one side, none on both", () => {
		expect(ncxIds.length).toBeGreaterThan(0);
		const both = ncxIds.filter((id) => NCX_SELF_INTERSECTING.has(id) && NCX_EMBEDDED.has(id));
		expect(both, `on both sides: ${both.join(", ")}`).toEqual([]);
		const neither = ncxIds.filter((id) => !NCX_SELF_INTERSECTING.has(id) && !NCX_EMBEDDED.has(id));
		expect(neither, `classified by neither — re-run scripts/gen-ncx-crossing.mjs: ${neither.join(", ")}`).toEqual([]);
		expect(NCX_SELF_INTERSECTING.size + NCX_EMBEDDED.size).toBe(ncxIds.length);
	});

	it("names no solid the shelf does not ship", () => {
		const known = new Set(ncxIds);
		const strays = [...NCX_SELF_INTERSECTING, ...NCX_EMBEDDED].filter((id) => !known.has(id));
		expect(strays, `not on the shelf: ${strays.join(", ")}`).toEqual([]);
	});

	it("holds the counts the shelf's own header states", () => {
		// nonconvexSolids.ts opens with "SELF-INTERSECTING (112 of 243)" and "An embedded solid (131 of
		// 243)". If a rebuild moves these, that header and this test are both meant to move with it.
		expect(NCX_SELF_INTERSECTING.size).toBe(112);
		expect(NCX_EMBEDDED.size).toBe(131);
	});

	it("answers false for anything off this shelf", () => {
		// The facet asks this of every record it sees, and only the "ncx-" ids are its business.
		expect(ncxSelfIntersects("cube")).toBe(false);
		expect(ncxSelfIntersects("sp3-1-00001")).toBe(false);
		expect(ncxSelfIntersects(undefined)).toBe(false);
	});

	it("agrees with the one solid the circumsphere list also names", () => {
		// ncx-7-15-10-a is the only solid on this shelf WITH a circumsphere, and its comment therefore ends
		// ", self-intersecting, inscribed" instead of with the flag. The first version of the extractor
		// anchored on the end of the line and silently dropped it, coming out 242 of 243.
		expect(ncxSelfIntersects("ncx-7-15-10-a")).toBe(true);
	});
});
