/*
 * canonicalTilingKey — a representation-independent fingerprint of a periodic tiling given as a
 * float translational cell { cellPolygons, basis }. Two cells that describe the SAME infinite tiling
 * (up to any plane isometry AND any choice of fundamental domain, including non-primitive supercells
 * and sheared/relabelled bases) get the SAME key.
 *
 * Why this exists: the composable demo shelf (build-composable-atlas.ts) ingests the composite-engine
 * cells verbatim, and that enumeration emits the same tiling under many fundamental-domain choices —
 * e.g. a primitive 1-hex cell and its 2x supercell, or two orbit/@-index relabellings of one cell.
 * The regular/star atlas dedups with the EXACT `dedupeByCongruence`, but that needs exact ℤ[ζ] geometry
 * (absent here — the composite cells are float only) and, crucially, treats a primitive cell and its
 * supercell as different (it verifies the LATTICES are congruent). So the demo shelf needs a float,
 * fundamental-domain-invariant key instead. This is DISPLAY-ONLY dedup; the soundness bar is "don't
 * drop genuinely distinct tilings", handled by the two safeguards below.
 *
 * Method (validated against the reported duplicate pairs and the discriminating non-pairs):
 *  1. Primitive reduction. Find every translation that maps the cell's tile-set onto itself (exact
 *     integer arithmetic on fractional lattice coordinates), giving the tiling's true period lattice
 *     Λ* ⊇ Λ and its primitive area. This is what collapses supercells onto their primitive.
 *  2. Patch fingerprint. Expand the tiling to a disk of radius ∝ the PRIMITIVE period (so a primitive
 *     cell and its supercell — same primitive period — compare at the same radius), then take the
 *     lexicographically minimal labelled-tile patch over every near-origin anchor of the rarest tile
 *     type and every grid isometry (24 rotations x reflection). Congruent tilings share this minimum.
 *
 * Soundness (no false merge ⇒ no dropped tiling): the primitive AREA is part of the key, so cells with
 * different primitive cells never merge; and the compared patch radius exceeds one full period, so it
 * pins down the whole periodic tiling, not just a local motif. Completeness (all real duplicates found)
 * is empirical here — validated by re-running dedup at a larger radius and checking the count is stable.
 */

export interface CanonCell {
	cellPolygons: { n: number; vertices: number[][]; star?: boolean }[];
	basis: number[][];
}

const NDEC = 6;
const POW = 10 ** NDEC;
// Integer micro-units of a fractional lattice coordinate. MUST be divisible by the small denominators
// a supercell period can land on (½, ⅓, ¼, ⅙, ⅛, …) or the modular period test misses them: with a
// power-of-ten scale, ⅓ rounds to 333333 and ⅓+⅓ = 666666 ≠ 666667, so a 3×/6× supercell fails to
// reduce to its primitive and false-splits from it in the key. 720720 = lcm(1..16) makes every such
// third/quarter/sixth/… exact, while staying small enough (~7e5) that float noise never flips a round.
const SCALE = 720720;
const r = (x: number): number => Math.round(x * POW) / POW;

/** Rotation/reflection-invariant shape descriptor: polygon order + sorted squared centroid-distances. */
function shapeInvariant(vs: number[][], cx: number, cy: number): string {
	const d = vs.map(([x, y]) => r((x - cx) ** 2 + (y - cy) ** 2)).sort((a, b) => a - b);
	return `${vs.length}:${d.join(",")}`;
}
const gcd = (a: number, b: number): number => {
	a = Math.abs(a);
	b = Math.abs(b);
	while (b) [a, b] = [b, a % b];
	return a;
};

/** Basis of the 2-D integer lattice generated by the given integer 2-vectors (column HNF). */
function latticeBasis(gens: [number, number][]): [[number, number], [number, number]] {
	let cols = gens.map((g) => [g[0], g[1]] as [number, number]).filter((c) => c[0] !== 0 || c[1] !== 0);
	// Reduce so at most one column has a nonzero first coordinate (Euclid on the first row).
	for (let guard = 0; guard < 10000; guard++) {
		const nz = cols.map((c, i) => [c, i] as const).filter(([c]) => c[0] !== 0);
		if (nz.length <= 1) break;
		nz.sort((a, b) => Math.abs(a[0][0]) - Math.abs(b[0][0]));
		const [small] = nz[0];
		const [big, bi] = nz[1];
		const q = Math.round(big[0] / small[0]);
		cols[bi] = [big[0] - q * small[0], big[1] - q * small[1]];
	}
	const p1 = cols.find((c) => c[0] !== 0) ?? [0, 0];
	// Second basis vector: gcd of the second coordinates of the columns with first coord 0.
	let g = 0;
	for (const c of cols) if (c !== p1 && c[0] === 0 && c[1] !== 0) g = gcd(g, c[1]);
	const b2: [number, number] = g !== 0 ? [0, g] : [0, 0];
	return [p1 as [number, number], b2];
}

function centroid(vs: number[][]): [number, number] {
	let x = 0;
	let y = 0;
	for (const [px, py] of vs) {
		x += px;
		y += py;
	}
	return [x / vs.length, y / vs.length];
}

/** Orientation-sensitive, translation-invariant descriptor of a tile (rounded vertex offsets). */
function shapeDesc(vs: number[][], cx: number, cy: number): string {
	return vs
		.map(([x, y]) => `${r(x - cx)},${r(y - cy)}`)
		.sort()
		.join(";");
}

/** Primitive period (max reduced-basis diagonal) and primitive cell area of the tiling. */
function primitivePeriodArea(cell: CanonCell): { period: number; area: number } {
	const [[ux, uy], [vx, vy]] = cell.basis;
	const det = ux * vy - uy * vx;
	const inv = [
		[vy / det, -vx / det],
		[-uy / det, ux / det],
	];
	const origArea = Math.abs(det);
	const tiles = cell.cellPolygons.map((p) => {
		const [cx, cy] = centroid(p.vertices);
		return {
			a: inv[0][0] * cx + inv[0][1] * cy, // fractional lattice coords of the centroid
			b: inv[1][0] * cx + inv[1][1] * cy,
			desc: shapeDesc(p.vertices, cx, cy),
		};
	});
	const fi = (x: number): number => ((Math.round((((x % 1) + 1) % 1) * SCALE) % SCALE) + SCALE) % SCALE;
	const S = new Set(tiles.map((t) => `${fi(t.a)},${fi(t.b)},${t.desc}`));
	// Candidate translations: differences between same-shape tiles (a period maps like to like).
	const byDesc = new Map<string, { a: number; b: number }[]>();
	for (const t of tiles) (byDesc.get(t.desc) ?? byDesc.set(t.desc, []).get(t.desc)!).push(t);
	const cands = new Set<string>();
	for (const [, lst] of byDesc) {
		const base = lst[0];
		for (const t of lst) cands.add(`${fi(t.a - base.a)},${fi(t.b - base.b)}`);
	}
	const periods: [number, number][] = [];
	for (const c of cands) {
		const [ta, tb] = c.split(",").map(Number);
		if (ta === 0 && tb === 0) continue;
		const shifted = new Set(
			tiles.map((t) => `${(fi(t.a) + ta) % SCALE},${(fi(t.b) + tb) % SCALE},${t.desc}`),
		);
		if (shifted.size === S.size && [...shifted].every((x) => S.has(x))) periods.push([ta, tb]);
	}
	const gens: [number, number][] = [[SCALE, 0], [0, SCALE], ...periods];
	const [Lb1, Lb2] = latticeBasis(gens);
	// Map fractional (micro-unit) basis to real vectors, Gauss-reduce, report max diagonal + area.
	const toReal = (bv: [number, number]): [number, number] => [
		(bv[0] / SCALE) * ux + (bv[1] / SCALE) * vx,
		(bv[0] / SCALE) * uy + (bv[1] / SCALE) * vy,
	];
	let a1 = toReal(Lb1);
	let a2 = toReal(Lb2);
	const dot = (p: number[], q: number[]): number => p[0] * q[0] + p[1] * q[1];
	for (let i = 0; i < 50; i++) {
		if (dot(a2, a2) < dot(a1, a1)) [a1, a2] = [a2, a1];
		if (dot(a1, a1) === 0) break;
		const m = Math.round(dot(a1, a2) / dot(a1, a1));
		if (m === 0) break;
		a2 = [a2[0] - m * a1[0], a2[1] - m * a1[1]];
	}
	const hyp = (x: number, y: number): number => Math.hypot(x, y);
	const period = Math.max(
		hyp(a1[0], a1[1]),
		hyp(a2[0], a2[1]),
		hyp(a1[0] + a2[0], a1[1] + a2[1]),
		hyp(a1[0] - a2[0], a1[1] - a2[1]),
	);
	const area = Math.abs(a1[0] * a2[1] - a1[1] * a2[0]) || origArea;
	return { period, area };
}

/**
 * Canonical key of a periodic tiling. `radiusFactor` scales the compared patch radius relative to the
 * primitive period; the default is safely above one period. Pass a larger value to stability-test a
 * dedup (the distinct-count must not change).
 */
export function canonicalTilingKey(cell: CanonCell, radiusFactor = 1.1): string {
	const { period, area } = primitivePeriodArea(cell);
	const r1 = period * radiusFactor + 0.5; // compared patch radius (≥ one full period)
	const [[ux, uy], [vx, vy]] = cell.basis;
	const bmin = Math.min(Math.hypot(ux, uy), Math.hypot(vx, vy)) || 1;

	// Precompute each cell polygon's centroid, centroid-relative offsets, and invariant shape.
	const cps = cell.cellPolygons.map((p) => {
		const [cx, cy] = centroid(p.vertices);
		const offs = p.vertices.map(([x, y]) => [x - cx, y - cy] as [number, number]);
		const circum = Math.max(...offs.map(([dx, dy]) => Math.hypot(dx, dy)));
		return { cx, cy, offs, circum, shape: shapeInvariant(p.vertices, cx, cy) };
	});
	const R = r1 + Math.max(...cps.map((p) => p.circum)) + 0.5; // generation radius (anchor is at origin)
	const M = Math.ceil(R / bmin) + 2;

	// Anchor set = cell polygons of the rarest SHAPE (orientation-invariant, so both a tiling and its
	// rotated/reflected twin pick the same shape; a supercell just has a few copies). Anchoring each at
	// the origin keeps the generated patch to ~one period instead of ~two, the main cost lever.
	const shapeCount = new Map<string, number>();
	for (const p of cps) shapeCount.set(p.shape, (shapeCount.get(p.shape) ?? 0) + 1);
	let rare = cps[0].shape;
	for (const p of cps) {
		const c = shapeCount.get(p.shape)!;
		const cr = shapeCount.get(rare)!;
		if (c < cr || (c === cr && p.shape < rare)) rare = p.shape;
	}
	const anchors = cps.filter((p) => p.shape === rare);

	// Grid isometries: 24 rotations (15° steps cover 3/4/6/8/12-fold) x optional reflection.
	const lins: [number, number, number][] = [];
	for (let t = 0; t < 24; t++) {
		const th = (Math.PI * 2 * t) / 24;
		lins.push([1, Math.cos(th), Math.sin(th)]);
		lins.push([-1, Math.cos(th), Math.sin(th)]);
	}

	let best: string | null = null;
	for (const A of anchors) {
		// Materialize the tiling with A at the origin (shift every lattice copy by -A.centroid).
		const tiles: { cx: number; cy: number; offs: [number, number][] }[] = [];
		for (let i = -M; i <= M; i++) {
			for (let j = -M; j <= M; j++) {
				const tx = i * ux + j * vx - A.cx;
				const ty = i * uy + j * vy - A.cy;
				for (const p of cps) {
					const cx = p.cx + tx;
					const cy = p.cy + ty;
					if (cx * cx + cy * cy <= R * R) tiles.push({ cx, cy, offs: p.offs });
				}
			}
		}
		for (const [rf, c, s] of lins) {
			const items: string[] = [];
			for (const t of tiles) {
				const X = t.cx * rf;
				const Y = t.cy;
				const rx = c * X - s * Y;
				const ry = s * X + c * Y;
				if (rx * rx + ry * ry > r1 * r1) continue;
				const offs = t.offs
					.map(([dx, dy]) => {
						const X2 = dx * rf;
						return `${r(c * X2 - s * dy)},${r(s * X2 + c * dy)}`;
					})
					.sort()
					.join(";");
				items.push(`${r(rx)},${r(ry)}|${offs}`);
			}
			items.sort();
			const key = items.join("/");
			if (best === null || key < best) best = key;
		}
	}
	return `A${r(area)}#${best ?? ""}`;
}

/** Canonical form of a cyclic sequence up to rotation and reversal (min over all rotations of it and its reverse). */
function canonCyclic(seq: string[]): string {
	let best: string | null = null;
	for (const s of [seq, [...seq].reverse()]) {
		for (let i = 0; i < s.length; i++) {
			const f = s.slice(i).concat(s.slice(0, i)).join(",");
			if (best === null || f < best) best = f;
		}
	}
	return best ?? "";
}

/**
 * True vertex-orbit count (k-uniformity) of a periodic tiling under its FULL symmetry group — mirror
 * images counted as ONE orbit. This is the standard k-uniform definition and the project's chirality-
 * MERGE convention (CLAUDE.md). The composite engine counts orbits under the orientation-preserving
 * subgroup only, so an achiral tiling whose vertex figures come in mirror pairs (e.g. the dodecagon +
 * cx9 tiling: two (cx9,12,3) vertices that are each other's mirror) gets its k inflated; this recovers
 * the correct, lower value.
 *
 * `engineK` is the enumerator's chiral count. Orbits under the full group are unions of the chiral
 * orbits, so the true count is always ≤ engineK. Two tiers for speed:
 *  - Cheap: distinct vertex figures up to rotation+reflection is a fast lower bound (cheap ≤ true ≤
 *    engineK). When it already equals engineK nothing can merge, so return early — the common case.
 *  - Exact: otherwise, count distinct per-vertex patch fingerprints, each canonicalised over all 24
 *    rotations × reflection at a radius > one period. For a periodic tiling, two vertices with
 *    reflection-congruent neighbourhoods that large are provably in the same orbit (the reflection
 *    extends to a global symmetry), so this never falsely merges a genuinely chiral pair.
 */
export function trueVertexOrbitCount(cell: CanonCell, engineK: number): number {
	if (engineK <= 1) return engineK;
	const { period } = primitivePeriodArea(cell);
	const [[ux, uy], [vx, vy]] = cell.basis;
	const bmin = Math.min(Math.hypot(ux, uy), Math.hypot(vx, vy)) || 1;
	const cps = cell.cellPolygons.map((p) => {
		const [cx, cy] = centroid(p.vertices);
		const offs = p.vertices.map(([x, y]) => [x - cx, y - cy] as [number, number]);
		const circum = Math.max(...offs.map(([dx, dy]) => Math.hypot(dx, dy)));
		return { cx, cy, verts: p.vertices, offs, circum, shape: shapeInvariant(p.vertices, cx, cy) };
	});
	const maxCircum = Math.max(...cps.map((p) => p.circum));

	const buildPatch = (radius: number) => {
		const M = Math.ceil(radius / bmin) + 2;
		const tiles: { cx: number; cy: number; offs: [number, number][]; verts: number[][]; shape: string }[] = [];
		for (let i = -M; i <= M; i++) {
			for (let j = -M; j <= M; j++) {
				const tx = i * ux + j * vx;
				const ty = i * uy + j * vy;
				for (const p of cps) {
					const cx = p.cx + tx;
					const cy = p.cy + ty;
					if (cx * cx + cy * cy <= radius * radius)
						tiles.push({ cx, cy, offs: p.offs, verts: p.verts.map(([x, y]) => [x + tx, y + ty]), shape: p.shape });
				}
			}
		}
		return tiles;
	};

	// Cheap pass: interior vertices within one period of the origin (every orbit is represented there),
	// their figures canonicalised up to rotation+reflection.
	const inc = new Map<string, { shape: string; angle: number; theta: number }[]>();
	const vpos = new Map<string, [number, number]>();
	for (const t of buildPatch(period + maxCircum + 1)) {
		const m = t.verts.length;
		for (let k = 0; k < m; k++) {
			const [bx, by] = t.verts[k];
			const [ax, ay] = t.verts[(k - 1 + m) % m];
			const [nx, ny] = t.verts[(k + 1) % m];
			const vk = `${Math.round(bx * 1000)},${Math.round(by * 1000)}`;
			const d =
				((ax - bx) * (nx - bx) + (ay - by) * (ny - by)) /
				(Math.hypot(ax - bx, ay - by) * Math.hypot(nx - bx, ny - by));
			const angle = Math.round((Math.acos(Math.max(-1, Math.min(1, d))) * 180) / Math.PI);
			const theta = Math.atan2((ay + ny) / 2 - by, (ax + nx) / 2 - bx);
			(inc.get(vk) ?? inc.set(vk, []).get(vk)!).push({ shape: t.shape, angle, theta });
			if (!vpos.has(vk)) vpos.set(vk, [bx, by]);
		}
	}
	const figs = new Set<string>();
	const nearVerts: [number, number][] = [];
	for (const [vk, list] of inc) {
		const [x, y] = vpos.get(vk)!;
		if (x * x + y * y > period * period) continue;
		if (Math.abs(list.reduce((sum, c) => sum + c.angle, 0) - 360) > 3) continue; // interior only
		figs.add(canonCyclic([...list].sort((a, b) => a.theta - b.theta).map((c) => `${c.shape}:${c.angle}`)));
		nearVerts.push([x, y]);
	}
	if (figs.size >= engineK) return engineK; // cheap == engineK ⇒ nothing merges

	// Exact pass: distinct per-vertex fingerprints (radius > one period ⇒ no false merge).
	const r1 = period * 1.1 + 0.5;
	const patch = buildPatch(period + r1 + maxCircum + 1);
	const lins: [number, number, number][] = [];
	for (let t = 0; t < 24; t++) {
		const th = (Math.PI * 2 * t) / 24;
		lins.push([1, Math.cos(th), Math.sin(th)]);
		lins.push([-1, Math.cos(th), Math.sin(th)]);
	}
	const fps = new Set<string>();
	for (const [ax, ay] of nearVerts) {
		let best: string | null = null;
		for (const [rf, c, s] of lins) {
			const items: string[] = [];
			for (const t of patch) {
				const X = (t.cx - ax) * rf;
				const Y = t.cy - ay;
				const rx = c * X - s * Y;
				const ry = s * X + c * Y;
				if (rx * rx + ry * ry > r1 * r1) continue;
				const offs = t.offs
					.map(([dx, dy]) => {
						const X2 = dx * rf;
						return `${r(c * X2 - s * dy)},${r(s * X2 + c * dy)}`;
					})
					.sort()
					.join(";");
				items.push(`${r(rx)},${r(ry)}|${offs}`);
			}
			items.sort();
			const key = items.join("/");
			if (best === null || key < best) best = key;
		}
		fps.add(best ?? "");
	}
	return fps.size;
}
