import { Cyclotomic, CyclotomicRing } from '@/classes';
import { Polyform } from './Polyform';

/**
 * Convex unit-edge tiles on the 30° grid, generated by boundary enumeration (the pivot away
 * from gluing-BFS). A tile is a cyclic word of interior-angle "units" over {2,3,4,5}
 * (60°/90°/120°/150° = 2/3/4/5 units of 30° = 2π/12). Everything decisive is exact ℤ[ζ₁₂];
 * float never enters the closure test.
 *
 * Boundary walk: edge j points along ζ^{dir[j]}. The exterior turn at vertex j is (6 − word[j])
 * units (interior = π − exterior). Fix dir[0] = 0; dir[j] = dir[j−1] + (6 − word[j]) mod 12.
 * The polygon closes iff Σ_j ζ^{dir[j]} = 0 exactly (a real ℤ[ζ₁₂] zero, NOT a float tolerance).
 */

const ANGLE_UNITS = [2, 3, 4, 5] as const;

/**
 * Exact vertices of a convex unit-edge tile given its cyclic interior-angle word (D=12 units).
 * Walk from the exact origin along the ζ^{dir[j]} unit edges; return the n vertices v0..v_{n-1}
 * (the closing duplicate v_n = v0 is dropped). All arithmetic exact.
 */
export function tileVertices(word: number[], ring: CyclotomicRing): Cyclotomic[] {
  const n = word.length;
  const dirs = new Array<number>(n);
  dirs[0] = 0;
  for (let j = 1; j < n; j++) {
    dirs[j] = (((dirs[j - 1] + (6 - word[j])) % 12) + 12) % 12;
  }
  const verts: Cyclotomic[] = [];
  let v = Cyclotomic.fromRational(ring, 0n); // exact 0
  for (let j = 0; j < n; j++) {
    verts.push(v);
    v = v.add(Cyclotomic.zeta(ring, dirs[j]));
  }
  return verts; // v0..v_{n-1}; closing edge from v_{n-1} returns to v0 when the word closes
}

/** True iff the boundary walk of `word` returns to its start (Σ unit edge vectors = exact zero). */
function closes(word: number[], ring: CyclotomicRing, zeroKey: string): boolean {
  let dir = 0;
  let sum = Cyclotomic.zeta(ring, 0); // dir[0] = 0
  for (let j = 1; j < word.length; j++) {
    dir = (((dir + (6 - word[j])) % 12) + 12) % 12;
    sum = sum.add(Cyclotomic.zeta(ring, dir));
  }
  return sum.key() === zeroKey;
}

/**
 * The complete finite set of convex unit-edge tiles on the 30° grid, as canonical angle-words.
 *
 * For each side count n (3..12), recursively build words over {2,3,4,5} with running-sum
 * pruning (never brute-force 4^n), keep those whose interior-angle units sum to (n−2)·6 AND
 * close exactly, dedup by dihedral canonical form (Polyform.canonicalCyclicWord), and drop the
 * four bare regulars (triangle/square/hexagon/dodecagon). Returned sorted by length then
 * lexicographically. Validated against a Python prototype: exactly 11 tiles.
 */
export function enumerateConvexFamily(ring: CyclotomicRing): number[][] {
  const zeroKey = Cyclotomic.fromRational(ring, 0n).key();
  const bareKeys = new Set(
    [[2, 2, 2], [3, 3, 3, 3], new Array<number>(6).fill(4), new Array<number>(12).fill(5)]
      .map(w => Polyform.canonicalCyclicWord(w).join(',')),
  );

  const found = new Map<string, number[]>(); // canonical join → canonical word

  for (let n = 3; n <= 12; n++) {
    const target = (n - 2) * 6;
    const word = new Array<number>(n);

    const recurse = (pos: number, partial: number): void => {
      const remaining = n - pos;
      // Two-sided running-sum prune: each remaining corner adds 2..5 units.
      if (partial + remaining * 2 > target) return; // even all-minimum overshoots
      if (partial + remaining * 5 < target) return; // even all-maximum undershoots
      if (pos === n) {
        // partial === target guaranteed by the prunes above (remaining === 0)
        if (!closes(word, ring, zeroKey)) return;
        const canon = Polyform.canonicalCyclicWord(word);
        const keyStr = canon.join(',');
        if (bareKeys.has(keyStr)) return;
        if (!found.has(keyStr)) found.set(keyStr, canon);
        return;
      }
      for (const a of ANGLE_UNITS) {
        word[pos] = a;
        recurse(pos + 1, partial + a);
      }
    };

    recurse(0, 0);
  }

  return [...found.values()].sort((a, b) => {
    if (a.length !== b.length) return a.length - b.length;
    for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return a[i] - b[i];
    return 0;
  });
}
