#!/usr/bin/env python3
"""Does the drawn/undrawn EDGE-TYPE search reproduce freedraw, on any LATTICE grid?

check_marked_square.py answered that for the square grid and hardcoded it: two edge directions, the
8-element point group of Z^2, and `p + (1,0)` / `p + (0,1)` written out by hand. This is the same
referee with the lattice as a parameter, so the triangular grid — three directions, a 12-element
point group — takes no new code. It reproduces check_marked_square's numbers exactly on `square`,
which is the regression that licenses trusting it on `triangle`.

Canonical form. A pattern is a subset of the edges of a lattice L0, periodic under a sublattice L.
Two patterns are the same iff one maps to the other under a symmetry of L0 — a point-group element
composed with a translation. So: for each point-group element g, push L and the drawn set through g,
put gL in Hermite normal form {(a,0), (b,d)}, and read one bit per direction off each of the a*d
translation representatives; the lexicographic minimum over all |G| * a * d readings is the
invariant. Exact, finite, no window and no tolerance.

freedraw DEFINES a pattern to have no vertex of degree 1 (a dangling edge is a dead end, "a maze,
not a tiling"), while the search knows nothing about that and enumerates dangling edges happily.
They are filtered here and counted, because how many there are is itself worth knowing.

  python3 check_marked_grid.py --grid triangle --cells fdtri-k3.json \
      --oracle ../../public/freedraw/tri-solutions.json
"""
import argparse
import json
from math import sqrt

# ---------------------------------------------------------------- grids
# Each grid names, in LATTICE coordinates (integer pairs over the basis below):
#   basis  the two basis vectors in the Cartesian plane, for reading a developed pattern back
#   dirs   the edge directions out of a lattice point, one per bit plane; the oracle's h/v/w order
#   group  the point group as 2x2 integer matrices (a, b; c, d) acting on lattice coordinates
#
# SQUARE: basis is orthonormal, dirs are +x and +y, group is the 8 signed permutations.
# TRIANGLE: e1 and e2 at 60 degrees, so the third edge direction out of a point is e1 - e2. A
# rotation by 60 degrees sends e1 -> e2 and e2 -> e2 - e1; reflection in the e1 axis sends e1 -> e1
# and e2 -> e1 - e2. Those two generate the 12-element hexagonal point group.
SQUARE_GROUP = [
    (1, 0, 0, 1), (0, -1, 1, 0), (-1, 0, 0, -1), (0, 1, -1, 0),      # rotations
    (1, 0, 0, -1), (-1, 0, 0, 1), (0, 1, 1, 0), (0, -1, -1, 0),      # reflections
]


def _matmul(g, h):
    a, b, c, d = g
    e, f, i, j = h
    return (a * e + b * i, a * f + b * j, c * e + d * i, c * f + d * j)


def _gen_group(gens):
    G = {(1, 0, 0, 1)}
    while True:
        new = {_matmul(g, h) for g in G for h in gens} - G
        if not new:
            return sorted(G)
        G |= new


GRIDS = {
    "square": {
        "basis": ((1.0, 0.0), (0.0, 1.0)),
        "dirs": ((1, 0), (0, 1)),
        "names": ("h", "v"),
        "group": SQUARE_GROUP,
    },
    "triangle": {
        "basis": ((1.0, 0.0), (0.5, sqrt(3) / 2)),
        "dirs": ((1, 0), (0, 1), (1, -1)),
        "names": ("h", "v", "w"),
        "group": _gen_group([(0, -1, 1, 1), (1, 1, 0, -1)]),
    },
    # HEX is read on its DUAL. The vertices of {6,3} are not a lattice (a honeycomb is two thirds of
    # one), but the hexagon CENTRES are a triangular lattice, and every edge of {6,3} crosses exactly
    # one edge of it — so a drawn-edge set on the hex grid is a drawn-edge set on the triangular
    # lattice of centres, and the whole apparatus above applies unchanged. The two centres of a hex
    # edge are its midpoint offset by +-sqrt(3)/2 along the edge's normal.
    #
    # A hex-grid VERTEX is where three hexagons meet, i.e. a triangle of the dual, so "no vertex of
    # degree 1" becomes "no lattice triangle with exactly one drawn edge". Each cell carries two
    # triangles, listed as (offset, direction) triples in `triangles`.
    "hex": {
        "basis": ((1.5, sqrt(3) / 2), (0.0, sqrt(3))),   # centre lattice, edge-1 hexagons
        "dirs": ((1, 0), (0, 1), (1, -1)),
        "names": ("h", "v", "w"),
        "group": _gen_group([(0, -1, 1, 1), (1, 1, 0, -1)]),
        "dual": True,
        "triangles": [(((0, 0), 0), ((0, 0), 1), ((0, 1), 2)),
                      (((1, 0), 1), ((0, 1), 0), ((0, 1), 2))],
    },
}


def apply(g, p):
    a, b, c, d = g
    return (a * p[0] + b * p[1], c * p[0] + d * p[1])


def _egcd(x, y):
    if y == 0:
        return (abs(x), 1 if x >= 0 else -1, 0)
    g, s, t = _egcd(y, x % y)
    return (g, t, s - (x // y) * t)


def hnf_list(vecs):
    """Basis {(a,0), (b,d)} of the lattice generated by the given integer vectors, with a, d > 0 and
    0 <= b < a. d is the least positive second coordinate in the lattice; a generates the y=0 layer."""
    vecs = [v for v in vecs if v != (0, 0)]
    w = None
    for v in vecs:
        if v[1] == 0:
            continue
        if w is None:
            w = v if v[1] > 0 else (-v[0], -v[1])
        else:
            g, s, t = _egcd(w[1], v[1])
            w = (s * w[0] + t * v[0], g)
    if w is None or w[1] == 0:
        raise ValueError("degenerate lattice (rank < 2)")
    d = w[1]
    a = 0
    for v in vecs:
        q = v[1] // d
        if q * d != v[1]:
            raise ValueError("second coordinate not divisible")
        r = v[0] - q * w[0]
        a = _egcd(a, r)[0] if a else abs(r)
    if a == 0:
        raise ValueError("degenerate lattice (rank < 2)")
    return (a, w[0] % a, d)


def hnf(T1, T2):
    return hnf_list([T1, T2])


def coset(a, b, d, x, y):
    q = y // d
    j = y - q * d
    i = (x - q * b) % a
    return j * a + i


def table(edges, T1, T2, nd):
    """Bit planes over the period lattice, on the SMALLEST lattice that already fixes the drawing.

    The developed period is whatever the solver's fundamental domain happened to be, which can be a
    proper multiple of the pattern's own period; reading a bitmask off a doubled cell produces a
    string no other presentation of the same pattern will ever produce. So build the planes on the
    developed lattice, find every translation of that cell that fixes the drawing, and rebuild on
    the lattice those translations generate.
    """
    a, b, d = hnf(T1, T2)
    n = a * d
    P = [[0] * n for _ in range(nd)]
    for (x, y, dr) in edges:
        P[dr][coset(a, b, d, x, y)] = 1
    fixing = [(tx, ty) for ty in range(d) for tx in range(a)
              if all(P[r][coset(a, b, d, i, j)] == P[r][coset(a, b, d, i + tx, j + ty)]
                     for r in range(nd) for j in range(d) for i in range(a))]
    a2, b2, d2 = hnf_list([(a, 0), (b, d)] + fixing)
    if (a2, b2, d2) == (a, b, d):
        return a, b, d, P
    P2 = [[0] * (a2 * d2) for _ in range(nd)]
    for j in range(d):
        for i in range(a):
            for r in range(nd):
                P2[r][coset(a2, b2, d2, i, j)] = P[r][coset(a, b, d, i, j)]
    return a2, b2, d2, P2


def _image(dirs, g, t, x, y, dr):
    """Where the edge (x, y, dr) lands under v -> g v + t, as a (base point, direction) pair.

    g permutes the edge directions up to sign, so the image is one of the dirs traversed forwards or
    backwards; a backwards traversal is the same edge based at the other end.
    """
    P = apply(g, (x, y))
    Q = apply(g, (x + dirs[dr][0], y + dirs[dr][1]))
    P = (P[0] + t[0], P[1] + t[1])
    Q = (Q[0] + t[0], Q[1] + t[1])
    delta = (Q[0] - P[0], Q[1] - P[1])
    for r, dv in enumerate(dirs):
        if delta == dv:
            return P, r
        if delta == (-dv[0], -dv[1]):
            return Q, r
    raise ValueError("point-group element does not permute the edge directions: %r" % (delta,))


def canonical(grid, edges, T1, T2):
    dirs, group = grid["dirs"], grid["group"]
    nd = len(dirs)
    a, b, d, P = table(edges, T1, T2, nd)
    reps = [(i, j, r) for j in range(d) for i in range(a) for r in range(nd)
            if P[r][coset(a, b, d, i, j)]]
    best = None
    for g in group:
        a2, b2, d2 = hnf_list([apply(g, (a, 0)), apply(g, (b, d))])
        P2 = [[0] * (a2 * d2) for _ in range(nd)]
        for (x, y, r) in reps:
            base, nr = _image(dirs, g, (0, 0), x, y, r)
            P2[nr][coset(a2, b2, d2, base[0], base[1])] = 1
        for oy in range(d2):
            for ox in range(a2):
                s = []
                for j in range(d2):
                    for i in range(a2):
                        c = coset(a2, b2, d2, i + ox, j + oy)
                        s.append("".join(str(P2[r][c]) for r in range(nd)))
                key = "%d/%d/%d/" % (a2, b2, d2) + "".join(s)
                if best is None or key < best:
                    best = key
    return best


def degrees(grid, edges, T1, T2):
    """Drawn-edge degree of every grid VERTEX, as a coset list. Reduce to cosets FIRST: a developed
    fundamental domain is a domain of the tiling's face keys, not a tidy a-by-d block of the plane,
    so the same edge coset can appear at two absolute positions, and counting the raw list turns a
    degree-1 dangling edge into a phantom degree-2.

    On a direct grid a vertex is a lattice point and its degree counts the 2*nd incident edges. On a
    DUAL grid (hex) a vertex is a lattice triangle, and its degree counts that triangle's three.
    """
    dirs = grid["dirs"]
    nd = len(dirs)
    a, b, d, P = table(edges, T1, T2, nd)
    tris = grid.get("triangles")
    out = []
    for j in range(d):
        for i in range(a):
            if tris is None:
                c = coset(a, b, d, i, j)
                out.append(sum(P[r][c] + P[r][coset(a, b, d, i - dv[0], j - dv[1])]
                               for r, dv in enumerate(dirs)))
            else:
                for tri in tris:
                    out.append(sum(P[r][coset(a, b, d, i + o[0], j + o[1])] for (o, r) in tri))
    return out


def _to_lattice(grid, pt, shifted=True, origin=None):
    """Cartesian -> integer lattice coordinates over the grid's basis.

    `origin` shifts the reading. It matters only for a DUAL grid, whose lattice is the hexagon
    centres and so does not pass through 0; any centre will do, because they all differ by lattice
    vectors and the canonical form minimises over translations anyway. Taking one off the pattern
    beats hardcoding where develop happened to put the first hexagon.
    """
    ox, oy = ((origin if origin is not None else grid.get("origin", (0.0, 0.0)))
              if shifted else (0.0, 0.0))
    (e1x, e1y), (e2x, e2y) = grid["basis"]
    px, py = pt[0] - ox, pt[1] - oy
    det = e1x * e2y - e1y * e2x
    u = (px * e2y - py * e2x) / det
    v = (e1x * py - e1y * px) / det
    iu, iv = int(round(u)), int(round(v))
    if abs(u - iu) > 1e-3 or abs(v - iv) > 1e-3:   # the oracle patches ship 5 decimals
        raise ValueError("developed point %r is not on the grid (lattice coords %r)" % (pt, (u, v)))
    return iu, iv


def _dual_endpoints(p, q):
    """The two hexagon centres flanking the hex edge p--q: its midpoint, offset by +-sqrt(3)/2 along
    the edge normal. Unit edge length, so this is exact up to float rounding."""
    mx, my = (p[0] + q[0]) / 2.0, (p[1] + q[1]) / 2.0
    ux, uy = q[0] - p[0], q[1] - p[1]
    n = sqrt(ux * ux + uy * uy)
    nx, ny = -uy / n * (sqrt(3) / 2), ux / n * (sqrt(3) / 2)
    return (mx + nx, my + ny), (mx - nx, my - ny)


def edges_from_cells(grid, rec):
    dirs = grid["dirs"]
    dual = grid.get("dual", False)
    segs = [_dual_endpoints(p, q) if dual else (p, q) for (p, q) in rec["drawn"]]
    origin = segs[0][0] if (dual and segs) else None
    out = set()
    for (p, q) in segs:
        P, Q = _to_lattice(grid, p, True, origin), _to_lattice(grid, q, True, origin)
        delta = (Q[0] - P[0], Q[1] - P[1])
        for r, dv in enumerate(dirs):
            if delta == dv:
                out.add((P[0], P[1], r))
                break
            if delta == (-dv[0], -dv[1]):
                out.add((Q[0], Q[1], r))
                break
        else:
            raise ValueError("drawn segment is not a grid edge: %r %r" % (p, q))
    return out


def lattice_period(grid, rec):
    # A period is a VECTOR, so the grid's origin offset does not apply to it.
    return _to_lattice(grid, rec["T1"], False), _to_lattice(grid, rec["T2"], False)


def edges_from_oracle(grid, rec):
    """The oracle's own periodic drawn set, in this grid's lattice coordinates.

    Two shapes. Lattice grids (square, triangle) ship a bitmask indexed by lattice coset, in the same
    a/b/d Hermite basis used here. Patch grids (hex) ship explicit geometry — vertices, and edges as
    (from, to, dx, dy, drawn) with the endpoint translated by dx*T1 + dy*T2 — which comes back through
    exactly the same reader the developed cells take, dual mapping included.
    """
    patch = rec.get("patch")
    if patch is None:
        a, b, d = rec["a"], rec["b"], rec["d"]
        out = set()
        for j in range(d):
            for i in range(a):
                c = j * a + i
                for r, nm in enumerate(grid["names"]):
                    if rec[nm][c]:
                        out.add((i, j, r))
        return out, (a, 0), (b, d)
    T1, T2, V = patch["T1"], patch["T2"], patch["verts"]
    segs = []
    for (i, j, dx, dy, drawn) in patch["edges"]:
        if not drawn:
            continue
        p = V[i]
        q = (V[j][0] + dx * T1[0] + dy * T2[0], V[j][1] + dx * T1[1] + dy * T2[1])
        segs.append((p, q))
    edges = edges_from_cells(grid, {"drawn": segs})
    return edges, _to_lattice(grid, T1, False), _to_lattice(grid, T2, False)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--grid", default="square", choices=sorted(GRIDS))
    ap.add_argument("--cells", required=True)
    ap.add_argument("--oracle", required=True, nargs="+")
    ap.add_argument("--kmax", type=int, default=3)
    args = ap.parse_args()
    grid = GRIDS[args.grid]

    ours, dangling = {}, {}
    for rec in json.load(open(args.cells)):
        if rec["k"] > args.kmax:
            continue
        T1, T2 = lattice_period(grid, rec)
        edges = edges_from_cells(grid, rec)
        if 1 in degrees(grid, edges, T1, T2):
            dangling[rec["k"]] = dangling.get(rec["k"], 0) + 1
            continue
        ours.setdefault(rec["k"], {})[canonical(grid, edges, T1, T2)] = rec["id"]

    theirs = {}
    for rec in [r for f in args.oracle for r in json.load(open(f))]:
        if rec["k"] > args.kmax or rec.get("grid", "square") != args.grid:
            continue
        edges, T1, T2 = edges_from_oracle(grid, rec)
        theirs.setdefault(rec["k"], {})[canonical(grid, edges, T1, T2)] = rec["id"]

    print("k    search  dangling   distinct   freedraw   missing   extra")
    ok = True
    for k in range(1, args.kmax + 1):
        a, b = ours.get(k, {}), theirs.get(k, {})
        miss, extra = set(b) - set(a), set(a) - set(b)
        ok = ok and not miss and not extra
        print("%-4d %6d  %8d   %8d   %8d   %7d   %5d" %
              (k, len(a) + dangling.get(k, 0), dangling.get(k, 0), len(a), len(b), len(miss), len(extra)))
        for key in list(miss)[:3]:
            print("      MISSING  %s  (%s)" % (b[key][:24], key[:60]))
        for key in list(extra)[:3]:
            print("      EXTRA    %s  (%s)" % (a[key][:24], key[:60]))
    # Separate "we never found it" from "we found it and filed it under a different k". The second is
    # a disagreement about counting vertex orbits, not about which patterns exist.
    aU = {key: k for k in ours for key in ours[k]}
    bU = {key: k for k in theirs for key in theirs[k]}
    absent, invented = set(bU) - set(aU), set(aU) - set(bU)
    misk = {key for key in set(aU) & set(bU) if aU[key] != bU[key]}
    print()
    print("union over k <= %d:  search %d   freedraw %d   never found %d   not in freedraw %d   "
          "found at a different k %d" % (args.kmax, len(aU), len(bU), len(absent), len(invented), len(misk)))
    for key in sorted(misk)[:5]:
        print("      k %d here, %d there   %s" % (aU[key], bU[key], theirs[bU[key]][key]))
    print("VERDICT:", "MATCH — the edge-type search reproduces freedraw exactly" if ok else "MISMATCH")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
