#!/usr/bin/env python3
"""Does the drawn/undrawn EDGE-TYPE search reproduce freedraw on the square grid?

The test of Marek's proposal. `public/freedraw/solutions.json` holds 1420 square-grid freedraw
patterns at k <= 3 (13 / 153 / 1254), enumerated independently of this engine and already checked
bijectively against his own digon-alphabet solver by develop_freedraw.py. This script computes an
exact canonical form for every pattern on both sides and compares the two SETS, not the two counts.

Canonical form. A pattern is a subset of the edges of Z^2, periodic under a lattice L. Two patterns
are the same iff one maps to the other under a symmetry of the square lattice — the 8 elements of the
point group, composed with a translation. So: for each of the 8 elements g, push L and the drawn set
through g, put gL in Hermite normal form {(a,0), (b,d)}, and read the h/v bitmask off each of the a*d
translation representatives; the lexicographic minimum over all 8 * a * d readings is the invariant.
Exact, finite, no window and no tolerance.

One difference between the two objects has to be handled explicitly: freedraw DEFINES a pattern to
have no vertex of degree 1 (a dangling edge is a dead end, "a maze, not a tiling"), while the search
knows nothing about that and enumerates dangling edges happily. They are filtered here, and counted,
because how many there are is itself worth knowing.

  python3 check_marked_square.py --cells fdsq-cells.json --oracle ../../public/freedraw/solutions.json
"""
import argparse
import json
from math import gcd

# The 8 elements of the square lattice's point group, as 2x2 integer matrices (a, b; c, d).
POINTGROUP = [
    (1, 0, 0, 1), (0, -1, 1, 0), (-1, 0, 0, -1), (0, 1, -1, 0),      # rotations
    (1, 0, 0, -1), (-1, 0, 0, 1), (0, 1, 1, 0), (0, -1, -1, 0),      # reflections
]


def apply(g, p):
    a, b, c, d = g
    return (a * p[0] + b * p[1], c * p[0] + d * p[1])


def _egcd(x, y):
    if y == 0:
        return (abs(x), 1 if x >= 0 else -1, 0)
    g, s, t = _egcd(y, x % y)
    return (g, t, s - (x // y) * t)


def hnf_list(vecs):
    """Basis {(a,0), (b,d)} of the lattice generated by the given integer vectors, with a, d > 0 and
    0 <= b < a. d is the least positive second coordinate in the lattice; a generates the y=0 layer."""
    vecs = [v for v in vecs if v != (0, 0)]
    w = None
    for v in vecs:
        if v[1] == 0:
            continue
        if w is None:
            w = v if v[1] > 0 else (-v[0], -v[1])
        else:
            g, s, t = _egcd(w[1], v[1])
            w = (s * w[0] + t * v[0], g)
    if w is None or w[1] == 0:
        raise ValueError("degenerate lattice (rank < 2)")
    d = w[1]
    a = 0
    for v in vecs:
        a = gcd(a, abs(v[0] - (v[1] // d) * w[0]))
    if a == 0:
        raise ValueError("degenerate lattice (rank < 2)")
    return a, w[0] % a, d


def hnf(u, v):
    return hnf_list([u, v])


def table(edges, T1, T2):
    """(a, b, d, H, V) for the pattern, on its MINIMAL period lattice.

    The lattice a development hands back is the period of the LABELLED tiling — vertices carry their
    type — and that can be a proper sublattice of the period of the drawn figure itself, which is all
    the figure is. A 1-uniform pattern presented with two vertex types develops on a half-size lattice,
    and reading its bitmask off that cell produces a string no other presentation of the same pattern
    will ever produce. So: build the tables on the developed lattice, find every translation of that
    cell that fixes the drawing, and rebuild on the lattice those translations generate.
    """
    a, b, d = hnf(T1, T2)
    n = a * d
    H, V = [0] * n, [0] * n
    for (x, y, dr) in edges:
        (H if dr == 0 else V)[coset(a, b, d, x, y)] = 1
    fixing = [(tx, ty) for ty in range(d) for tx in range(a)
              if all(H[coset(a, b, d, i, j)] == H[coset(a, b, d, i + tx, j + ty)] and
                     V[coset(a, b, d, i, j)] == V[coset(a, b, d, i + tx, j + ty)]
                     for j in range(d) for i in range(a))]
    a2, b2, d2 = hnf_list([(a, 0), (b, d)] + fixing)
    if (a2, b2, d2) == (a, b, d):
        return a, b, d, H, V
    n2 = a2 * d2
    H2, V2 = [0] * n2, [0] * n2
    for j in range(d):
        for i in range(a):
            H2[coset(a2, b2, d2, i, j)] = H[coset(a, b, d, i, j)]
            V2[coset(a2, b2, d2, i, j)] = V[coset(a, b, d, i, j)]
    return a2, b2, d2, H2, V2


def coset(a, b, d, x, y):
    q = y // d
    j = y - q * d
    i = (x - q * b) % a
    return j * a + i


def _image(g, t, x, y, dr):
    """Where the unit edge (x, y, dr) lands under v -> g v + t, as a (base point, direction) pair."""
    P = apply(g, (x, y))
    Q = apply(g, (x + 1, y) if dr == 0 else (x, y + 1))
    P = (P[0] + t[0], P[1] + t[1])
    Q = (Q[0] + t[0], Q[1] + t[1])
    dx, dy = Q[0] - P[0], Q[1] - P[1]
    return (P if (dx == 1 or dy == 1) else Q), (0 if dx else 1)


def canonical(edges, T1, T2):
    """edges: set of (x, y, dir), dir 0 = the unit edge east from (x,y), 1 = north. Coordinates are
    representatives; the set is read modulo the lattice generated by T1 and T2."""
    a, b, d, H, V = table(edges, T1, T2)
    reps = [(i, j, dr) for j in range(d) for i in range(a) for dr in (0, 1)
            if (H if dr == 0 else V)[coset(a, b, d, i, j)]]
    best = None
    for g in POINTGROUP:
        a2, b2, d2 = hnf_list([apply(g, (a, 0)), apply(g, (b, d))])
        n2 = a2 * d2
        H2, V2 = [0] * n2, [0] * n2
        for (x, y, dr) in reps:
            base, nd = _image(g, (0, 0), x, y, dr)
            (H2 if nd == 0 else V2)[coset(a2, b2, d2, base[0], base[1])] = 1
        for oy in range(d2):
            for ox in range(a2):
                s = []
                for j in range(d2):
                    for i in range(a2):
                        c = coset(a2, b2, d2, i + ox, j + oy)
                        s.append("%d%d" % (H2[c], V2[c]))
                key = "%d/%d/%d/" % (a2, b2, d2) + "".join(s)
                if best is None or key < best:
                    best = key
    return best


def degrees(edges, T1, T2):
    """Drawn-edge degree of every grid-point coset.

    Reduce to cosets FIRST. A developed fundamental domain is a domain of the tiling's face keys, not
    a tidy a-by-d block of the plane, so the same edge coset can appear at two absolute positions —
    counting the raw list turns a degree-1 dangling edge into a phantom degree-2 and lets it through
    the filter that is supposed to remove it.
    """
    a, b, d, H, V = table(edges, T1, T2)
    deg = [0] * (a * d)
    for j in range(d):
        for i in range(a):
            c = coset(a, b, d, i, j)
            deg[c] = (H[c] + V[c]
                      + H[coset(a, b, d, i - 1, j)] + V[coset(a, b, d, i, j - 1)])
    return deg


def orbit_count(edges, T1, T2):
    """k computed from the geometry alone: the number of grid-point orbits under the symmetry group
    of the drawn pattern. An independent referee for the two enumerations' k.

    Every isometry that maps the square grid to itself is x -> r x + t with r in the 8-element point
    group and t an integer vector (a 90-degree rotation about a cell centre, or a reflection in the
    line x = 1/2, are both of that form), so the group modulo the period lattice is a finite set to
    test one element at a time.
    """
    a, b, d, H, V = table(edges, T1, T2)
    n = a * d

    def drawn(x, y, dr):
        return (H if dr == 0 else V)[coset(a, b, d, x, y)]

    image_edge = _image
    group = []
    for g in POINTGROUP:
        # r must preserve the period lattice, else it cannot be a symmetry of a pattern with that lattice
        gT1, gT2 = apply(g, (a, 0)), apply(g, (b, d))
        try:
            if hnf(gT1, gT2) != (a, b, d):
                continue
        except ValueError:
            continue
        for ty in range(d):
            for tx in range(a):
                t = (tx, ty)
                good = True
                for j in range(d):
                    for i in range(a):
                        for dr in (0, 1):
                            base, ndr = image_edge(g, t, i, j, dr)
                            if drawn(i, j, dr) != drawn(base[0], base[1], ndr):
                                good = False
                                break
                        if not good:
                            break
                    if not good:
                        break
                if good:
                    group.append((g, t))
    parent = list(range(n))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for (g, t) in group:
        for j in range(d):
            for i in range(a):
                p = apply(g, (i, j))
                c1, c2 = coset(a, b, d, i, j), coset(a, b, d, p[0] + t[0], p[1] + t[1])
                r1, r2 = find(c1), find(c2)
                if r1 != r2:
                    parent[max(r1, r2)] = min(r1, r2)
    return len({find(c) for c in range(n)})


def edges_from_cells(rec):
    """Developed drawn segments -> (x, y, dir) triples. Every step is axis-aligned and unit length on
    this board, which is asserted rather than assumed."""
    out = set()
    for (p, q) in rec["drawn"]:
        px, py = int(round(p[0])), int(round(p[1]))
        qx, qy = int(round(q[0])), int(round(q[1]))
        if abs(p[0] - px) > 1e-6 or abs(q[0] - qx) > 1e-6 or abs(p[1] - py) > 1e-6 or abs(q[1] - qy) > 1e-6:
            raise ValueError("drawn segment is not on the integer grid: %r %r" % (p, q))
        dx, dy = qx - px, qy - py
        if (abs(dx), abs(dy)) not in ((1, 0), (0, 1)):
            raise ValueError("drawn segment is not a unit grid edge: %r %r" % (p, q))
        if dx == -1 or dy == -1:
            px, py = qx, qy
        out.add((px, py, 0 if dx else 1))
    return out


def edges_from_oracle(rec):
    a, b, d = rec["a"], rec["b"], rec["d"]
    out = set()
    for j in range(d):
        for i in range(a):
            c = j * a + i
            if rec["h"][c]:
                out.add((i, j, 0))
            if rec["v"][c]:
                out.add((i, j, 1))
    return out, (a, 0), (b, d)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cells", required=True)
    ap.add_argument("--oracle", required=True)
    ap.add_argument("--kmax", type=int, default=3)
    args = ap.parse_args()

    ours = {}
    dangling = {}
    for rec in json.load(open(args.cells)):
        if rec["k"] > args.kmax:
            continue
        T1 = (int(round(rec["T1"][0])), int(round(rec["T1"][1])))
        T2 = (int(round(rec["T2"][0])), int(round(rec["T2"][1])))
        edges = edges_from_cells(rec)
        if 1 in degrees(edges, T1, T2):
            dangling[rec["k"]] = dangling.get(rec["k"], 0) + 1
            continue
        ours.setdefault(rec["k"], {})[canonical(edges, T1, T2)] = rec["id"]

    theirs = {}
    for rec in json.load(open(args.oracle)):
        if rec["k"] > args.kmax or rec.get("grid", "square") != "square":
            continue
        edges, T1, T2 = edges_from_oracle(rec)
        theirs.setdefault(rec["k"], {})[canonical(edges, T1, T2)] = rec["id"]

    print("k    search  dangling   distinct   freedraw   missing   extra")
    ok = True
    for k in range(1, args.kmax + 1):
        a, b = ours.get(k, {}), theirs.get(k, {})
        miss = set(b) - set(a)
        extra = set(a) - set(b)
        ok = ok and not miss and not extra
        print("%-4d %6d  %8d   %8d   %8d   %7d   %5d" %
              (k, len(a) + dangling.get(k, 0), dangling.get(k, 0), len(a), len(b), len(miss), len(extra)))
        for key in list(miss)[:3]:
            print("      MISSING  %s  (%s)" % (b[key][:24], key[:60]))
        for key in list(extra)[:3]:
            print("      EXTRA    %s  (%s)" % (a[key][:24], key[:60]))
    # Separate "we never found it" from "we found it and filed it under a different k". The second is
    # a disagreement about counting vertex orbits, not about which patterns exist, and the two need
    # different fixes, so never report them as one number.
    aU = {key: k for k in ours for key in ours[k]}
    bU = {key: k for k in theirs for key in theirs[k]}
    absent = set(bU) - set(aU)
    invented = set(aU) - set(bU)
    misk = {key for key in set(aU) & set(bU) if aU[key] != bU[key]}
    print()
    print("union over k <= %d:  search %d   freedraw %d   never found %d   not in freedraw %d   found at a different k %d"
          % (args.kmax, len(aU), len(bU), len(absent), len(invented), len(misk)))
    for key in sorted(misk)[:5]:
        print("      k %d here, %d there   %s" % (aU[key], bU[key], theirs[bU[key]][key]))
    print("VERDICT:", "MATCH — the edge-type search reproduces freedraw exactly" if ok else "MISMATCH")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
