#!/usr/bin/env python3
"""Develop Marek Čtrnáct's decoded k-uniform quotient half-edge structures into EXACT period cells
{T1,T2,Seed} in ℤ[ζ₁₂], matching TilingAtlas's Galebach oracle format.

Reads work/out/pruned/eupruned_<NN>_*.txt (NN = 01..kmax), reuses work/pruner.py's decode() to get
the folded quotient arrays (rneig,lneig,mirro,lvert,glue,label), unfolds each tiling by a developing
BFS in exact ℤ[ζ₁₂] arithmetic, extracts the translation lattice Λ = <T1,T2> from wrap-around
periods, and emits one vertex representative per Λ-orbit as Seed.

Output: work/ctrnact-cells-k<MAX>.json = array of {id,k,T1,T2,Seed}. Validate with
  pnpm tsx scripts/ctrnact-recon-check.ts <json>

Deterministic. Float is used ONLY for lattice reduction / coincidence tests, never to snap positions
(ℤ[ζ₁₂] is dense in ℂ). All emitted coords accumulate exactly as sums of ζ^k.
"""
import os, sys, glob, json, argparse, cmath, math
from collections import deque

# ----------------------------------------------------------------------------- exact ℤ[ζ₁₂]
# element = (a,b,c,d) = a + b·ζ + c·ζ² + d·ζ³, ζ = ζ₁₂ = e^{iπ/6}, min poly ζ⁴ = ζ² − 1.
def zmul_zeta(v):
    a, b, c, d = v
    return (-d, a, b + d, c)  # ζ·(a+bζ+cζ²+dζ³) = −d + aζ + (b+d)ζ² + cζ³

def zpow(k):
    v = (1, 0, 0, 0)
    for _ in range(k % 12):
        v = zmul_zeta(v)
    return v

ZK = [zpow(k) for k in range(12)]          # unit edge in direction k·30°
ZERO = (0, 0, 0, 0)

def zadd(u, v):
    return (u[0] + v[0], u[1] + v[1], u[2] + v[2], u[3] + v[3])

def zsub(u, v):
    return (u[0] - v[0], u[1] - v[1], u[2] - v[2], u[3] - v[3])

def zscale(u, m):
    return (u[0] * m, u[1] * m, u[2] * m, u[3] * m)

_E = cmath.exp(1j * math.pi / 6)
_EP = [_E ** k for k in range(4)]
def zfloat(v):
    return v[0] * _EP[0] + v[1] * _EP[1] + v[2] * _EP[2] + v[3] * _EP[3]

def angunits(n):
    # interior angle of a regular n-gon in 30° units: 180−360/n = (6 − 12/n)·30°
    return 6 - 12 // n   # 3→2, 4→3, 6→4, 12→5

# ----------------------------------------------------------------------------- pruner import
# We reuse pruner.py's decode() only (folds a conway block into the quotient half-edge arrays);
# the dedup/O(n²) compare is never called here. pruner.py sits beside this file.
_HERE = os.path.dirname(os.path.abspath(__file__))
os.environ.setdefault("EU_KMIN", "1")
os.environ.setdefault("EU_KMAX", "0")   # empty driver range: import w/o processing files
os.environ.setdefault("EU_QUIET", "1")
os.environ.setdefault("EU_OUT", os.path.join(_HERE, "_import_scratch"))
import importlib.util
_spec = importlib.util.spec_from_file_location("pr", os.path.join(_HERE, "pruner.py"))
pr = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(pr)

# ----------------------------------------------------------------------------- block IO
def read_blocks(path):
    blocks, buf = [], []
    for raw in open(path):
        if raw.strip() == "":
            if buf:
                blocks.append(buf); buf = []
        else:
            buf.append(raw.rstrip("\n"))
    if buf:
        blocks.append(buf)
    return blocks

def tes_id(tes):
    parts = tes.split("/")
    nn_fam = parts[1]; filesig = parts[2]
    n = parts[3].rsplit(" ", 1)[1].replace(".tes", "")
    return "ctrnact-%s-%s-%s" % (nn_fam, filesig.replace(" ", "_"), n)

# ----------------------------------------------------------------------------- integer lattice
def egcd(a, b):
    old_r, r = a, b
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r != 0:
        q = old_r // r
        old_r, r = r, old_r - q * r
        old_s, s = s, old_s - q * s
        old_t, t = t, old_t - q * t
    if old_r < 0:
        old_r, old_s, old_t = -old_r, -old_s, -old_t
    return old_r, old_s, old_t  # g = a*old_s + b*old_t, g > 0

def lattice_basis(periods):
    """Integer HNF-style basis of the ℤ-submodule of ℤ⁴ generated by the period 4-vectors.
    Returns list of 4-int tuples (rank ≤ 2 for a real 2D translation lattice)."""
    piv = {}  # col -> pivot vector (list of 4 ints) with vector[col] != 0
    for v in periods:
        v = list(v)
        if not any(v):
            continue
        for col in range(4):
            if v[col] == 0:
                continue
            if col in piv:
                b = piv[col]
                g, x, y = egcd(b[col], v[col])
                nb = [x * b[i] + y * v[i] for i in range(4)]      # pivot becomes g
                bc = b[col] // g; vc = v[col] // g
                nv = [bc * v[i] - vc * b[i] for i in range(4)]    # kills v[col]
                piv[col] = nb
                v = nv
            else:
                piv[col] = v
                v = [0, 0, 0, 0]
                break
    return [tuple(piv[c]) for c in sorted(piv)]

def _dot(u, v):
    a = zfloat(u); b = zfloat(v)
    return a.real * b.real + a.imag * b.imag

def gauss_reduce(T1, T2):
    """Lagrange–Gauss 2D lattice reduction. Exact ℤ[ζ₁₂] coords; reduction coeff m is a rounded
    float inner-product ratio (integer), so every subtraction stays exact. Returns the shortest basis."""
    a, b = tuple(T1), tuple(T2)
    for _ in range(1000):
        if _dot(b, b) < _dot(a, a):
            a, b = b, a
        da = _dot(a, a)
        if da == 0:
            break
        m = int(round(_dot(b, a) / da))
        if m == 0:
            break
        b = zsub(b, zscale(a, m))
    if _dot(b, b) < _dot(a, a):
        a, b = b, a
    return a, b

# ----------------------------------------------------------------------------- developer
class DevelopError(Exception):
    pass

def develop(rneig, lneig, mirro, lvert, glue, label, sign=1):
    """Flood-fill develop. Returns (T1, T2, seeds, diag). Raises DevelopError on inconsistency."""
    n_he = len(rneig)

    def star(h0, d0):
        """All half-edge instances around the vertex of (h0,d0), as (h,dir), in cyclic order,
        by unfolding rneig and accumulating interior angles until back to (h0,d0)=360°."""
        seq = []
        cur, d = h0, d0
        for _ in range(60):
            seq.append((cur, d))
            r = rneig[cur]
            d = (d + sign * angunits(lvert[r])) % 12
            cur = r
            if (cur, d) == (h0, d0):
                return seq
        raise DevelopError("star did not close within 60 steps")

    placed = {}     # (h,dir) -> pos (exact tuple)
    periods = []
    expanded = set()  # vertex positions already expanded

    def reg(h, d, pos):
        key = (h, d)
        prev = placed.get(key)
        if prev is not None:
            if prev != pos:
                periods.append(zsub(pos, prev))
            return False
        placed[key] = pos
        return True

    reg(0, 0, ZERO)
    q = deque([(0, 0, ZERO)])
    guard = 0
    while q:
        guard += 1
        if guard > 200000:
            raise DevelopError("BFS did not terminate (200k pops)")
        h0, d0, pos = q.popleft()
        if pos in expanded:
            continue
        expanded.add(pos)
        for (h, d) in star(h0, d0):
            reg(h, d, pos)                      # all star members share this vertex pos
            g = glue[h]; gd = (d + 6) % 12
            npos = zadd(pos, ZK[d])
            if reg(g, gd, npos):
                q.append((g, gd, npos))

    if not periods:
        raise DevelopError("no periods found (tiling did not wrap)")
    basis = lattice_basis(periods)
    if len(basis) != 2:
        raise DevelopError("lattice rank %d != 2" % len(basis))
    # Gauss-reduce so the emitted basis is short: the gate reconstructs stars only inside a small
    # window around the reduced basis, so a skewed basis strands vertices at the window edge and
    # drops face classes. Λ is unchanged (reduction = integer basis change).
    T1, T2 = gauss_reduce(basis[0], basis[1])

    seeds = seeds_mod_lattice([p for p in placed.values()], T1, T2)
    diag = {
        "n_he": n_he,
        "n_vertices_dev": len(expanded),
        "n_placed": len(placed),
        "n_periods": len(periods),
        "n_seeds": len(seeds),
    }
    return T1, T2, seeds, diag

def _lattice_coords(pos, T1, T2):
    """Float (alpha,beta) with pos ≈ alpha·T1 + beta·T2 (2×2 solve in ℂ→ℝ²)."""
    p = zfloat(pos); a = zfloat(T1); b = zfloat(T2)
    det = a.real * b.imag - a.imag * b.real
    alpha = (p.real * b.imag - p.imag * b.real) / det
    beta = (a.real * p.imag - a.imag * p.real) / det
    return alpha, beta

def seeds_mod_lattice(positions, T1, T2):
    """Distinct vertex positions modulo Λ = <T1,T2>, each reduced into the base cell. Exact."""
    seen = {}
    for pos in positions:
        alpha, beta = _lattice_coords(pos, T1, T2)
        m = math.floor(alpha + 1e-9)
        nn = math.floor(beta + 1e-9)
        red = zsub(zsub(pos, zscale(T1, m)), zscale(T2, nn))
        seen[red] = red
    # deterministic order
    return sorted(seen.keys())

# ----------------------------------------------------------------------------- driver
def process_block(b, sign):
    tes = [l for l in b if l.startswith("TES file:")][0].split(":", 1)[1].strip()
    tid = tes_id(tes)
    pr.decode(b[0] + "\n", b[1] + "\n", b[3] + "\n", b[4] + "\n")
    k = b[0].count("(")
    T1, T2, seeds, diag = develop(pr.rneig, pr.lneig, pr.mirro, pr.lvert, pr.glue, pr.label, sign=sign)
    return {
        "id": tid,
        "k": k,
        "T1": list(T1),
        "T2": list(T2),
        "Seed": [list(s) for s in seeds],
    }, diag

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--kmax", type=int, default=8)
    ap.add_argument("--kmin", type=int, default=1)
    ap.add_argument("--sign", type=int, default=1, choices=[1, -1])
    ap.add_argument("--pruned", default="work/out/pruned")
    ap.add_argument("--out", default=None)
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    out = args.out or ("work/ctrnact-cells-k%d.json" % args.kmax)
    records = []
    errors = []
    for k in range(args.kmin, args.kmax + 1):
        # family files (eupruned_NN_fam.txt) AND streamed single files (eupruned_NN.txt / eupruned_N.txt)
        cand = set(glob.glob(os.path.join(args.pruned, "eupruned_%02d_*.txt" % k)))
        cand |= set(glob.glob(os.path.join(args.pruned, "eupruned_%d_*.txt" % k)))
        cand.add(os.path.join(args.pruned, "eupruned_%02d.txt" % k))
        cand.add(os.path.join(args.pruned, "eupruned_%d.txt" % k))
        for f in sorted(p for p in cand if os.path.exists(p)):
            for b in read_blocks(f):
                tes = [l for l in b if l.startswith("TES file:")]
                if not tes:
                    continue
                tid = tes_id(tes[0].split(":", 1)[1].strip())
                try:
                    rec, diag = process_block(b, args.sign)
                    records.append(rec)
                    if args.verbose:
                        print("  ok  %-32s seeds=%d periods=%d" % (rec["id"], diag["n_seeds"], diag["n_periods"]))
                except Exception as e:
                    errors.append({"id": tid, "k": k, "error": "%s: %s" % (type(e).__name__, e)})
                    print("  ERR %-32s %s" % (tid, e), file=sys.stderr)

    records.sort(key=lambda r: (r["k"], r["id"]))
    with open(out, "w") as fh:
        json.dump(records, fh)
    per_k = {}
    for r in records:
        per_k[r["k"]] = per_k.get(r["k"], 0) + 1
    print("developed %d tilings -> %s" % (len(records), out))
    for k in sorted(per_k):
        print("  k=%d : %d" % (k, per_k[k]))
    if errors:
        print("DEVELOP ERRORS (%d):" % len(errors), file=sys.stderr)
        for e in errors[:40]:
            print("  %s (k%d): %s" % (e["id"], e["k"], e["error"]), file=sys.stderr)

if __name__ == "__main__":
    main()
