#!/usr/bin/env python3
"""emit_length_meta.py — k and the length-parameter count for every parametric-length family.

Both numbers were being computed in TypeScript, by `lib/tilings/vertex-orbits.ts` and
`lib/tilings/length-system.ts` (a file that never existed), which were re-implementations of this
directory's map machinery. This computes them here, once, and the Atlas reads the result — one
definition per question, in the language where the rest of the tiling mathematics already lives.

Each is measured where it MEANS something, and the two places are different:

    k        at the family's DEFAULT sliders — that is the member the shelf card draws, and k drops on
             the measure-zero subsets where an extra symmetry appears (all shifts 1/2, say).
    params   at a GENERIC point — regularity read at a symmetric member is not the family's constraint
             (at A = B = C an equiangular hexagon is equilateral, and calling it regular there reports
             a 3-parameter family as rigid).
    key      at a GENERIC point, for the same reason twice over: at a symmetric member two distinct
             edges coincide and a primitive cell can look like a supercell, so `build_map` reduces a
             2-parameter family onto a 1-parameter one and two different families key alike.

`key` is the canonical dart map of the SMOOTHED tiling (`tiling_key.smooth` deletes the points that are
a corner of no tile) together with its corner angles, and it is what `length-families.ts` deduplicates
the shelf on. Angles are fixed across a length family, so the map plus the angles determines the cone:
two rows share a key exactly when they are the same family. Four sources feed that shelf and three of
them rediscover each other, which is why the check has to exist at all.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import length_family as LF
import tiling_key as TK
import vertex_orbits as vo

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
SRC = os.path.join(ROOT, "experiments", "results", "length-cells.json")
OUT = os.path.join(ROOT, "lib", "tilings", "length-meta.generated.ts")

rows, bad = [], 0
for e in json.load(open(SRC)):
    polys, basis = vo.float_cell(e["renderCell"])
    dim, info = LF.freedom(polys, basis)
    if dim is None:
        print(f"  {e['id']}: no map ({info.get('reason')})")
        bad += 1
        continue
    # SMOOTH FIRST, then refine. `refine` promotes every T-junction to a vertex, including the ones
    # where every incident tile runs straight through — points that are a corner of nothing, whose
    # position is a free relabelling and not a parameter. `smooth` deletes exactly those.
    key = TK.family_key(TK.refine(TK.smooth(polys, basis), basis), basis)
    if key is None:
        print(f"  {e['id']}: no canonical key")
        bad += 1
        continue
    dpolys, dbasis = vo.float_cell(e.get("defaultCell", e["renderCell"]))
    # REFINE FIRST. orbit_count walks vertex figures, and on a non-edge-to-edge cell a tile's side that
    # a neighbour meets part-way along has no vertex there to walk from — the figure comes back empty and
    # the count is 0. Promoting the T-junctions is what makes the existing counter apply to this shelf.
    k = vo.orbit_count(TK.refine(TK.smooth(dpolys, dbasis), dbasis), dbasis)
    if isinstance(k, tuple):
        k = k[0]
    rows.append((e["id"], int(k), info, key))
    kts = e.get("kTs")
    flag = "" if kts is None or int(k) == int(kts) else f"   <<< TS said k={kts}"
    if flag:
        bad += 1
    print(f"  {e['id']:34s} k={k}  params={info['params']}  V={info['V']} E={info['E']} "
          f"F={info['F']} chi={info['euler']}{flag}")

seen = {}
for i, k, n, key in rows:
    seen.setdefault(key, []).append(i)
dups = {key: ids for key, ids in seen.items() if len(ids) > 1}
if dups:
    print(f"\n{sum(len(v) - 1 for v in dups.values())} rows are a family another row already has, "
          f"over {len(dups)} families — length-families.ts keeps the first of each:")
    for ids in sorted(dups.values(), key=len, reverse=True):
        print(f"  {ids[0]:24s} absorbs  {', '.join(ids[1:])}")

body = "\n".join(
    f'\t"{i}": {{ k: {k}, params: {n["params"]}, V: {n["V"]}, E: {n["E"]}, F: {n["F"]}, '
    f'key: {json.dumps(key)} }},'
    for i, k, n, key in rows)
with open(OUT, "w") as f:
    f.write(f'''// GENERATED by tools/ctrnact-oracle/emit_length_meta.py — do not edit by hand.
//
// k and the length-parameter count for every parametric-length family, computed by `vertex_orbits.py`
// and `length_family.py`. These were previously re-implemented in TypeScript; the Atlas now reads them
// instead of recomputing them, so there is one definition of each and no drift between two languages.
//
// Regenerate with:   pnpm tsx scripts/export-length-cells.ts
//                    python3 tools/ctrnact-oracle/emit_length_meta.py

export interface LengthMeta {{
\t/** Vertex orbits AT THE FAMILY'S DEFAULT SLIDERS — the member the shelf card draws. */
\tk: number;
\t/** Length parameters modulo scale, measured at a generic point of the box. */
\tparams: number;
\t/** Map counts of the SMOOTHED tiling per translational period; V - E + F = 0. */
\tV: number; E: number; F: number;
\t/** Canonical dart map + corner angles of the smoothed tiling at a GENERIC member. Two rows share
\t *  this exactly when they are the same family; `LENGTH_FAMILIES` keeps one row per value and the
\t *  survivor's note names the rows it absorbed. */
\tkey: string;
}}

export const LENGTH_META: Record<string, LengthMeta> = {{
{body}
}};
''')
print(f"\nwrote {OUT} ({len(rows)} families, {bad} failed)")
