// eu_develop — native C++ port of develop.py: pruned Čtrnáct combinatorial solutions → EXACT period
// cells {id,k,T1,T2,Seed} in ℤ[ζ₁₂] (ζ=ζ₁₂, min poly ζ⁴=ζ²−1), Galebach oracle format. Reuses the
// decode machinery already ported in eu_pruner.cpp (vertex-figure tables in pruner_tables.inc), adds
// the geometric developer (flood-fill in exact ℤ[ζ₁₂], integer lattice HNF, Lagrange-Gauss reduction,
// seeds mod Λ). Validated byte-for-byte against develop.py on the same pruned input (k≤13).
//
// Float is used ONLY for lattice reduction / coincidence tests, never to snap positions (ℤ[ζ₁₂] is
// dense in ℂ). To stay bit-identical to develop.py: banker's rounding (nearbyint, Python round()) for
// the reduction coefficient, floor division in egcd, lexicographic seed sort.
//
//   ./eu_develop --kmin 14 --kmax 16 --pruned <dir> --out cells.json   [--sign 1]
#include <cstdio>
#include <cstdint>
#include <cmath>
#include <cfenv>
#include <array>
#include <vector>
#include <string>
#include <deque>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <complex>
#include <fstream>
#include <sstream>
#include <filesystem>

using std::array;
using std::string;
using std::vector;
namespace fs = std::filesystem;

#include "ctrnact_decode.hpp" // shared decode + pruner_tables.inc + countsignature (also used by eu_pruner)

// ===================== exact ℤ[ζ₁₂] =====================
using Vec = array<int, 4>; // a + bζ + cζ² + dζ³
static inline Vec zmul_zeta(const Vec& v) { return {-v[3], v[0], v[1] + v[3], v[2]}; }
static inline Vec zadd(const Vec& u, const Vec& w) { return {u[0]+w[0], u[1]+w[1], u[2]+w[2], u[3]+w[3]}; }
static inline Vec zsub(const Vec& u, const Vec& w) { return {u[0]-w[0], u[1]-w[1], u[2]-w[2], u[3]-w[3]}; }
static inline Vec zscale(const Vec& u, long m) { return {(int)(u[0]*m), (int)(u[1]*m), (int)(u[2]*m), (int)(u[3]*m)}; }
static const Vec ZERO{0, 0, 0, 0};
static array<Vec, 12> makeZK() { array<Vec, 12> z; Vec v{1,0,0,0}; for (int k = 0; k < 12; k++) { z[k] = v; v = zmul_zeta(v); } return z; }
static const array<Vec, 12> ZK = makeZK();
static inline int angunits(int n) { return 6 - 12 / n; } // 3→2, 4→3, 6→4, 12→5

typedef std::complex<double> cd;
static const cd _E = std::exp(cd(0, M_PI / 6));
static array<cd, 4> makeEP() { array<cd, 4> e; cd v(1, 0); for (int k = 0; k < 4; k++) { e[k] = v; v *= _E; } return e; }
static const array<cd, 4> _EP = makeEP();
static inline cd zfloat(const Vec& v) { return (double)v[0]*_EP[0] + (double)v[1]*_EP[1] + (double)v[2]*_EP[2] + (double)v[3]*_EP[3]; }
static inline double zdot(const Vec& u, const Vec& w) { cd a = zfloat(u), b = zfloat(w); return a.real()*b.real() + a.imag()*b.imag(); }

struct VecHash { size_t operator()(const Vec& v) const { size_t h = 1469598103934665603ULL; for (int x : v) { h ^= (size_t)(uint32_t)x; h *= 1099511628211ULL; } return h; } };

// ===================== integer lattice =====================
static inline long ifloordiv(long a, long b) { long q = a / b; if ((a % b != 0) && ((a < 0) != (b < 0))) q--; return q; }
struct EG { long g, s, t; };
static EG egcd(long a, long b) {
	long old_r = a, r = b, old_s = 1, s = 0, old_t = 0, t = 1;
	while (r != 0) {
		long q = ifloordiv(old_r, r);
		long tr = old_r - q * r; old_r = r; r = tr;
		long ts = old_s - q * s; old_s = s; s = ts;
		long tt = old_t - q * t; old_t = t; t = tt;
	}
	if (old_r < 0) { old_r = -old_r; old_s = -old_s; old_t = -old_t; }
	return {old_r, old_s, old_t};
}
// Integer HNF-style basis of the ℤ-module generated by the period 4-vectors (faithful port).
static vector<Vec> lattice_basis(const vector<Vec>& periods) {
	std::map<int, array<long, 4>> piv;
	for (const auto& p0 : periods) {
		array<long, 4> v{p0[0], p0[1], p0[2], p0[3]};
		if (!(v[0] || v[1] || v[2] || v[3])) continue;
		for (int col = 0; col < 4; col++) {
			if (v[col] == 0) continue;
			auto it = piv.find(col);
			if (it != piv.end()) {
				array<long, 4>& b = it->second;
				EG e = egcd(b[col], v[col]);
				array<long, 4> nb, nv;
				long bc = b[col] / e.g, vc = v[col] / e.g;
				for (int i = 0; i < 4; i++) { nb[i] = e.s * b[i] + e.t * v[i]; nv[i] = bc * v[i] - vc * b[i]; }
				piv[col] = nb;
				v = nv;
			} else {
				piv[col] = v;
				v = {0, 0, 0, 0};
				break;
			}
		}
	}
	vector<Vec> out;
	for (auto& kv : piv) { auto& b = kv.second; out.push_back({(int)b[0], (int)b[1], (int)b[2], (int)b[3]}); }
	return out; // std::map iterates keys ascending == Python sorted(piv)
}
// Lagrange-Gauss 2D reduction; reduction coeff = banker's-rounded float ratio (Python round()).
static void gauss_reduce(Vec T1, Vec T2, Vec& ra, Vec& rb) {
	Vec a = T1, b = T2;
	for (int it = 0; it < 1000; it++) {
		if (zdot(b, b) < zdot(a, a)) { std::swap(a, b); }
		double da = zdot(a, a);
		if (da == 0) break;
		long m = (long)std::nearbyint(zdot(b, a) / da); // FE_TONEAREST default = round-half-to-even
		if (m == 0) break;
		b = zsub(b, zscale(a, m));
	}
	if (zdot(b, b) < zdot(a, a)) { std::swap(a, b); }
	ra = a; rb = b;
}
// Distinct vertex positions modulo Λ, reduced into the base cell, sorted lexicographically.
static vector<Vec> seeds_mod_lattice(const vector<Vec>& positions, const Vec& T1, const Vec& T2) {
	cd a = zfloat(T1), b = zfloat(T2);
	double det = a.real() * b.imag() - a.imag() * b.real();
	std::set<Vec> seen;
	for (const auto& pos : positions) {
		cd p = zfloat(pos);
		double alpha = (p.real() * b.imag() - p.imag() * b.real()) / det;
		double beta = (a.real() * p.imag() - a.imag() * p.real()) / det;
		long m = (long)std::floor(alpha + 1e-9);
		long nn = (long)std::floor(beta + 1e-9);
		Vec red = zsub(zsub(pos, zscale(T1, m)), zscale(T2, nn));
		seen.insert(red);
	}
	return vector<Vec>(seen.begin(), seen.end());
}

// ===================== developer =====================
struct Face { int tile; vector<Vec> verts; };  // one tile: index into TILE_NAME + boundary verts (exact ℤ[ζ₁₂])
struct DevResult { Vec T1, T2; vector<Vec> seeds; bool ok; string err; vector<Face> faces; bool areaOk = false; };

// Partition the DEVELOPED darts into faces (tiles). The quotient is symmetry-folded — a k=1 tiling can
// have a single self-looped dart — so each quotient dart h appears at many directions d; the geometric
// dart is the key (h*12+d) in `placed`. Face traversal is checkpart's walk (free → glue[rneig[free]])
// lifted to (h,d): from (h,d), rf=rneig[h] has direction d+sign·CLASS_UNITS[cls[rf]] (as in develop's
// star), then glue crosses the edge to (glue[rf], dir+6). Face corners = the free-dart positions; the
// face's tile = CLASS_TILE[cls[rf]] (constant over the face — condition 1, verified). Each geometric
// dart lies on exactly one face, so faces partition `placed` and Σ area = |det Λ| (the area cert).
// Doubled tiles work unchanged: flat corners are collinear verts the shoelace absorbs.
static void extractFaces(DevResult& res, const std::unordered_map<int, Vec>& placed,
                         const vector<int>& rneig, const vector<int>& cls, const vector<int>& glue,
                         int sign, const Vec& T1, const Vec& T2) {
	cd tA = zfloat(T1), tB = zfloat(T2);
	double detA = std::abs(tA.real() * tB.imag() - tA.imag() * tB.real());
	auto shoelace = [&](const vector<Vec>& vs) -> double {
		double A = 0; int n = (int)vs.size();
		for (int i = 0; i < n; i++) { cd p = zfloat(vs[i]), q = zfloat(vs[(i + 1) % n]); A += p.real() * q.imag() - p.imag() * q.real(); }
		return std::abs(A) / 2.0;
	};
	int n_darts = (int)rneig.size();
	std::unordered_set<int> seen;
	double areaSum = 0; bool ok = true;
	for (auto& kv : placed) {
		if (seen.count(kv.first)) continue;
		int h0 = kv.first / 12, d0 = kv.first % 12;
		vector<Vec> verts; int tile = -1;
		int h = h0, d = d0;
		Vec P = kv.second;                 // start at this dart's developed position; accumulate along edges
		for (int s = 0;; s++) {
			if (s > 64) { ok = false; break; }
			if (s > 0 && seen.count(h * 12 + d)) { ok = false; break; }
			seen.insert(h * 12 + d);
			verts.push_back(P);
			int rf = rneig[h]; if (rf < 0 || rf >= n_darts) { ok = false; break; }
			int t = CLASS_TILE[cls[rf]];
			if (tile < 0) tile = t; else if (t != tile) { ok = false; break; }
			int dr = (((d + sign * CLASS_UNITS[cls[rf]]) % 12) + 12) % 12;
			int nh = glue[rf]; if (nh < 0 || nh >= n_darts) { ok = false; break; }
			P = zadd(P, ZK[dr]);           // cross edge rf to the next corner (accumulate, don't look up)
			h = nh; d = (dr + 6) % 12;
			if (h == h0 && d == d0) break;
		}
		if (!ok) break;
		if (verts.size() < 3) { ok = false; break; }
		Face f; f.tile = tile; f.verts = std::move(verts);
		areaSum += shoelace(f.verts);
		res.faces.push_back(std::move(f));
	}
	res.areaOk = ok && std::abs(areaSum - detA) < 1e-6 * std::max(1.0, detA);
	if (std::getenv("EU_FACES_DEBUG"))
		std::fprintf(stderr, "    [faces] ok=%d areaSum=%.6f detΛ=%.6f nfaces=%zu\n", ok, areaSum, detA, res.faces.size());
}

static DevResult develop(const vector<int>& rneig, const vector<int>& cls,
                         const vector<int>& glue, int sign, bool wantFaces) {
	// Turn by the incident corner's true interior angle, read from its corner CLASS
	// (CLASS_UNITS[cls]) rather than derived from the polygon size (angunits(lvert)).
	// For the regular palette cls is bijective with lvert and CLASS_UNITS[cls]==angunits(n),
	// so this is byte-identical there; for doubled tiles it yields the correct per-corner
	// turn (real θ_N vs flat 180°), which angunits(lvert) cannot express.
	auto star = [&](int h0, int d0, vector<std::pair<int,int>>& seq) -> bool {
		seq.clear();
		int cur = h0, d = d0;
		for (int i = 0; i < 60; i++) {
			seq.push_back({cur, d});
			int r = rneig[cur];
			d = (((d + sign * CLASS_UNITS[cls[r]]) % 12) + 12) % 12;
			cur = r;
			if (cur == h0 && d == d0) return true;
		}
		return false;
	};
	std::unordered_map<int, Vec> placed;   // key h*12+d -> pos
	std::unordered_set<Vec, VecHash> expanded;
	vector<Vec> periods;
	auto reg = [&](int h, int d, const Vec& pos) -> bool {
		int key = h * 12 + d;
		auto it = placed.find(key);
		if (it != placed.end()) { if (it->second != pos) periods.push_back(zsub(pos, it->second)); return false; }
		placed[key] = pos;
		return true;
	};
	reg(0, 0, ZERO);
	std::deque<std::tuple<int,int,Vec>> q;
	q.push_back({0, 0, ZERO});
	long guard = 0;
	vector<std::pair<int,int>> seq;
	while (!q.empty()) {
		if (++guard > 200000) return {{}, {}, {}, false, "BFS did not terminate (200k pops)"};
		auto [h0, d0, pos] = q.front(); q.pop_front();
		if (expanded.count(pos)) continue;
		expanded.insert(pos);
		if (!star(h0, d0, seq)) return {{}, {}, {}, false, "star did not close within 60 steps"};
		for (auto [h, d] : seq) {
			reg(h, d, pos);
			int g = glue[h], gd = (d + 6) % 12;
			Vec npos = zadd(pos, ZK[d]);
			if (reg(g, gd, npos)) q.push_back({g, gd, npos});
		}
	}
	if (periods.empty()) return {{}, {}, {}, false, "no periods found (tiling did not wrap)"};
	vector<Vec> basis = lattice_basis(periods);
	if (basis.size() != 2) return {{}, {}, {}, false, "lattice rank " + std::to_string(basis.size()) + " != 2"};
	Vec T1, T2; gauss_reduce(basis[0], basis[1], T1, T2);
	vector<Vec> allpos; allpos.reserve(placed.size());
	for (auto& kv : placed) allpos.push_back(kv.second);
	vector<Vec> seeds = seeds_mod_lattice(allpos, T1, T2);
	DevResult res{T1, T2, seeds, true, ""};
	if (wantFaces) extractFaces(res, placed, rneig, cls, glue, sign, T1, T2);
	return res;
}

// ===================== block IO + driver =====================
static vector<vector<string>> read_blocks(std::istream& in) {
	vector<vector<string>> blocks; vector<string> buf; string raw;
	while (std::getline(in, raw)) {
		std::string s = raw; while (!s.empty() && (s.back()=='\r')) s.pop_back();
		std::string t = s; size_t a = t.find_first_not_of(" \t\r\n"); // strip() test
		if (a == std::string::npos) { if (!buf.empty()) { blocks.push_back(buf); buf.clear(); } }
		else buf.push_back(s);
	}
	if (!buf.empty()) blocks.push_back(buf);
	return blocks;
}
static string tes_id(const string& tes) {
	vector<string> parts; string cur; for (char c : tes) { if (c == '/') { parts.push_back(cur); cur.clear(); } else cur += c; } parts.push_back(cur);
	string nn_fam = parts[1], filesig = parts[2], last = parts[3];
	size_t sp = last.rfind(' ');
	string n = last.substr(sp + 1);
	size_t dot = n.rfind(".tes"); if (dot != std::string::npos) n = n.substr(0, dot);
	string fs2 = filesig; std::replace(fs2.begin(), fs2.end(), ' ', '_');
	return "ctrnact-" + nn_fam + "-" + fs2 + "-" + n;
}
static void jstr(std::ostream& o, const string& s) { o << '"'; for (char c : s) { if (c == '"' || c == '\\') o << '\\'; o << c; } o << '"'; }
static void jvec(std::ostream& o, const Vec& v) { o << '[' << v[0] << ',' << v[1] << ',' << v[2] << ',' << v[3] << ']'; }

struct Rec { int k; string id; Vec T1, T2; vector<Vec> seeds; vector<Face> faces; bool areaOk; };

int main(int argc, char** argv) {
	std::fesetround(FE_TONEAREST);
	bool wantFaces = std::getenv("EU_FACES") != nullptr; // emit tile polygons + area certificate (doubled/render)
	int kmin = 1, kmax = 8, sign = 1; string pruned = "work/out/pruned", out;
	for (int i = 1; i < argc; i++) {
		string a = argv[i];
		auto nxt = [&]() { return string(argv[++i]); };
		if (a == "--kmin") kmin = std::stoi(nxt());
		else if (a == "--kmax") kmax = std::stoi(nxt());
		else if (a == "--sign") sign = std::stoi(nxt());
		else if (a == "--pruned") pruned = nxt();
		else if (a == "--out") out = nxt();
	}
	if (out.empty()) out = "work/ctrnact-cells-k" + std::to_string(kmax) + ".json";

	vector<Rec> records; long errors = 0; std::unordered_map<int,long> perK;
	for (int k = kmin; k <= kmax; k++) {
		// accept streamed (eupruned_NN.txt) and family (eupruned_NN_*.txt) naming, NN zero-padded or not
		char pad[8]; std::snprintf(pad, sizeof pad, "%02d", k);
		string p2 = string("eupruned_") + pad, p1 = string("eupruned_") + std::to_string(k);
		vector<string> files;
		if (fs::is_directory(pruned)) for (auto& e : fs::directory_iterator(pruned)) {
			string fn = e.path().filename().string();
			if (fn.size() < 4 || fn.substr(fn.size()-4) != ".txt") continue;
			string stem = fn.substr(0, fn.size()-4);
			if (stem == p2 || stem == p1 || stem.rfind(p2 + "_", 0) == 0 || stem.rfind(p1 + "_", 0) == 0) files.push_back(e.path().string());
		}
		std::sort(files.begin(), files.end());
		for (const auto& f : files) {
			std::ifstream in(f);
			for (auto& b : read_blocks(in)) {
				int tesLine = -1;
				for (size_t i = 0; i < b.size(); i++) if (b[i].rfind("TES file:", 0) == 0) { tesLine = (int)i; break; }
				if (tesLine < 0) continue;
				string tes = b[tesLine].substr(9); size_t z = tes.find_first_not_of(" \t"); tes = (z==std::string::npos)?"":tes.substr(z);
				string tid = tes_id(tes);
				// Counting-vertex k = the eupruned_<k> file this block came from (the pruner
				// already grouped by the Myers counting convention). The old '('-count shortcut
				// equals this ONLY when every vertex counts (regular palette); for the doubled
				// palette it would also count noncounting flat-flat (mid-edge) vertices.
				int kk = k;
				Graph gph = decode(b[0], b[4]);
				DevResult dr = develop(gph.rneig, gph.cls, gph.glue, sign, wantFaces);
				if (!dr.ok) { errors++; std::fprintf(stderr, "  ERR %-32s %s\n", tid.c_str(), dr.err.c_str()); continue; }
				records.push_back({kk, tid, dr.T1, dr.T2, dr.seeds, dr.faces, dr.areaOk});
				perK[kk]++;
			}
		}
	}
	std::sort(records.begin(), records.end(), [](const Rec& x, const Rec& y) { return x.k != y.k ? x.k < y.k : x.id < y.id; });
	std::ofstream of(out);
	of << '[';
	for (size_t i = 0; i < records.size(); i++) {
		const Rec& r = records[i];
		if (i) of << ',';
		of << "{\"id\":"; jstr(of, r.id);
		of << ",\"k\":" << r.k << ",\"T1\":"; jvec(of, r.T1);
		of << ",\"T2\":"; jvec(of, r.T2);
		of << ",\"Seed\":[";
		for (size_t s = 0; s < r.seeds.size(); s++) { if (s) of << ','; jvec(of, r.seeds[s]); }
		of << "]";
		if (wantFaces) {
			of << ",\"areaOk\":" << (r.areaOk ? "true" : "false") << ",\"faces\":[";
			for (size_t fi = 0; fi < r.faces.size(); fi++) {
				if (fi) of << ',';
				of << "{\"tile\":"; jstr(of, TILE_NAME[r.faces[fi].tile]); of << ",\"verts\":[";
				for (size_t vi = 0; vi < r.faces[fi].verts.size(); vi++) { if (vi) of << ','; jvec(of, r.faces[fi].verts[vi]); }
				of << "]}";
			}
			of << "]";
		}
		of << "}";
	}
	of << ']';
	of.close();
	std::fprintf(stderr, "developed %zu tilings -> %s\n", records.size(), out.c_str());
	vector<int> ks; for (auto& kv : perK) ks.push_back(kv.first); std::sort(ks.begin(), ks.end());
	for (int k : ks) std::fprintf(stderr, "  k=%d : %ld\n", k, perK[k]);
	if (wantFaces) { long ao = 0; for (auto& r : records) if (r.areaOk) ao++;
		std::fprintf(stderr, "area-cert (float Σface=|detΛ|): %ld/%zu tilings PASS%s\n", ao, records.size(),
		             ao == (long)records.size() ? "" : "  ⚑ SOME FAILED"); }
	if (errors) std::fprintf(stderr, "DEVELOP ERRORS: %ld\n", errors);
	return 0;
}
