#!/usr/bin/env python3
"""Write one isotoxal palette per SUBSET of the eleven D=120 star outlines.

The eleven outlines are the boundaries of {5/2},{6/2},{8/2},{8/3},{10/2},{10/3},{10/4},{12/2},{12/3},
{12/4},{12/5}: point angle 60*(n-2d)/n units, an integer exactly for these. Regular n-gons are
included for every n whose corner is a whole number of units and which the stars in the subset need.

⚑ A SUBSET SWEEP IS NOT A CENSUS OF THE WHOLE GRID. A solid whose faces use j different star families
appears only in palettes carrying all j of them, so the singles answer j=1, the pairs answer j=2, and
nothing here answers j>=3. That is a coverage statement, not a theorem — see isotox-full11.json for
the run that needs no such caveat.

Usage: python3 gen_isotox_subset_palettes.py --size 1 --size 2 [--emit]
"""
import argparse, itertools, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
D = 120
REG = [(3, "3"), (4, "4"), (5, "5"), (6, "6"), (8, "8"), (10, "a"), (12, "c")]
# (n, alphaU, famchar, the {n/d} whose outline this is)
STARS = [(5, 12, "p", "5/2"), (6, 20, "s", "6/2"), (8, 30, "t", "8/2"), (8, 15, "q", "8/3"),
         (10, 36, "u", "10/2"), (10, 24, "r", "10/3"), (10, 12, "v", "10/4"),
         (12, 40, "w", "12/2"), (12, 30, "x", "12/3"), (12, 20, "y", "12/4"), (12, 10, "z", "12/5")]


def palette(sub):
    stars = [STARS[i] for i in sub]
    # the regular n-gons: the six that every isotoxal palette has carried, plus the 12-gon when a
    # 12-pointed star is present (which is what the shipped isotox-cmp12-* palettes do).
    need12 = any(n == 12 for n, _, _, _ in stars)
    regs = [r for r in REG if r[0] != 12 or need12]
    name = "isotox-sub-" + "-".join("%d_%d" % (n, a) for n, a, _, _ in stars)
    return {
        "name": name,
        "D": D,
        "closure": "mixed",
        "maxValence": 6,
        "comment": ("SUBSET PALETTE, generated by gen_isotox_subset_palettes.py. Star outlines: "
                    + ", ".join("%s (the outline of {%s})" % (("%d*%d" % (n, a)), nd)
                                for n, a, _, nd in stars)
                    + ". ⚑ Complete only for solids whose star faces all come from THIS subset; a "
                      "solid mixing families outside it cannot appear here by construction."),
        "tiles": ([{"kind": "regular", "n": n, "name": str(n), "famchar": fc} for n, fc in regs]
                  + [{"kind": "star", "n": n, "alphaU": a, "name": "%d*%d" % (n, a), "famchar": fc}
                     for n, a, fc, _ in stars]),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, action="append", required=True)
    ap.add_argument("--emit", action="store_true")
    args = ap.parse_args()
    made = []
    for k in args.size:
        for sub in itertools.combinations(range(len(STARS)), k):
            p = palette(sub)
            made.append(p["name"])
            if args.emit:
                open(os.path.join(HERE, "alphabets", "palettes", p["name"] + ".json"), "w") \
                    .write(json.dumps(p, indent=1) + "\n")
    print("%d palettes%s" % (len(made), "" if args.emit else " (dry run — pass --emit)"))
    for n in made[:4]:
        print("  ", n)
    if len(made) > 4:
        print("   ... and %d more" % (len(made) - 4))


if __name__ == "__main__":
    main()
