#!/usr/bin/env python3
"""UNVALIDATED. Do not quote numbers from this file. (2026-08-13)

Written to adjudicate a count change on the tri45 shelf, and it is not good enough for the job: it
collapses that shelf's 4,285 entries to 3,976 where `scripts/build-tri45-shelf.mjs`'s own fingerprint
keeps them distinct, so its duplicate counts and its set differences are inside its own error. A
separate angle check built on its primitive-lattice reduction produced a FALSE finding — reducing the
lattice without also collapsing the faces it identifies counts a 4x fundamental domain four times over
and reads 1440 degrees where a legal tiling reads 360. Kept because the shape of the problem is right
and the next attempt should start from it, not because its answers are.

Exact-enough canonical form for a developed periodic tiling, to compare two catalogues as SETS.

Counts alone cannot say whether a change lost tilings or removed duplicates, and on the 45-45-90
palettes the count moved DOWN when the sided-class fix landed — so the question has to be settled on
the objects, not the totals.

A developed record is a period lattice (T1, T2) and a list of faces, each a list of plane vertices.
Two records are the same tiling iff one maps to the other under an isometry of the plane. Here that
group is finite modulo the period: the point group is generated by rotation through 45 degrees and a
reflection (16 elements — every direction in these palettes is a multiple of 45 degrees), and the
translations that matter can be taken to be "move some face centroid to the origin", because any
isometry carrying one tiling to the other carries some face to some face.

So: for each of the 16 point-group elements and each face centroid taken as the origin, write the
face set as a sorted string of (centroid mod L, sorted vertex offsets), and take the lexicographic
minimum. Coordinates are rounded to 1e-4, which is far below the 0.5 minimum separation of anything
in these tilings and far above the 1e-9 the developer prints.

  python3 tiling_canon.py --cells a.json                 # duplicates inside one catalogue
  python3 tiling_canon.py --cells new.json --against old.json    # set comparison
"""
import argparse
import json
from fractions import Fraction
from math import cos, sin, pi

Q = 4                                   # rounding, decimal places


def _pg():
    """The 16-element point group: rotations by k*45 degrees, with and without a flip."""
    out = []
    for k in range(8):
        c, s = cos(k * pi / 4), sin(k * pi / 4)
        out.append((c, -s, s, c))
        out.append((c, s, s, -c))       # rotation composed with reflection in the x axis
    return out


PG = _pg()


def _apply(g, p):
    a, b, c, d = g
    return (a * p[0] + b * p[1], c * p[0] + d * p[1])


def _resid(p, T1, T2):
    """Lattice residue of a point in the parallelogram spanned by T1, T2."""
    det = T1[0] * T2[1] - T1[1] * T2[0]
    a = (p[0] * T2[1] - p[1] * T2[0]) / det
    b = (T1[0] * p[1] - T1[1] * p[0]) / det
    a -= (a + 1e-9) // 1
    b -= (b + 1e-9) // 1
    if a > 1 - 1e-7:
        a -= 1
    if b > 1 - 1e-7:
        b -= 1
    return (a * T1[0] + b * T2[0], a * T1[1] + b * T2[1])


def _lat_coords(p, T1, T2):
    det = T1[0] * T2[1] - T1[1] * T2[0]
    return ((p[0] * T2[1] - p[1] * T2[0]) / det, (T1[0] * p[1] - T1[1] * p[0]) / det)


def _primitive(T1, T2, faces, cents):
    """Reduce (T1, T2) to the tiling's OWN period lattice.

    A developed period is whatever fundamental domain the search happened to close on, and it can be
    a proper multiple of the tiling's real period. Two presentations of one tiling then read as two
    tilings, which makes a set comparison meaningless. So: find every translation that maps the face
    set to itself, express it in lattice coordinates (rationals with tiny denominators), and rebuild
    on the lattice those generate.
    """
    shp = [tuple(sorted((round(v[0] - c[0], Q) + 0.0, round(v[1] - c[1], Q) + 0.0) for v in f))
           for f, c in zip(faces, cents)]
    have = {}
    for c, sh in zip(cents, shp):
        a, b = _lat_coords(c, T1, T2)
        have[(round((a - (a + 1e-9) // 1) % 1.0, Q), round((b - (b + 1e-9) // 1) % 1.0, Q), sh)] = True

    def is_period(da, db):
        for c, sh in zip(cents, shp):
            a, b = _lat_coords(c, T1, T2)
            key = (round((a + da - (a + da + 1e-9) // 1) % 1.0, Q),
                   round((b + db - (b + db + 1e-9) // 1) % 1.0, Q), sh)
            if key not in have:
                return False
        return True

    gens = [(Fraction(1), Fraction(0)), (Fraction(0), Fraction(1))]
    for c in cents:
        if shp[cents.index(c)] != shp[0]:
            continue
        da, db = _lat_coords((c[0] - cents[0][0], c[1] - cents[0][1]), T1, T2)
        if is_period(da, db):
            gens.append((Fraction(da).limit_denominator(64), Fraction(db).limit_denominator(64)))
    # Hermite form of the rational lattice the generators span.
    den = 1
    for a, b in gens:
        den = den * a.denominator // _gcd(den, a.denominator)
        den = den * b.denominator // _gcd(den, b.denominator)
    rows = [[int(a * den), int(b * den)] for a, b in gens]
    a11, a12, a22 = _hnf2(rows)
    if (a11, a12, a22) == (den, 0, den):
        return T1, T2
    U1 = (a11 / den, a12 / den)
    U2 = (0.0, a22 / den)
    N1 = (U1[0] * T1[0] + U1[1] * T2[0], U1[0] * T1[1] + U1[1] * T2[1])
    N2 = (U2[0] * T1[0] + U2[1] * T2[0], U2[0] * T1[1] + U2[1] * T2[1])
    return N1, N2


def _gcd(a, b):
    while b:
        a, b = b, a % b
    return a or 1


def _hnf2(rows):
    """Row Hermite normal form {(a11, a12), (0, a22)} of the integer lattice spanned by `rows`.

    Standard two-column HNF and not the shortcut it replaces: reduce the first column by repeated
    extended gcd to one pivot row, clear the first coordinate of every other row against it, then
    take the gcd of what is left in the second column.
    """
    rows = [list(r) for r in rows if r[0] or r[1]]
    if not rows:
        return (1, 0, 1)
    piv = None
    for r in rows:
        if r[0] == 0:
            continue
        if piv is None:
            piv = r if r[0] > 0 else [-r[0], -r[1]]
        else:
            g, x, y = _egcd(piv[0], r[0])
            piv = [g, x * piv[1] + y * r[1]]
    rest = []
    for r in rows:
        if piv is None:
            rest.append(r[1])
        else:
            q = r[0] // piv[0]
            rest.append(r[1] - q * piv[1])
    a22 = 0
    for v in rest:
        a22 = _plain_gcd(a22, abs(v))
    if piv is None:
        return (0, 0, a22 or 1)
    a22 = a22 or 1
    return (piv[0], piv[1] % a22, a22)


def _plain_gcd(a, b):
    """gcd with gcd(0, 0) == 0. _gcd's `or 1` fallback is right for its callers and wrong here: it
    turns "no constraint yet" into "constrained to 1" and collapses the second HNF coordinate."""
    while b:
        a, b = b, a % b
    return a


def _egcd(a, b):
    if b == 0:
        return (abs(a), 1 if a > 0 else -1, 0)
    g, x, y = _egcd(b, a % b)
    return (g, y, x - (a // b) * y)


def _gcd_all(xs):
    g = 0
    for x in xs:
        g = _gcd(g, x)
    return g or 1


def canonical(rec):
    T1, T2 = rec["T1"], rec["T2"]
    faces = [[tuple(v) for v in f] for f in rec["faces"]]
    cents = [(sum(v[0] for v in f) / len(f), sum(v[1] for v in f) / len(f)) for f in faces]
    T1, T2 = _primitive(T1, T2, faces, cents)
    keep, seen = [], set()
    for f, c in zip(faces, cents):
        r = _resid(c, T1, T2)
        k = (round(r[0], Q) + 0.0, round(r[1], Q) + 0.0,
             tuple(sorted((round(v[0] - c[0], Q) + 0.0, round(v[1] - c[1], Q) + 0.0) for v in f)))
        if k in seen:
            continue
        seen.add(k)
        keep.append((f, c))
    faces = [f for f, _ in keep]
    cents = [c for _, c in keep]
    best = None
    for g in PG:
        gT1, gT2 = _apply(g, T1), _apply(g, T2)
        gf = [[_apply(g, v) for v in f] for f in faces]
        gc = [_apply(g, c) for c in cents]
        for oi in range(len(gc)):
            ox, oy = gc[oi]
            items = []
            for f, c in zip(gf, gc):
                rc = _resid((c[0] - ox, c[1] - oy), gT1, gT2)
                offs = sorted((round(v[0] - c[0], Q) + 0.0, round(v[1] - c[1], Q) + 0.0) for v in f)
                items.append((round(rc[0], Q) + 0.0, round(rc[1], Q) + 0.0, tuple(offs)))
            key = repr(sorted(items))
            if best is None or key < best:
                best = key
    return best


def load(path, kmax):
    out = {}
    for rec in json.load(open(path)):
        if rec["k"] > kmax:
            continue
        out.setdefault(rec["k"], {}).setdefault(canonical(rec), []).append(rec["id"])
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cells", required=True)
    ap.add_argument("--against")
    ap.add_argument("--kmax", type=int, default=3)
    args = ap.parse_args()

    A = load(args.cells, args.kmax)
    if not args.against:
        print("k   records  distinct  duplicated")
        for k in sorted(A):
            n = sum(len(v) for v in A[k].values())
            print("%-3d %7d  %8d  %10d" % (k, n, len(A[k]), n - len(A[k])))
        return 0

    B = load(args.against, args.kmax)
    print("k    new  old  in both  new only  old only")
    lost = 0
    for k in sorted(set(A) | set(B)):
        a, b = set(A.get(k, {})), set(B.get(k, {}))
        lost += len(b - a)
        print("%-4d %4d %4d %8d %9d %9d" % (k, len(a), len(b), len(a & b), len(a - b), len(b - a)))
    aU = {key for k in A for key in A[k]}
    bU = {key for k in B for key in B[k]}
    print()
    print("union: new %d   old %d   old-only %d   new-only %d   same tiling, different k: %d"
          % (len(aU), len(bU), len(bU - aU), len(aU - bU),
             len({key for key in aU & bU
                  if next(k for k in A if key in A[k]) != next(k for k in B if key in B[k])})))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
