"use client";

import { useMemo } from "react";
import { ALPHABET_44, type AlphabetLetter } from "@/lib/defense/alphabet44";
import { figureFromWord } from "@/lib/render/vertexFigure";
import { hsbToHsla, polygonHue } from "@/lib/utils/renderTiling";

// The whole alphabet on one slide: 44 letters, grouped by the 14 configurations they refine.
//
// The slide's claim is that a letter is a configuration PLUS a site symmetry, and the grouping is
// what carries it — 4.4.4.4 alone accounts for eight of the 44, and the hexagonal vertex for ten,
// because those are the words with the most subgroups to fold by. Read the row of a group and you
// are reading the subgroup lattice of a dihedral group, drawn.
//
// Every mark is derived, not drawn by eye. lib/defense/alphabet44.ts is generated by
// scripts/build-alphabet-figure.mjs, which recovers each letter's site-symmetry subgroup from the
// shipped table by finding the unique subgroup whose dart orbits the entry's own label array
// transverses, then checks the recovered axes and rotations really are symmetries of the figure
// drawn here. The frame is the table's, so an axis at 150 degrees is at 150 degrees in this picture.
//
// SVG and not canvas: 44 static drawings with no interaction, no resize maths and no text to flush
// out of a mirrored transform.

/**
 * Half the drawn box, how far a mirror line runs, and how much of the box the tiles get.
 *
 * The tiles get less than the mirrors do, deliberately. A mirror of 4.4.4.4 lies along the edge
 * between two of its squares and a mirror of the hexagonal vertex along an edge between two triangles,
 * so at cell size an axis drawn only across the figure is indistinguishable from a tile edge. Letting
 * every axis run out past the tiles makes it unmistakable at a glance.
 */
const VIEW = 1.34;
const REACH = 1.3;
const TILES = 0.83;
/**
 * The largest reach, in unit edges, a cell will shrink to fit. A 12-gon's far corner is 3.86 edges
 * from the vertex, so fitting one whole would leave the square beside it four pixels across; past the
 * cap the figure is drawn at cap scale and clipped by the cell instead. Set at 2.05 so every
 * configuration without a 12-gon still lands whole — the hexagonal vertex reaches 1, the square 1.41,
 * and 3.4.6.4 exactly 2.
 */
const CAP = 2.05;

const MIRROR = "rgba(20,20,20,0.62)";
const MARK = "rgba(20,20,20,0.88)";

interface Geometry {
	polys: { n: number; d: string }[];
}

/** The figure a letter's word describes, scaled to circumradius 1 so every cell reads the same size. */
function geometryOf(word: number[]): Geometry | null {
	const polys = figureFromWord(word.join("."));
	if (!polys) return null;
	let r = 0;
	for (const p of polys) for (const v of p.vertices) r = Math.max(r, Math.hypot(v.x, v.y));
	if (r <= 0) return null;
	const k = Math.min(r, CAP) / (VIEW * TILES);
	return {
		polys: polys.map((p) => ({
			n: p.n,
			d: p.vertices.map((v, i) => `${i ? "L" : "M"}${(v.x / k).toFixed(4)},${(v.y / k).toFixed(4)}`).join(" ") + " Z",
		})),
	};
}

/**
 * The crystallographic marker for an r-fold rotation about the vertex: a lens for 2, then the regular
 * r-gon. Drawn over a surface-coloured disc, because it sits on the one point every tile touches.
 */
function RotationMark({ r }: { r: number }) {
	if (r < 2) return null;
	const size = 0.2;
	if (r === 2) {
		// The standard pointed oval, as two circular arcs meeting at the two points.
		const a = size * 1.25, b = size * 0.62;
		return (
			<>
				<circle cx={0} cy={0} r={a * 1.05} fill="var(--color-surface-base, #fff)" />
				<path d={`M${-a},0 Q0,${b} ${a},0 Q0,${-b} ${-a},0 Z`} fill={MARK} />
			</>
		);
	}
	// A 3- and a 6-fold sit point-up; a 4-fold sits square, as the crystallographic symbols do.
	const turn = r === 4 ? Math.PI / 4 : Math.PI / 2;
	const pts = Array.from({ length: r }, (_, i) => {
		const t = (2 * Math.PI * i) / r + turn;
		return `${(Math.cos(t) * size).toFixed(4)},${(Math.sin(t) * size).toFixed(4)}`;
	}).join(" ");
	return (
		<>
			<circle cx={0} cy={0} r={size * 1.35} fill="var(--color-surface-base, #fff)" />
			<polygon points={pts} fill={MARK} />
		</>
	);
}

function LetterCell({ letter }: { letter: AlphabetLetter }) {
	const geo = useMemo(() => geometryOf(letter.word), [letter]);
	// The table names no variant for the three chiral configurations, whose word has no symmetry at
	// all: their single letter is the trivial fold, which is what F means everywhere else.
	const name = letter.variant || "F";

	return (
		<figure className="m-0 flex flex-col items-center gap-[0.15rem]">
			<div
				className="relative overflow-hidden rounded-md border border-line bg-surface-base"
				style={{ width: "var(--cell)", height: "var(--cell)" }}
			>
				{geo && (
					// y down in SVG, y up in the figure: one flip on the group, so the angles the generator
					// emits are the angles drawn.
					<svg viewBox={`${-VIEW} ${-VIEW} ${2 * VIEW} ${2 * VIEW}`} className="h-full w-full" role="img" aria-label={letter.symbol}>
						<g transform="scale(1,-1)">
							{geo.polys.map((p, i) => (
								<path
									key={i}
									d={p.d}
									fill={hsbToHsla(polygonHue(p.n), 40, 100, 0.9)}
									stroke={hsbToHsla(polygonHue(p.n), 55, 62, 1)}
									strokeWidth={0.035}
									strokeLinejoin="round"
								/>
							))}
							{letter.axes.map((a) => {
								const t = (a.deg * Math.PI) / 180;
								const x = Math.cos(t) * REACH, y = Math.sin(t) * REACH;
								return (
									<line
										key={a.deg}
										x1={-x}
										y1={-y}
										x2={x}
										y2={y}
										stroke={MIRROR}
										strokeWidth={0.055}
										strokeLinecap="round"
									/>
								);
							})}
							<RotationMark r={letter.rot} />
						</g>
					</svg>
				)}
			</div>
			<figcaption className="font-mono leading-none text-fg-secondary" style={{ fontSize: "var(--label)" }}>
				{name}
			</figcaption>
		</figure>
	);
}

/** The 44, in table order, split at each change of configuration — which is where the groups are. */
function groupLetters() {
	const out: { word: string; letters: AlphabetLetter[] }[] = [];
	for (const l of ALPHABET_44) {
		const word = l.symbol.slice(1, l.symbol.indexOf(")")).split(",").join(".");
		const last = out[out.length - 1];
		if (last && last.word === word) last.letters.push(l);
		else out.push({ word, letters: [l] });
	}
	return out;
}

const BLOCKS = groupLetters();

export function Alphabet44() {

	return (
		<div
			className="not-prose flex w-full flex-col items-center gap-2"
			style={
				{
					"--cell": "clamp(2.4rem, 7.8vh, 4.7rem)",
					"--label": "clamp(0.44rem, 1.15vh, 0.72rem)",
				} as React.CSSProperties
			}
		>
			<div className="flex flex-wrap items-start justify-center gap-x-5 gap-y-2">
				{BLOCKS.map((b) => (
					<div key={b.word} className="flex flex-col items-center gap-[0.2rem]">
						<div className="font-mono leading-none text-fg-muted" style={{ fontSize: "var(--label)" }}>
							{b.word}
						</div>
						<div className="flex gap-[0.2rem]">
							{b.letters.map((l) => (
								<LetterCell key={l.code} letter={l} />
							))}
						</div>
					</div>
				))}
			</div>
			<div className="flex items-center justify-center gap-5 text-fg-muted" style={{ fontSize: "var(--label)" }}>
				<span className="flex items-center gap-1.5">
					<svg viewBox="-1 -1 2 2" className="h-[0.9em] w-[0.9em]" aria-hidden>
						<line x1={-0.9} y1={0} x2={0.9} y2={0} stroke={MIRROR} strokeWidth={0.18} strokeLinecap="round" />
					</svg>
					a mirror through the vertex
				</span>
				<span className="flex items-center gap-1.5">
					<svg viewBox="-1 -1 2 2" className="h-[0.9em] w-[0.9em]" aria-hidden>
						<polygon points="0,-0.78 0.68,0.39 -0.68,0.39" fill={MARK} />
					</svg>
					a rotation about it, 2- to 6-fold
				</span>
			</div>
		</div>
	);
}
