/**
 * Parse the candidate-lattice census block printed by the k=3 census runs
 * (`experiments/results/*-k3-census-table-*.log`) into a thesis `.tex` table fragment.
 * Counts only — timings / fill rates / gate costs are the deferred per-stage profile (not here).
 */
export type CensusRow = { hol: string; work: number; lattices: number; mult: string };
export type Census = { k: number; solveCalls: number; rows: CensusRow[] };

export function parseCensus(log: string): Census {
	const head = log.match(/k=(\d+)\s+solve-calls=(\d+)/);
	if (!head) throw new Error('censusTable: no "k=… solve-calls=…" header found');
	const rows: CensusRow[] = [];
	for (const line of log.split('\n')) {
		const m = line.match(/^\s*(\d+|ALL)\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|\s*([\d.]+×)\s*$/);
		if (m) rows.push({ hol: m[1], work: Number(m[2]), lattices: Number(m[3]), mult: m[4] });
	}
	if (rows.length === 0) throw new Error('censusTable: no data rows parsed');
	return { k: Number(head[1]), solveCalls: Number(head[2]), rows };
}

export function censusToTex(c: Census): string {
	const body = c.rows.map((r) => {
		const hol = r.hol === 'ALL' ? '\\textbf{all}' : `$${r.hol}$`;
		const sep = r.hol === 'ALL' ? '\\midrule\n' : '';
		return `${sep}${hol} & ${r.work} & ${r.lattices} & ${r.mult} \\\\`;
	});
	return [
		`% AUTOGENERATED by figures/data-extract/censusTable.ts — regenerate from the census log.`,
		'\\begin{table}[ht]',
		'\\centering\\small',
		'\\begin{tabular}{rrrr}',
		'\\toprule',
		'holohedry $\\hol(\\Lambda)$ & work items & distinct lattices & multiplicity \\\\',
		'\\midrule',
		...body,
		'\\bottomrule',
		'\\end{tabular}',
		`\\caption{Candidate-lattice census for $k=${c.k}$ (${c.solveCalls} solve-calls): work items and distinct period lattices per holohedry class. Multiplicity is work items per distinct lattice (orbit/dedup overlap).}`,
		`\\label{tab:lattice-census-k${c.k}}`,
		'\\end{table}',
		'',
	].join('\n');
}
