/**
 * FigureIR → SVG (the PREVIEW backend — instant browser iteration, future web-atlas reuse; the
 * thesis uses emit/tikz.ts). Same style module as TikZ so they cannot drift. SVG is y-DOWN: we
 * keep model coordinates and flip with a scale(1,-1) group; text is counter-flipped locally.
 * Physical sizing: width/height in mm derived from edgeMm; strokes/radii converted mm → model
 * units (vector-effect-free, scales exactly like the TikZ output).
 */
import type { FigureIR, FigureElement, V2 } from '../ir/types';
import { hexOf, mixHexToWhite, resolveStyle } from '../style/palette';
import { rectH, rectW } from '../ir/types';

const fmt = (v: number): string => {
	const s = v.toFixed(6).replace(/\.?0+$/, '');
	return s === '-0' ? '0' : s;
};
const pts = (verts: V2[]): string => verts.map((p) => `${fmt(p.x)},${fmt(p.y)}`).join(' ');

/** SVG is the PREVIEW backend and can't typeset TeX; render the small subset our figures use as
 *  readable Unicode so the preview matches the TikZ output's intent (the .tex still carries real TeX). */
function plainTex(s: string): string {
	return s
		.replace(/\$/g, '')
		.replace(/\\varnothing/g, '∅')
		.replace(/\\vec\s*([A-Za-z])/g, '$1⃗')
		.replace(/\\mathrm\{([^}]*)\}/g, '$1')
		.replace(/\^\\circ/g, '°')
		.replace(/\\cdot/g, '·')
		.replace(/\\ /g, ' ')
		.replace(/\\\{/g, '{')
		.replace(/\\\}/g, '}')
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.trim();
}

function emitElement(el: FigureElement, mmToModel: number): string {
	const st = resolveStyle(el.styleRef);
	// fade = mix toward white in code — the twin of the TikZ emitter's `name!pct!figBg`
	const col = (name: string): string => {
		const hex = hexOf(name).slice(1);
		return '#' + (st.strength != null ? mixHexToWhite(hex, st.strength) : hex);
	};
	// fill-only fade (wireframe transitions): stroke stays at `col` strength
	const colFill = (name: string): string => {
		const hex = hexOf(name).slice(1);
		return '#' + (st.fillStrength != null ? mixHexToWhite(hex, st.fillStrength) : col(name).slice(1));
	};
	const stroke = st.stroke ? ` stroke="${col(st.stroke)}" stroke-width="${fmt((st.lineWidthMm ?? 0) * mmToModel)}" stroke-linejoin="round" stroke-linecap="round"` : '';
	switch (el.kind) {
		case 'poly':
			return `<polygon points="${pts(el.verts)}" fill="${st.fill ? colFill(st.fill) : 'none'}"${stroke}/>`;
		case 'polyline': {
			const tag = el.closed ? 'polygon' : 'polyline';
			return `<${tag} points="${pts(el.verts)}" fill="none"${stroke}/>`;
		}
		case 'marker': {
			if (!st.fill || st.radiusMm == null) {
				throw new Error(`marker styleRef '${el.styleRef}' lacks fill/radius`);
			}
			return `<circle cx="${fmt(el.at.x)}" cy="${fmt(el.at.y)}" r="${fmt(st.radiusMm * mmToModel)}" fill="${col(st.fill)}"/>`;
		}
		case 'arrow': {
			const c = col(st.stroke ?? 'figEdge');
			const w = (st.lineWidthMm ?? 0.4) * mmToModel;
			return `<line x1="${fmt(el.from.x)}" y1="${fmt(el.from.y)}" x2="${fmt(el.to.x)}" y2="${fmt(el.to.y)}" stroke="${c}" stroke-width="${fmt(w)}" marker-end="url(#arrowhead)"/>`;
		}
		case 'text': {
			// counter-flip so text reads upright inside the y-flipped group; TeX rendered to readable
			// Unicode for the preview (the TikZ backend typesets the real TeX).
			const c = col(st.text ?? 'figEdge');
			return `<text x="${fmt(el.at.x)}" y="${fmt(-el.at.y)}" transform="scale(1,-1)" fill="${c}" font-family="Georgia, serif" font-size="${fmt(3.2 * mmToModel)}" text-anchor="middle" dominant-baseline="middle">${plainTex(el.tex)}</text>`;
		}
	}
}

export function emitSvg(ir: FigureIR, opts: { edgeMm: number }): string {
	const mmToModel = 1 / opts.edgeMm; // 1mm in model units
	const w = rectW(ir.bbox);
	const h = rectH(ir.bbox);
	// y-flip: viewBox y-min is -bbox.maxY
	const viewBox = `${fmt(ir.bbox.minX)} ${fmt(-ir.bbox.maxY)} ${fmt(w)} ${fmt(h)}`;
	const lines: string[] = [
		'<?xml version="1.0" encoding="UTF-8"?>',
		'<!-- AUTOGENERATED by figures/ (TilingAtlas) — preview backend; thesis uses the TikZ emitter. -->',
		`<svg xmlns="http://www.w3.org/2000/svg" width="${fmt(w * opts.edgeMm)}mm" height="${fmt(h * opts.edgeMm)}mm" viewBox="${viewBox}">`,
		`<defs><marker id="arrowhead" markerWidth="8" markerHeight="6" refX="7" refY="3" orient="auto"><path d="M0,0 L8,3 L0,6 z" fill="${hexOf('oiBlue')}"/></marker>` +
			// clip-path transforms WITH the flipped group, so the rect is in model (y-up) coords
			(ir.clip
				? `<clipPath id="figclip"><rect x="${fmt(ir.clip.minX)}" y="${fmt(ir.clip.minY)}" width="${fmt(rectW(ir.clip))}" height="${fmt(rectH(ir.clip))}"/></clipPath>`
				: '') +
			'</defs>',
		`<rect x="${fmt(ir.bbox.minX)}" y="${fmt(-ir.bbox.maxY)}" width="${fmt(w)}" height="${fmt(h)}" fill="${hexOf('figBg')}"/>`,
		`<g transform="scale(1,-1)"${ir.clip ? ' clip-path="url(#figclip)"' : ''}>`,
	];
	for (const el of ir.elements) lines.push(emitElement(el, mmToModel));
	lines.push('</g>', '</svg>', '');
	return lines.join('\n');
}
