/**
 * FigureIR → standalone TikZ document (the THESIS-FINAL backend). Compiled per-figure with
 * latexmk; the thesis \includegraphics the resulting PDF. TikZ is y-up — model coordinates pass
 * through unchanged. Physical sizing: `x=<edgeMm>mm` on the picture; line widths / marker radii
 * are absolute mm from the style module (visually identical across figures of any edgeMm).
 *
 * Each generated file inlines the full \definecolor block — self-contained, compilable anywhere.
 */
import type { FigureIR, FigureElement, V2 } from '../ir/types';
import { emitTexColors, resolveStyle } from '../style/palette';

const fmt = (v: number): string => {
	const s = v.toFixed(6).replace(/\.?0+$/, '');
	return s === '-0' ? '0' : s;
};
const pt = (p: V2): string => `(${fmt(p.x)},${fmt(p.y)})`;

function emitElement(el: FigureElement): string {
	const st = resolveStyle(el.styleRef);
	// fade = TikZ-native mix toward the background (print-safe; no transparency)
	const col = (name: string): string =>
		st.strength != null ? `${name}!${st.strength}!figBg` : name;
	// fill-only fade (wireframe transitions): stroke stays at `col` strength
	const colFill = (name: string): string =>
		st.fillStrength != null ? `${name}!${st.fillStrength}!figBg` : col(name);
	switch (el.kind) {
		case 'poly': {
			// fill+stroke on the SAME path (crack avoidance), round joins from the picture options.
			const opts = [
				st.fill ? `fill=${colFill(st.fill)}` : null,
				st.stroke ? `draw=${col(st.stroke)}` : null,
				st.lineWidthMm != null ? `line width=${st.lineWidthMm}mm` : null,
			].filter(Boolean);
			return `\\path[${opts.join(',')}] ${el.verts.map(pt).join(' -- ')} -- cycle;`;
		}
		case 'polyline': {
			const opts = [
				st.stroke ? `draw=${col(st.stroke)}` : null,
				st.lineWidthMm != null ? `line width=${st.lineWidthMm}mm` : null,
			].filter(Boolean);
			const tail = el.closed ? ' -- cycle' : '';
			return `\\path[${opts.join(',')}] ${el.verts.map(pt).join(' -- ')}${tail};`;
		}
		case 'marker': {
			if (!st.fill || st.radiusMm == null) {
				throw new Error(`marker styleRef '${el.styleRef}' lacks fill/radius`);
			}
			return `\\path[fill=${col(st.fill)}] ${pt(el.at)} circle [radius=${st.radiusMm}mm];`;
		}
		case 'arrow': {
			const opts = [
				'-{Stealth[length=2.2mm]}',
				`draw=${col(st.stroke ?? 'figEdge')}`,
				st.lineWidthMm != null ? `line width=${st.lineWidthMm}mm` : null,
			].filter(Boolean);
			return `\\draw[${opts.join(',')}] ${pt(el.from)} -- ${pt(el.to)};`;
		}
		case 'text':
			return `\\node[text=${col(st.text ?? 'figEdge')},font=\\small] at ${pt(el.at)} {${el.tex}};`;
	}
}

export function emitTikz(ir: FigureIR, opts: { edgeMm: number }): string {
	const lines: string[] = [
		'% AUTOGENERATED by figures/ (TilingAtlas) — do not edit; regenerate with `pnpm figures`.',
		'\\documentclass[border=1mm]{standalone}',
		'\\usepackage{tikz}',
		'\\usetikzlibrary{arrows.meta}',
		emitTexColors(),
		'\\begin{document}',
		`\\begin{tikzpicture}[x=${opts.edgeMm}mm,y=${opts.edgeMm}mm,line join=round,line cap=round]`,
		`\\useasboundingbox (${fmt(ir.bbox.minX)},${fmt(ir.bbox.minY)}) rectangle (${fmt(ir.bbox.maxX)},${fmt(ir.bbox.maxY)});`,
	];
	if (ir.clip) {
		lines.push(
			`\\clip (${fmt(ir.clip.minX)},${fmt(ir.clip.minY)}) rectangle (${fmt(ir.clip.maxX)},${fmt(ir.clip.maxY)});`
		);
	}
	for (const el of ir.elements) lines.push(emitElement(el));
	lines.push('\\end{tikzpicture}', '\\end{document}', '');
	return lines.join('\n');
}
