import { describe, it, expect } from "vitest";
import fixture from "@/lib/utils/__fixtures__/intrinsic-cells.fixture.json";
import { developIntrinsic, evaluateIntrinsic, type IntrinsicCellData } from "@/lib/utils/intrinsicCell";

/**
 * The two solvers have to agree.
 *
 * An intrinsic cell ships the constraint system, not the answer, so the geometry exists only once
 * something solves for it — `tools/ctrnact-oracle/intrinsic_family.py` offline, this module in the
 * browser. They take different steps on purpose (least-norm `lstsq` there, a damped normal-equation
 * solve here, because a browser has no LAPACK), which is sound only because the chart's fixed point is
 * pinned by the free angles and not by the route. Sound in theory; measured here.
 *
 * The fixture is generated by `emit_intrinsic_fixture.py` from real shelf records at slider positions
 * that are deliberately not round fractions of their ranges — a chart that agrees only at the anchor and
 * the midpoint is agreeing where the tiling's symmetry does the work.
 */
type Case = { t: number[]; cellPolygons: { n: number; vertices: number[][] }[]; basis: number[][] };
type Rec = { id: string; freeDarts: number[]; params: { defaultAlphaDeg: number }[];
	intrinsic: IntrinsicCellData; cases: Case[] };
const RECORDS = fixture as unknown as Rec[];

/**
 * A fresh copy of the cell per evaluation.
 *
 * `evaluateIntrinsic` warm-starts from wherever it last solved, which is what makes dragging a slider
 * continuous and is the right behaviour in the app. The fixture was generated with every solve starting
 * from the anchor, so comparing against it has to start there too — otherwise the test would be checking
 * a path, not a chart, and a family with more than one sheet could disagree for a reason that is not a bug.
 */
const fresh = (ic: IntrinsicCellData): IntrinsicCellData => JSON.parse(JSON.stringify(ic)) as IntrinsicCellData;

/** Same lattice: equal |det|, and each generator of one an integer combination of the other's. */
function expectSameLattice(got: number[][], want: number[][]) {
	const det = (b: number[][]): number => b[0][0] * b[1][1] - b[1][0] * b[0][1];
	expect(Math.abs(det(got))).toBeCloseTo(Math.abs(det(want)), 8);
	const d = det(want);
	for (const v of [...got, ...want.map((w) => w)]) {
		const m = (v[0] * want[1][1] - want[1][0] * v[1]) / d;
		const n = (want[0][0] * v[1] - v[0] * want[0][1]) / d;
		expect(Math.abs(m - Math.round(m))).toBeLessThan(1e-8);
		expect(Math.abs(n - Math.round(n))).toBeLessThan(1e-8);
	}
}

describe("intrinsic cells: TypeScript against the Python solver", () => {
	it("has a fixture with a range of dimensions", () => {
		expect(RECORDS.length).toBeGreaterThan(0);
		expect(Math.max(...RECORDS.map((r) => r.freeDarts.length))).toBeGreaterThan(1);
	});

	for (const rec of RECORDS) {
		describe(`${rec.id} (d=${rec.freeDarts.length})`, () => {
			for (const [i, c] of rec.cases.entries()) {
				it(`matches at slider position ${i} (${c.t.map((x) => x.toFixed(2)).join(", ")})`, () => {
					const cell = evaluateIntrinsic(fresh(rec.intrinsic), rec.freeDarts, c.t);
					expect(cell).not.toBeNull();
					const polys = cell!.cellPolygons as { n: number; vertices: number[][] }[];
					expect(polys.length).toBe(c.cellPolygons.length);
					for (let f = 0; f < polys.length; f++) {
						expect(polys[f].n).toBe(c.cellPolygons[f].n);
						for (let v = 0; v < polys[f].vertices.length; v++) {
							expect(polys[f].vertices[v][0]).toBeCloseTo(c.cellPolygons[f].vertices[v][0], 9);
							expect(polys[f].vertices[v][1]).toBeCloseTo(c.cellPolygons[f].vertices[v][1], 9);
						}
					}
					// The LATTICE has to match, not the two vectors naming it. Lagrange–Gauss reduction has
					// ties in a symmetric lattice — `period-k2-049`'s anchor is hexagonal, several
					// generators share a length — and which side of a tie a round lands on comes down to
					// the last bits of a dot product. Both answers are correct bases of the same lattice
					// and both draw the same tiling; asserting on the vectors would be asserting on
					// float noise.
					expectSameLattice(cell!.basis as number[][], c.basis);
				});
			}

			it("develops the anchor from its own angles", () => {
				const cell = evaluateIntrinsic(fresh(rec.intrinsic), rec.freeDarts,
					rec.freeDarts.map((d) => rec.intrinsic.angles0[d]));
				expect(cell).not.toBeNull();
				const anchor = rec.cases.find((c) =>
					c.t.every((v, j) => Math.abs(v - rec.intrinsic.angles0[rec.freeDarts[j]]) < 1e-9));
				if (!anchor) return;
				const polys = cell!.cellPolygons as { vertices: number[][] }[];
				for (let f = 0; f < polys.length; f++) {
					for (let v = 0; v < polys[f].vertices.length; v++) {
						expect(polys[f].vertices[v][0]).toBeCloseTo(anchor.cellPolygons[f].vertices[v][0], 9);
					}
				}
			});

			it("tiles: Σ tile areas equals |det basis| at every fixture position", () => {
				for (const c of rec.cases) {
					const cell = evaluateIntrinsic(fresh(rec.intrinsic), rec.freeDarts, c.t);
					const polys = (cell!.cellPolygons ?? []) as { vertices: number[][] }[];
					let sum = 0;
					for (const p of polys) {
						let s = 0;
						for (let i = 0; i < p.vertices.length; i++) {
							const a = p.vertices[i], b = p.vertices[(i + 1) % p.vertices.length];
							s += a[0] * b[1] - b[0] * a[1];
						}
						sum += Math.abs(s / 2);
					}
					const [[ux, uy], [vx, vy]] = cell!.basis as number[][];
					expect(Math.abs(sum - Math.abs(ux * vy - uy * vx))).toBeLessThan(1e-7);
				}
			});

			// Every edge is a unit edge; that is what makes these tiles equilateral, and it is the one
			// invariant a wrong turning convention in `localFace` would break silently everywhere else.
			it("keeps every edge at unit length", () => {
				const cell = evaluateIntrinsic(fresh(rec.intrinsic), rec.freeDarts,
					rec.cases[rec.cases.length - 1].t);
				for (const p of (cell!.cellPolygons ?? []) as { vertices: number[][] }[]) {
					for (let i = 0; i < p.vertices.length; i++) {
						const a = p.vertices[i], b = p.vertices[(i + 1) % p.vertices.length];
						expect(Math.hypot(b[0] - a[0], b[1] - a[1])).toBeCloseTo(1, 9);
					}
				}
			});
		});
	}

	it("develops something for a tuple outside the family instead of throwing", () => {
		const rec = RECORDS[0];
		const wild = rec.freeDarts.map((d) => rec.intrinsic.angles0[d] + 1e4);
		const cell = evaluateIntrinsic(fresh(rec.intrinsic), rec.freeDarts, wild);
		expect(cell).not.toBeNull();
		expect((cell!.cellPolygons ?? []).length).toBe(rec.intrinsic.faceSizes.length);
	});
});

describe("developIntrinsic is exported for the range tooling", () => {
	it("is a function", () => {
		expect(typeof developIntrinsic).toBe("function");
	});
});
