/**
 * Figure build orchestrator (figures/README.md):
 *   snapshot + orbits + oracle map → IR → emit .tex/.svg → latexmk (parallel, content-hash skip)
 *   → generated gallery/match-table .tex → deliver PDFs + includes to ../thesis/figures/generated/.
 *
 *   pnpm figures [--only <substring>] [--k <n>] [--no-latex] [--no-deliver]
 *
 * k=3 caveat (NOTES §28): the certified catalogue currently holds 60 distinct + 1 non-primitive
 * duplicate and MISSES Galebach #7. The k=3 gallery is generated with a loud caveat note, the
 * duplicate excluded; it regenerates in one command once the catalogue is fixed.
 */
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFile } from 'node:child_process';
import os from 'node:os';
import { loadSnapshot } from './snapshot';
import { ensureOrbits } from './tiling/orbits';
import { buildCellModel } from './tiling/cellModel';
import { tilingFigure } from './tiling/tilingFigure';
import { emitTikz } from './emit/tikz';
import { emitSvg } from './emit/svg';
import { emitTexColors } from './style/palette';
import { galleryEntries, type OracleMap, type TilingFigureEntry } from './manifest';

const ROOT = process.cwd();
const OUT = path.join(ROOT, 'figures', 'out', 'batch');
const THESIS_FIG = path.join(ROOT, '..', 'thesis', 'figures', 'generated');
const TEXBIN = path.join(os.homedir(), 'Library', 'TinyTeX', 'bin', 'universal-darwin');

const args = process.argv.slice(2);
const flag = (name: string): boolean => args.includes(name);
const opt = (name: string): string | undefined => {
	const i = args.indexOf(name);
	return i >= 0 ? args[i + 1] : undefined;
};

function latexmk(texFile: string): Promise<void> {
	return new Promise((resolve, reject) => {
		execFile(
			path.join(TEXBIN, 'latexmk'),
			['-pdf', '-halt-on-error', '-interaction=nonstopmode', path.basename(texFile)],
			{ cwd: path.dirname(texFile), env: { ...process.env, PATH: `${TEXBIN}:${process.env.PATH}` } },
			(err) => (err ? reject(new Error(`latexmk failed: ${texFile}`)) : resolve())
		);
	});
}

async function pool<T>(items: T[], n: number, fn: (t: T) => Promise<void>): Promise<void> {
	const queue = [...items];
	const workers = Array.from({ length: Math.max(1, n) }, async () => {
		for (;;) {
			const item = queue.shift();
			if (item === undefined) return;
			await fn(item);
		}
	});
	await Promise.all(workers);
}

const texEscape = (s: string): string => s.replace(/([&%$#_{}~^\\])/g, '\\$1');

/** Gallery include: subcaption grid, 4 panels per row, captioned with t-code + VC types. */
function galleryTex(k: number, entries: TilingFigureEntry[], caveat?: string): string {
	const COLS = 4;
	const PER_PAGE = 20;
	const lines: string[] = [
		`% AUTOGENERATED by figures/build.ts (TilingAtlas) — do not edit; regenerate with \`pnpm figures\`.`,
	];
	if (caveat) lines.push(`% ⚑ CAVEAT: ${caveat}`);
	const pages: TilingFigureEntry[][] = [];
	for (let i = 0; i < entries.length; i += PER_PAGE) pages.push(entries.slice(i, i + PER_PAGE));
	pages.forEach((page, pi) => {
		lines.push('\\begin{figure}[p]', '\\centering');
		page.forEach((e, i) => {
			const label = e.tCode ? `\\texttt{${texEscape(e.tCode)}}` : '(unmatched)';
			lines.push(
				`\\begin{subfigure}{0.235\\textwidth}`,
				`\\centering`,
				`\\includegraphics[width=\\linewidth]{figures/generated/k${k}/${e.id}.pdf}`,
				`\\caption*{${label}\\\\{\\tiny ${e.vcLabelTex}}}`,
				`\\end{subfigure}${(i + 1) % COLS === 0 ? '' : '\\hfill'}`
			);
		});
		const part = pages.length > 1 ? ` (part ${pi + 1} of ${pages.length})` : '';
		const caveatNote = caveat ? ` ${caveat}` : '';
		// k=1 is included in the preliminaries (definition context) — "certified" is results-chapter
		// language, so the eleven get the classical name instead.
		const subject =
			k === 1 ? 'The eleven uniform (Archimedean) tilings' : `The certified ${k}-uniform tilings`;
		lines.push(
			`\\caption{${subject}${part}, colored by polygon type, labeled by Galebach index and vertex types.${caveatNote}}`,
			`\\label{fig:gallery-k${k}${pages.length > 1 ? `-${pi + 1}` : ''}}`,
			'\\end{figure}',
			''
		);
	});
	return lines.join('\n');
}

/** Match table include: t-code ↔ vertex types, two tilings per row for k=3. */
function matchTableTex(k: number, entries: TilingFigureEntry[], caveat?: string): string {
	const twoCol = entries.length > 30;
	const rows: string[] = [];
	if (twoCol) {
		const half = Math.ceil(entries.length / 2);
		for (let i = 0; i < half; i++) {
			const a = entries[i];
			const b = entries[i + half];
			const cell = (e?: TilingFigureEntry) =>
				e ? `\\texttt{${texEscape(e.tCode ?? '—')}} & ${e.vcLabelTex}` : ' & ';
			rows.push(`${cell(a)} & ${cell(b)} \\\\`);
		}
	} else {
		for (const e of entries) {
			rows.push(`\\texttt{${texEscape(e.tCode ?? '—')}} & ${e.vcLabelTex} \\\\`);
		}
	}
	return [
		`% AUTOGENERATED by figures/build.ts (TilingAtlas) — do not edit; regenerate with \`pnpm figures\`.`,
		...(caveat ? [`% ⚑ CAVEAT: ${caveat}`] : []),
		'\\begin{table}[p]',
		'\\centering\\small',
		`\\begin{tabular}{${twoCol ? 'll@{\\qquad}ll' : 'll'}}`,
		'\\toprule',
		twoCol
			? 'Galebach & vertex types & Galebach & vertex types \\\\'
			: 'Galebach & vertex types \\\\',
		'\\midrule',
		...rows,
		'\\bottomrule',
		'\\end{tabular}',
		`\\caption{Per-tiling oracle match for $k=${k}$: every certified tiling is exactly congruent to the listed Galebach tiling.${caveat ? ` ${caveat}` : ''}}`,
		`\\label{tab:oracle-match-k${k}}`,
		'\\end{table}',
		'',
	].join('\n');
}

async function main(): Promise<void> {
	fs.mkdirSync(OUT, { recursive: true });
	const snap = loadSnapshot();
	const orbits = ensureOrbits(snap.tilings);
	const oracleMap = JSON.parse(
		fs.readFileSync(path.join(ROOT, 'figures', 'data', 'oracle-map.json'), 'utf8')
	) as OracleMap;

	// shared colors for hand-authored figures
	fs.writeFileSync(path.join(ROOT, 'figures', 'tex', 'colors.gen.tex'), emitTexColors() + '\n');

	let entries = galleryEntries(snap, orbits, oracleMap);
	const onlyK = opt('--k');
	if (onlyK) entries = entries.filter((e) => e.k === Number(onlyK));
	const only = opt('--only');
	if (only) entries = entries.filter((e) => e.id.includes(only));

	// --- emit ---
	const toCompile: string[] = [];
	for (const e of entries) {
		const model = buildCellModel(
			snap.tilings.find((t) => t.canonicalKey === e.canonicalKey)!.cellCodec,
			orbits[e.canonicalKey]
		);
		const { ir, edgeMm } = tilingFigure(model, {
			strategy: e.strategy,
			windowMm: e.windowMm,
			edgeMm: e.edgeMm,
		});
		const tex = emitTikz(ir, { edgeMm });
		const texPath = path.join(OUT, `${e.id}.tex`);
		const pdfPath = path.join(OUT, `${e.id}.pdf`);
		const hashPath = path.join(OUT, `${e.id}.hash`);
		const hash = createHash('sha256').update(tex).digest('hex');
		fs.writeFileSync(texPath, tex);
		fs.writeFileSync(path.join(OUT, `${e.id}.svg`), emitSvg(ir, { edgeMm }));
		const upToDate =
			fs.existsSync(pdfPath) && fs.existsSync(hashPath) && fs.readFileSync(hashPath, 'utf8') === hash;
		if (!upToDate) {
			toCompile.push(texPath);
			fs.writeFileSync(hashPath, hash);
		}
	}
	console.error(`[build] ${entries.length} figures emitted, ${toCompile.length} need compile`);

	// hand-authored figures
	const handDir = path.join(ROOT, 'figures', 'tex', 'hand');
	for (const f of fs.readdirSync(handDir).filter((f) => f.endsWith('.tex'))) {
		toCompile.push(path.join(handDir, f)); // latexmk skips unchanged ones itself
	}

	// --- compile ---
	if (!flag('--no-latex')) {
		let done = 0;
		await pool(toCompile, os.cpus().length - 1, async (tex) => {
			await latexmk(tex);
			done++;
			if (done % 10 === 0 || done === toCompile.length) {
				console.error(`[latexmk] ${done}/${toCompile.length}`);
			}
		});
	}

	// --- generated includes (galleries + match tables) ---
	const k3Caveat =
		'Preliminary (NOTES \\S28): the certified $k=3$ catalogue currently misses Galebach \\#7 and contained a non-primitive duplicate (excluded here); regenerated once the catalogue is re-certified.';
	const includes: [string, string][] = [];
	for (const k of [1, 2, 3]) {
		let ke = entries.filter((e) => e.k === k);
		if (k === 3) ke = ke.filter((e) => e.tCode !== null); // exclude the known duplicate
		if (ke.length === 0) continue;
		includes.push([`gallery-k${k}.tex`, galleryTex(k, ke, k === 3 ? k3Caveat : undefined)]);
		includes.push([`match-table-k${k}.tex`, matchTableTex(k, ke, k === 3 ? k3Caveat : undefined)]);
	}

	// --- deliver ---
	if (!flag('--no-deliver')) {
		for (const e of entries) {
			if (e.k === 3 && e.tCode === null) continue; // the duplicate stays out of the thesis
			const dir = path.join(THESIS_FIG, `k${e.k}`);
			fs.mkdirSync(dir, { recursive: true });
			fs.copyFileSync(path.join(OUT, `${e.id}.pdf`), path.join(dir, `${e.id}.pdf`));
		}
		for (const [name, content] of includes) {
			fs.writeFileSync(path.join(THESIS_FIG, name), content);
		}
		console.error(`[deliver] PDFs + includes → ${THESIS_FIG}`);
	} else {
		for (const [name, content] of includes) fs.writeFileSync(path.join(OUT, name), content);
	}

	console.error('★ figure build complete');
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
