/**
 * Precompute the compatibility graph over the fifteen vertex configurations that appear in a tiling,
 * for the defense deck (`<compat-graph>`), and write it to lib/defense/vcCompatibility.ts.
 *
 * Run: pnpm tsx scripts/build-compat-graph.ts
 *
 * WHY PRECOMPUTED. The relation is the app's own `VertexConfiguration.isCompatible`, which builds the
 * partial configurations around every vertex of both figures and tries to merge them; running it for
 * all 171 pairs is a second of work and it is the same second on every slide advance. The alternative
 * — hard-coding an adjacency table read off a paper — is exactly the kind of claim this deck should
 * not be making, so the numbers come from the code that the enumeration itself used.
 *
 * WHY THE MIRROR PAIRS MERGE. The generator works with ORIENTED configurations, so it lists 3.3.4.12
 * and 3.3.12.4 separately (likewise 3.4.4.6/3.6.4.4 and 4.6.12/4.12.6). The deck has already told the
 * room there are 21 configurations and 15 of them tile, counted the way the literature counts them:
 * up to reflection. So each mirror pair collapses to its canonical name and the two nodes' edges are
 * unioned — a is compatible with b when SOME orientation of a meets SOME orientation of b, which is
 * what "these two can sit at the ends of one edge" means when the tiling may be reflected.
 */

import { writeFileSync } from "node:fs";
import { generatePolygons, generateVCsWithCompatibilityGraph } from "@/lib/algorithm/pipeline-core";
import { PolygonType } from "@/classes/polygons/PolygonType";
import type { GeneratorParameters } from "@/classes";
import { canonicalWord } from "@/lib/render/vertexFigure";

/** Every configuration that tiles has a largest tile of 12 sides, so this reaches all fifteen. */
const N_MAX = 12;

/** Closes 360 degrees, appears in no tiling of the plane: not part of the slide's fifteen. */
const NON_TILING = new Set(["3.7.42", "3.8.24", "3.9.18", "3.10.15", "4.5.20", "5.5.10"]);

const canon = (name: string) => canonicalWord(name.split(",").map(Number));

const { names } = generatePolygons({ [PolygonType.REGULAR]: { n_max: N_MAX } } as GeneratorParameters);
const { vcNames, adjacencyList } = generateVCsWithCompatibilityGraph(names);

const nodes = [...new Set(vcNames.map(canon))].filter((n) => !NON_TILING.has(n));
const adj = new Map<string, Set<string>>(nodes.map((n) => [n, new Set<string>()]));
for (const a of vcNames) {
	const ca = canon(a);
	if (!adj.has(ca)) continue;
	for (const b of adjacencyList[a]) {
		const cb = canon(b);
		if (adj.has(cb) && cb !== ca) adj.get(ca)!.add(cb);
	}
}

// Symmetry is not assumed: `isCompatible` is called once per unordered pair, but the merge it runs is
// not visibly symmetric in its arguments, and after the mirror collapse a one-sided edge would be a
// real bug. Fail loudly instead of silently drawing half an edge.
for (const a of nodes) {
	for (const b of adj.get(a)!) {
		if (!adj.get(b)!.has(a)) throw new Error(`asymmetric: ${a} ~ ${b} but not the reverse`);
	}
}
if (nodes.length !== 15) throw new Error(`expected 15 configurations that tile, got ${nodes.length}`);

const edges: [string, string][] = [];
for (let i = 0; i < nodes.length; i++) {
	for (let j = i + 1; j < nodes.length; j++) {
		if (adj.get(nodes[i])!.has(nodes[j])) edges.push([nodes[i], nodes[j]]);
	}
}

const out = `// GENERATED by scripts/build-compat-graph.ts — do not edit by hand.
//
// The compatibility graph over the fifteen vertex configurations that appear in a tiling of the
// plane: an edge joins two of them when they can sit at the two ends of one edge of a tiling, which
// is \`VertexConfiguration.isCompatible\` — the same test the seed extractor runs. Mirror pairs are
// merged, so the names are the ones the deck has already used.

export interface CompatNode {
	/** "3.4.6.4", the canonical name. */
	word: string;
	/** How many of the other fourteen it can meet. */
	degree: number;
}

/** In the deck's own order: the fifteen as they appear on the vertex-configuration slide. */
export const COMPAT_NODES: CompatNode[] = [
${nodes.map((word) => `\t{ word: "${word}", degree: ${adj.get(word)!.size} },`).join("\n")}
];

/** Unordered, each pair once, in node order. */
export const COMPAT_EDGES: [string, string][] = [
${edges.map(([a, b]) => `\t["${a}", "${b}"],`).join("\n")}
];
`;

writeFileSync("lib/defense/vcCompatibility.ts", out);
console.log(`${nodes.length} configurations, ${edges.length} edges`);
for (const n of nodes) console.log(`  ${n.padEnd(14)} ${adj.get(n)!.size}`);
