/**
 * Precompute the /defense "fix the period first" figure: a tiling's two period vectors written as
 * sums of unit ζ steps. Run: `pnpm tsx scripts/build-period-figure.ts [tilingId]`
 *
 * The slide claims the period lattice of any k-uniform tiling is generated by sums of a bounded number
 * of unit edges. This turns that sentence into the picture of one case: the 24 ζ₂₄ directions as a
 * rose, a real tiling's cell behind them, and T1 and T2 drawn as the actual chains of unit steps that
 * add up to them.
 *
 * The decomposition is SEARCHED, not asserted: breadth-first over the unit directions in exact
 * ℤ[ζ₂₄] arithmetic, so the chain it prints is a shortest one and its length IS the vector's weight —
 * the quantity `docs/SMALLK_W_BOUND.md` proves the bound on (measured maxima 5, 6, 7 for k = 1, 2, 3).
 * Writing it out means the slide cannot drift from the arithmetic: regenerate and the figure follows.
 *
 * Output: public/defense/period-figure.json
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { CyclotomicRing, Cyclotomic, setActiveRing } from "@/classes/Cyclotomic";
import { decodeGalebachVertex, reconstructOracleCell } from "@/classes/algorithm/oracleCellReconstruct";
import type { ExactCellSource } from "@/lib/services/cellCodecService";
import type { TranslationalCellData } from "@/lib/utils/renderTiling";

const N = 24;
const ring = CyclotomicRing.create(N);
setActiveRing(ring);

const wanted = process.argv[2] ?? "t2001";

type Row = { id: string; renderCell: TranslationalCellData; exactSource?: ExactCellSource };
const atlas = JSON.parse(
	readFileSync(path.join(process.cwd(), "public", "reference-atlas.json"), "utf8"),
) as Row[];

const units = Array.from({ length: N }, (_, k) => Cyclotomic.zeta(ring, k));

/**
 * A shortest chain of unit ζ steps summing to `target`, as ζ-exponents.
 *
 * Plain BFS over the 24 directions, keyed on exact cyclotomic keys — no float, so a step never lands
 * "nearly" on a lattice point. The bound proven for k ≤ 3 is 7, and |W(7)| is a few thousand, so the
 * frontier stays small; `maxWeight` is a guard, not a tuning knob.
 */
function decompose(target: Cyclotomic, maxWeight = 9): number[] | null {
	const goal = target.key();
	const zero = Cyclotomic.ZERO(ring);
	if (zero.key() === goal) return [];
	let frontier = new Map<string, { v: Cyclotomic; path: number[] }>([[zero.key(), { v: zero, path: [] }]]);
	const seen = new Set<string>([zero.key()]);
	for (let w = 1; w <= maxWeight; w++) {
		const next = new Map<string, { v: Cyclotomic; path: number[] }>();
		for (const { v, path: p } of frontier.values()) {
			for (let k = 0; k < N; k++) {
				const nv = v.add(units[k]);
				const key = nv.key();
				if (key === goal) return [...p, k];
				if (seen.has(key)) continue;
				seen.add(key);
				next.set(key, { v: nv, path: [...p, k] });
			}
		}
		frontier = next;
		if (frontier.size === 0) break;
	}
	return null;
}

const row = atlas.find((t) => t.id === wanted);
if (!row?.exactSource || row.exactSource.kind !== "seed") {
	// Survey mode: which tilings carry {T1,T2,Seed} and what their period weights are, so the figure's
	// subject is chosen on the arithmetic rather than on the id looking friendly.
	console.log(`no {T1,T2,Seed} source for "${wanted}". Candidates and their period weights:\n`);
	for (const t of atlas) {
		if (!t.exactSource || t.exactSource.kind !== "seed") continue;
		if (!/^t[123]\d\d\d$/.test(t.id)) continue;
		const a = decompose(decodeGalebachVertex(ring, t.exactSource.T1));
		const b = decompose(decodeGalebachVertex(ring, t.exactSource.T2));
		if (!a || !b) continue;
		console.log(`${t.id}  |T1|=${a.length} [${a.join(",")}]   |T2|=${b.length} [${b.join(",")}]`);
	}
	process.exit(0);
}

const src = row.exactSource;
const T1 = decodeGalebachVertex(ring, src.T1);
const T2 = decodeGalebachVertex(ring, src.T2);
const c1 = decompose(T1);
const c2 = decompose(T2);
if (!c1 || !c2) throw new Error(`no decomposition within the weight guard for ${wanted}`);

// The cell's polygons, so the figure can show the tiling the lattice belongs to rather than an
// abstract pair of arrows. Reconstructed from the same exact source the vectors came from.
const rec = reconstructOracleCell(ring, wanted, src);
if ("error" in rec) throw new Error(`cell reconstruction failed: ${rec.error}`);
const polys = rec.cell.cellPolygons.map((p) => ({
	n: p.n,
	v: (p.exactVertices ?? []).map((vx) => { const q = vx.toVector(); return [q.x, q.y]; }),
}));

const out = {
	id: wanted,
	directions: N,
	t1: { chain: c1, weight: c1.length, xy: [T1.toVector().x, T1.toVector().y] },
	t2: { chain: c2, weight: c2.length, xy: [T2.toVector().x, T2.toVector().y] },
	polys,
};
writeFileSync(path.join(process.cwd(), "public", "defense", "period-figure.json"), JSON.stringify(out));
console.log(`${wanted}: |T1| = ${c1.length} [${c1.join(", ")}], |T2| = ${c2.length} [${c2.join(", ")}], ${polys.length} tiles`);
console.log("wrote public/defense/period-figure.json");
