// Run the oracle-free family enumerator and log synchronously, so the sweep can be watched while it
// runs. Usage: pnpm tsx scripts/enum-families.ts [Vmax]
import { writeFileSync, appendFileSync, mkdirSync } from "node:fs";
import { enumerateFamilies, vertexTypes, type RealizedFamily } from "../lib/tilings/enumerate-families";

const Vmax = Number(process.argv[2] ?? 4);
const pal = { ns: [3, 4, 6], maxFlats: 12 };
const out = "experiments/results/enumerate-families-2026-08-18.md";
mkdirSync("experiments/results", { recursive: true });

const log = (s: string) => { appendFileSync(out, s + "\n"); console.log(s); };

writeFileSync(out, `# Oracle-free family enumeration — palette {3, 4, 6}, Vmax = ${Vmax}\n\n`);
log(`started, ${new Date().toISOString()}`);
const vt = vertexTypes(pal);
log(`\n## Stage 1 — vertex alphabet: ${vt.length} types\n`);
log("```");
for (const w of vt) log("  " + w.map((u) => u * 30).join("."));
log("```\n");
log("## Stage 2+3 — sweep\n");
log("```");

const t0 = Date.now();
let last = t0;
const fams: RealizedFamily[] = enumerateFamilies(pal, {
	Vmax,
	onProgress: (V, n) => {
		const now = Date.now();
		log(`  V <= ${V}: ${n} families so far   (+${((now - last) / 1000).toFixed(1)}s, total ${((now - t0) / 1000).toFixed(1)}s)`);
		last = now;
	},
});
log("```\n");

const rigid = fams.filter((f) => f.dim <= 1);
const param = fams.filter((f) => f.dim > 1);
log(`## Result: ${fams.length} families — ${rigid.length} rigid, ${param.length} parametric\n`);
const row = (f: RealizedFamily) =>
	`| ${f.V} | ${f.E} | ${f.F} | ${f.dim - 1} | ${f.tiles.join(", ")} | \`${f.signature.split("|").slice(5).join("")}\` |`;
log("### Parametric (dim - 1 >= 1)\n");
log("| V | E | F | params | tiles | face words |");
log("|---|---|---|--------|-------|------------|");
for (const f of param.sort((a, b) => a.V - b.V || a.E - b.E)) log(row(f));
log("\n### Rigid (edge-to-edge, scale only)\n");
log("| V | E | F | params | tiles | face words |");
log("|---|---|---|--------|-------|------------|");
for (const f of rigid.sort((a, b) => a.V - b.V || a.E - b.E)) log(row(f));
log(`\nfinished in ${((Date.now() - t0) / 1000).toFixed(1)}s`);

writeFileSync("experiments/results/enumerate-families.json", JSON.stringify(fams, null, 1));
log(`\nwrote experiments/results/enumerate-families.json (${fams.length} records)`);

// Emit the Atlas data file. The search costs ~1s at V <= 3 and much more above it, which is fine in a
// script and not fine on the atlas load path, so the result is generated once and committed.
const NAME: Record<number, string> = { 3: "triangle", 4: "square", 6: "hexagon" };
const label = (f: RealizedFamily) => {
	const c = new Map<number, number>();
	for (const n of f.tiles) c.set(n, (c.get(n) ?? 0) + 1);
	return [...c.entries()].map(([n, q]) => `${q} ${NAME[n]}${q > 1 ? "s" : ""}`).join(" + ");
};
const num = (x: number) => (Math.abs(x) < 1e-12 ? 0 : Math.round(x * 1e12) / 1e12);
// The constant point, then one derivative point per slider — written as (x, y) pairs. The old form
// transposed to [[x0, slope_x], [y0, slope_y]], which the header described one way and the reader read
// the other; both were right and nothing in the types said so.
const pt = (v: [number, number][]) =>
	`[${v.map((q) => `[${num(q[0])},${num(q[1])}]`).join(",")}]`;
const body = param.sort((a, b) => a.V - b.V || a.E - b.E).map((f, i) => {
	// The ranges are already a box fitted strictly inside the positivity cone by `realize`, so they need
	// no further trimming here — the shrink this used to apply was covering for an interval that could
	// run to infinity, which a fitted box never does.
	return `\t{
\t\tid: "plen-enum-${String(i + 1).padStart(2, "0")}",
\t\tlabel: ${JSON.stringify(label(f))},
\t\tV: ${f.V}, E: ${f.E}, F: ${f.F}, tiles: ${JSON.stringify(f.tiles)},
\t\tranges: [${f.ranges.map(([a, b]) => `[${num(a)},${num(b)}]`).join(", ")}], c0: [${f.c0.map(num).join(", ")}],
\t\twords: ${JSON.stringify(f.signature.split("|")[5].split("/"))},
\t\tcellPolygons: [
${f.affine.cellPolygons.map((p) => `\t\t\t{ n: ${p.n}, v: [${p.v.map(pt).join(", ")}] },`).join("\n")}
\t\t],
\t\tbasis: [${pt(f.affine.basis[0])}, ${pt(f.affine.basis[1])}],
\t},`;
}).join("\n");
writeFileSync("lib/tilings/enumerated-families.generated.ts",
`// GENERATED by scripts/enum-families.ts — do not edit by hand.
// Palette {${pal.ns.join(", ")}}, Vmax = ${Vmax}. Each entry is a family of \`ranges.length\` parameters:
// a vertex coordinate is a CONSTANT point followed by one derivative point per slider, and \`ranges\` is
// a box fitted inside the cone on which every edge length stays positive — exact for one parameter,
// conservative above it, because a cone is not a box. See lib/tilings/enumerate-families.ts for how
// these were found and what the search does and does not cover.

export interface EnumeratedFamily {
	id: string;
	label: string;
	V: number; E: number; F: number;
	tiles: number[];
	/** One open slider interval per parameter — a box fitted inside the positivity cone. */
	ranges: [number, number][];
	/** The interior sample the search laid the family out at, one value per slider. */
	c0: number[];
	/** Face corner words in 30-degree units; a 6 is a T-junction. */
	words: string[];
	/** Constant point, then one derivative point per slider. */
	cellPolygons: { n: number; v: [number, number][][] }[];
	basis: [number, number][][];
}

export const ENUMERATED_FAMILIES: EnumeratedFamily[] = [
${body}
];

export const ENUMERATION_SCOPE = { palette: [${pal.ns.join(", ")}], Vmax: ${Vmax} };
`);
log(`wrote lib/tilings/enumerated-families.generated.ts (${param.length} families)`);
