// GENERATED by scripts/enum-families.ts — do not edit by hand.
// Palette {3, 4, 6}, Vmax = 3. Each entry is a ONE-parameter family: every vertex
// coordinate is [constant, coefficient of t], and `range` is the exact open interval on which every
// edge length stays positive. See lib/tilings/enumerate-families.ts for how these were found and
// lib/tilings/length-system.ts for why the search is complete within its declared bounds.

export interface EnumeratedFamily {
	id: string;
	label: string;
	V: number; E: number; F: number;
	tiles: number[];
	/** Exact open slider interval from the positivity constraints. */
	range: [number, number];
	/** The interior sample the search laid the family out at. */
	t0: number;
	/** Face corner words in 30-degree units; a 6 is a T-junction. */
	words: string[];
	cellPolygons: { n: number; v: [[number, number], [number, number]][] }[];
	basis: [[number, number], [number, number]][];
}

export const ENUMERATED_FAMILIES: EnumeratedFamily[] = [
	{
		id: "plen-enum-01",
		label: "1 square",
		V: 2, E: 3, F: 1, tiles: [4],
		range: [0.02, 0.98], t0: 0.5,
		words: ["336336"],
		cellPolygons: [
			{ n: 4, v: [[[1,0],[-1,0]], [[1,-1],[-1,0]], [[0,-1],[-1,0]], [[0,0],[-1,0]]] },
		],
		basis: [[[-1,0],[0,0]], [[0,1],[1,0]]],
	},
	{
		id: "plen-enum-02",
		label: "2 triangles",
		V: 2, E: 4, F: 2, tiles: [3,3],
		range: [0.02, 0.98], t0: 0.5,
		words: ["2226","2262"],
		cellPolygons: [
			{ n: 3, v: [[[1,0],[-1,0]], [[0.5,-0.866025403784],[-1,0]], [[0,0],[-1,0]]] },
			{ n: 3, v: [[[0,0],[0,0]], [[0.5,0.866025403784],[0,0]], [[1,0],[0,0]]] },
		],
		basis: [[[-0.5,0.866025403784],[1,0]], [[-1,0],[0,0]]],
	},
	{
		id: "plen-enum-03",
		label: "2 squares",
		V: 3, E: 5, F: 2, tiles: [4,4],
		range: [0.02, 4], t0: 1,
		words: ["33633","36333"],
		cellPolygons: [
			{ n: 4, v: [[[0,0],[0,0]], [[1,0],[1,0]], [[1,-1],[1,-1]], [[0,-1],[0,-1]]] },
			{ n: 4, v: [[[0,0],[0,0]], [[0,1],[0,1]], [[1,1],[1,1]], [[1,0],[1,0]]] },
		],
		basis: [[[1,0],[1,0]], [[-1,2],[0,2]]],
	},
	{
		id: "plen-enum-04",
		label: "2 squares",
		V: 3, E: 5, F: 2, tiles: [4,4],
		range: [0.02, 4], t0: 1,
		words: ["36333","36333"],
		cellPolygons: [
			{ n: 4, v: [[[0,0],[0,0]], [[1,0],[1,0]], [[1,-1],[1,-1]], [[0,-1],[0,-1]]] },
			{ n: 4, v: [[[0,0],[0,0]], [[-1,0],[-1,0]], [[-1,1],[-1,1]], [[0,1],[0,1]]] },
		],
		basis: [[[0,1],[0,1]], [[2,0],[2,-1]]],
	},
	{
		id: "plen-enum-05",
		label: "2 triangles + 1 square",
		V: 3, E: 6, F: 3, tiles: [3,3,4],
		range: [0.02, 4], t0: 1,
		words: ["222","2622","33633"],
		cellPolygons: [
			{ n: 4, v: [[[0,0],[0,0]], [[1,0],[1,0]], [[1,-1],[1,-1]], [[0,-1],[0,-1]]] },
			{ n: 3, v: [[[0,0],[0,0]], [[0.5,0.866025403784],[0.5,0.866025403784]], [[1,0],[1,0]]] },
			{ n: 3, v: [[[0,0],[0,0]], [[-0.5,0.866025403784],[-0.5,0.866025403784]], [[0.5,0.866025403784],[0.5,0.866025403784]]] },
		],
		basis: [[[1,0],[1,0]], [[-0.5,1.866025403784],[0.5,1.866025403784]]],
	},
	{
		id: "plen-enum-06",
		label: "3 triangles",
		V: 3, E: 6, F: 3, tiles: [3,3,3],
		range: [0.02, 4], t0: 1,
		words: ["222","222","262626"],
		cellPolygons: [
			{ n: 3, v: [[[1,0],[0,0]], [[0.5,-0.866025403784],[-0.5,-0.866025403784]], [[0,0],[-1,0]]] },
			{ n: 3, v: [[[0,0],[0,0]], [[0.5,0.866025403784],[0,0]], [[1,0],[0,0]]] },
			{ n: 3, v: [[[0,0],[0,0]], [[0,0],[-1,0]], [[0,0],[-0.5,0.866025403784]]] },
		],
		basis: [[[-0.5,-0.866025403784],[-1,0]], [[-0.5,0.866025403784],[0.5,0.866025403784]]],
	},
	{
		id: "plen-enum-07",
		label: "4 triangles",
		V: 3, E: 7, F: 4, tiles: [3,3,3,3],
		range: [0.02, 4], t0: 1,
		words: ["222","222","2622","2622"],
		cellPolygons: [
			{ n: 3, v: [[[0,0],[0,0]], [[1,0],[1,0]], [[0.5,-0.866025403784],[0.5,-0.866025403784]]] },
			{ n: 3, v: [[[0,0],[0,0]], [[0.5,0.866025403784],[0.5,0.866025403784]], [[1,0],[1,0]]] },
			{ n: 3, v: [[[0,0],[0,0]], [[-0.5,0.866025403784],[-0.5,0.866025403784]], [[0.5,0.866025403784],[0.5,0.866025403784]]] },
			{ n: 3, v: [[[0,0],[0,0]], [[0.5,-0.866025403784],[0.5,-0.866025403784]], [[-0.5,-0.866025403784],[-0.5,-0.866025403784]]] },
		],
		basis: [[[1,0],[1,0]], [[-1,1.732050807569],[0,1.732050807569]]],
	},
];

export const ENUMERATION_SCOPE = { palette: [3, 4, 6], Vmax: 3 };
