// figures/trace/build-trace-figures.ts
/** Driver: read the frozen running-example traces and emit the trace-driven figures (F2/F3/F5/F6)
 *  as .svg (preview) + .tex (TikZ, thesis). Run: pnpm tsx figures/trace/build-trace-figures.ts
 *  Figures land in figures/out/trace/. Does NOT deliver to ../thesis. */
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { FigureIR } from '../ir/types';
import { emitSvg } from '../emit/svg';
import { emitTikz } from '../emit/tikz';
import { polygonsFigure } from './polygonsFigure';
import { loadTrace, type TorusNode, type VcNode, type PoolNode, type LatticeNode } from './loadTrace';
import { torusTreeFigure, vcTreeFigure } from './treeFigure';
import { poolFigure } from './poolFigure';

const ROOT = process.cwd();
const OUT = path.join(ROOT, 'figures', 'out', 'trace');

/** Size each figure to a target PHYSICAL WIDTH (mm) rather than a fixed mm-per-edge: these figures
 *  have very different model-unit extents (a 3-polygon row vs a 143-unit-wide tree), so a single
 *  edgeMm blows the trees up to a metre wide. edgeMm = targetWidthMm / (bbox width in model units);
 *  the emitter derives height from the bbox aspect. */
function write(id: string, ir: FigureIR, targetWidthMm: number): void {
  fs.mkdirSync(OUT, { recursive: true });
  const widthUnits = Math.max(1e-6, ir.bbox.maxX - ir.bbox.minX);
  const edgeMm = targetWidthMm / widthUnits;
  fs.writeFileSync(path.join(OUT, `${id}.svg`), emitSvg(ir, { edgeMm }));
  fs.writeFileSync(path.join(OUT, `${id}.tex`), emitTikz(ir, { edgeMm }));
  console.error(`[trace-figures] wrote ${id}.svg + ${id}.tex (${targetWidthMm}mm wide, edgeMm=${edgeMm.toFixed(2)})`);
}

// F2 — polygon set (a compact row).
write('f2-polygons', polygonsFigure([3, 4, 6]), 120);

const EX = path.join(ROOT, 'figures', 'traces', 'running-example');
// F6 — torus-fill DFS of the running example (fill 476, all 18 nodes) — wide landscape.
write('f6-torus-fill', torusTreeFigure(loadTrace<TorusNode>(EX, 'torus')), 165);

// F3 — VC search tree, curated, with the example's two VCs highlighted (portrait — height follows).
write('f3-vc-search', vcTreeFigure(loadTrace<VcNode>(EX, 'vc'), [['3','4','6','4'], ['3','6','3','6']]), 120);

const WINNER = '1|-4,0,-1,0,2,0,1,0#1|0,0,0,0,-2,0,0,0';
// F5 — vector pool + candidate lattices, winner highlighted (square).
write('f5-pool-lattice', poolFigure(loadTrace<PoolNode>(EX, 'pool'), loadTrace<LatticeNode>(EX, 'lattice'), WINNER), 85);

const README = `# Pipeline-walkthrough figures (trace-driven)

Generated by \`pnpm tsx figures/trace/build-trace-figures.ts\` from the frozen real traces in
\`figures/traces/running-example/\` (k=2 example, fill 476: 3.4.6.4 + 3.6.3.6, an 8-tile cell of
4 triangles / 2 squares / 2 hexagons). Each figure is emitted as \`.svg\` (preview) and \`.tex\`
(standalone TikZ, thesis-final).

- \`f2-polygons\` — the input polygon set {3,4,6}.
- \`f3-vc-search\` — the vertex-configuration search tree (curated slice of the real 64-node search;
  the two VCs this example uses are highlighted).
- \`f5-pool-lattice\` — the short-vector pool + candidate period lattices; the winning lattice full.
- \`f6-torus-fill\` — the torus-fill DFS (all 18 real nodes; each node is the actual partial cell).

To include in the thesis (AL/TA): \`\\input{figures/generated/trace/<id>.tex}\` after compiling the
\`.tex\` standalone, or \`\\includegraphics\` a PDF built from the \`.svg\`. CC does not write ../thesis.
`;
fs.writeFileSync(path.join(OUT, 'README.md'), README);
console.error('[trace-figures] wrote README.md');
